### ISSUE TITLE
Accepting Pull Requests: Ability to regenerate Team Invite Link

### ISSUE THREAD

**Issue by akhmerov** [mattermost/platform#1006]
If a team invite link has leaked, it appears to be impossible to invalidate the old one and create a new one. Maybe such an option exists, but it isn't easy to find in UI at all.

**Comment by it33** [comment]
Hi @akhmerov, 

Thanks for the question, the help text on the Team Invite Link dialog is out-of-date. Since it was written there are now many ways to limit sign-ups from the link, such as restricting sign-ups to email accounts from specific domains, or requiring a certain SSO option to sign-up. [Fix to help text is queued](https://github.com/mattermost/platform/pull/1009).

That said, even with the security features mentioned, it would be a nice feature to offer invalidation of the team invite link. Labeling this as "Accepting Pull Requests".

**Comment by coreyhulen** [comment]
This is fixed and in master.  It should ship with 1.2.
