### ISSUE TITLE
Accepting Pull Requests: Fix auto-link of @ mentions so they always work on usernames

### ISSUE THREAD

**Issue by tallpauley** [mattermost/platform#1130]
Username th- can't be tagged

**Comment by trashcan** [comment]
Do you mean you can't reference it with autocomplete with @th- ?

**Comment by it33** [comment]
Thanks @tallpauley! 

Appreciate the find, opening this ticket to the community, 

Proposed Title: 
Accepting Pull Requests: Fix auto-link of @ mentions so they always work on usernames

Repro: Create account with username `test-` and try to mention
Expected: @test- properly auto-links
Observed: @test- does not auto-link

Guessing that there is logic that tries to parse out certain characters adjacent to usernames, rather than checking if a username exists following an `@` symbol. 

There have been a host of bugs in this area as different developers have tried to identify usernames next to periods and punctuation, wondering if someone from the community has a better solution that what's been tried.

**Comment by trashcan** [comment]
Maybe it would be better to check if the username exists before trimming any punctuation.

**Comment by trashcan** [comment]
This is my idea of how it should work 

```
function replaceAtMentionWithToken(fullMatch, prefix, mention, username) {
    let words = text.split(' ');

    for (var c=0; c<words.length; c++) {
        if (words[c].indexOf("@") === 0) {
            let username = words[c].toLowerCase().substring(1, words[c].length);
            if (Constants.SPECIAL_MENTIONS.indexOf(username) !== -1 || UserStore.getProfileByUsername(username)) {
                words[c] = "<a class='mention-link' href='#' data-mention='" + username + "'>" + username + "</a>";
            }
        }
    }
    return words.join(' ');
}
```
Except that if there isn't a match on a word that starts with @, it should try subtracting characters off the end. Any thoughts? 

(This doesn't work because I don't quite understand how the tokens part works yet but it should show the general idea.) If there is a word that starts with @ try and match it to a username. If it doesn't match try and shorten it until you find a match or do not.

**Comment by hmhealey** [comment]
The tokens stuff is there to avoid having the formatting code deal with parsing html. For example, if we format a link, we replace it in the text with MM_LINK0, do our other parsing, and then go back and fill in the actual html tags afterwards. We had issues with our old system before where it would have a link like `example.com#anchor` and it would make the link and then parse part of the href attribute as a hashtag causing a weird link within a link to be generated.

For fixing @mentions for usernames ending in punctuation (periods, dashes, and underscores specifically), I think you've got the right idea about stripping characters off the end of the word. The regex for matching @mentions specifically avoids ending with punctuation so you can just take that part of the regex off and then try removing any trailing punctuation one by one until it finds a match. Just make sure to only trim off punctuation since we don't want cases where something like `@william` is matched because you have a user `@will`.

**Comment by lfbrock** [comment]
Thanks @trashcan, 

We created a ticket [for accepting pull requests on this issue](https://mattermost.atlassian.net/browse/PLT-813). It's listed in [the Accepting Pull Requests issues list](https://mattermost.atlassian.net/browse/PLT-797?filter=10101). [Code Contribution Guidelines](https://github.com/mattermost/platform/blob/master/doc/developer/Code-Contribution-Guidelines.md) are available for anyone interested in contributing to this project.
