### ISSUE TITLE
Feature Request: Guest access

### ISSUE THREAD

**Issue by Glueon** [mattermost/platform#1217]
As far as I remember slack has a feature which allows to create a conversation with a guest. A guest could a customer, which we want to add too a conversation so he could discuss some issues with developers, etc.

Right now we can send him an invite link and add him to the system, but he will see all our stuff in a contact list and will be able to send direct messages, read the town square. We do not want him to see that as it for private usage only. 

Are there any movements towards this idea or you could suggest a solution based on current functionality?

**Comment by manens** [comment]
Vote here : 
http://mattermost.uservoice.com/forums/306457-general/suggestions/9982719-add-restricted-users

**Comment by Glueon** [comment]
Cool thanks.

**Comment by it33** [comment]
Per [Contributing Feature Ideas](http://www.mattermost.org/feature-requests/) process, closing this issue since there's a [feature idea](http://mattermost.uservoice.com/forums/306457-general/suggestions/9982719-add-restricted-users) already filed and being upvoted on this. The addition of a cross-linked topic to discuss this more in the [feature idea discussion](https://forum.mattermost.org/c/feature-ideas) forum is highly welcome.
