### ISSUE TITLE
Idea : add autocomplete webhook

### ISSUE THREAD

**Issue by kernicPanel** [mattermost/platform#1256]
Let me explain this through an example
I've set a outgoing webhooks triggered by "$", then sended text is parsed by my bot, and runs according command. 
ie: "$start 1234" runs "start" command with "1234" args.

Autocomplete hook could work like this:
I enter "$st" and press tab, the hook is triggered, sends current text to the bot and the response populates the autocomplete list with something like [{command: […], description: […]}, […]] and whatever needed by the list.

What do you think ?

If nobody is interested by this feature, maybe someone can give me hints on how to do this ?
I'll be glad to submit a pull request, but I dont know golang or react…

**Comment by kernicPanel** [comment]
And to be perfectly clear, I've submitted the same idea to rocketchat team : RocketChat/Rocket.Chat#1308
I hope this would'nt bother anyone, I'd love to see this becoming a kind of standard feature.

**Comment by kernicPanel** [comment]
Imagine this workflow where the bot is using your github api key:
```
$addl[tab]
Autocomplete list : ['addlabel']

$addLabel [tab]
Autocomplete list : [<long list of issues>]

$addLabel 12[tab]
Autocomplete list : [<long list of issues begining with 12>]

$addLabel 1234 [tab]
Autocomplete list : [<list of available tags>]

$addLabel 1234 feat[tab]
Autocomplete list : [<list of available tags begining with feat>]
```

And so on…
This "simple" implementation allows bots to have their custom autocomplete, regarding current textline, user, chatroom, etc
And all this logic belong where it should: on the bot.

I believe this would be greatly useful.

**Comment by it33** [comment]
Hi @kernicPanel, highly appreciate the idea!

It's an interesting use case and I expect it will garners some upvotes and discussion among the community, 

You've also illustrated that our process for requesting features was ambiguous among the feature idea forum, GitHub issues and forum.mattermost.org, so we've updated our [community process](http://www.mattermost.org/feature-requests/) for this. 

So for a feature of this complexity (design of an API), the [feature ideas forum](http://mattermost.uservoice.com/forums/306457-general/suggestions/10487664-add-autocomplete-webhook) for upvotes coupled with here on the forum.mattermost.org for discussion, under feature ideas, is the right combination: https://forum.mattermost.org/t/add-autocomplete-webhook/460

In terms of feedback on the feature itself, some thoughts: 

1. You can look at the auto-complete code for adding "in:" and "from:" modifiers in search. 

2. You can look at `/loadtests` slash command for some of the logic around auto-complete--but the warning here is that code pre-dates Mattermost (it was from our original game portal written in Django, and is due to be refactored at some point). 

In terms of the API support, propose we start by hearing from the community on their thoughts, 

Closing this issue for now so the discussion can continue in the forum: https://forum.mattermost.org/t/add-autocomplete-webhook/460
