### ISSUE TITLE
Ability to change max length of username

### ISSUE THREAD

**Issue by rompic** [mattermost/platform#1380]
is it possible to change the max length of the username? I couldn't find any setting in the admin console.

**Comment by it33** [comment]
Hi @rompic, the max length of usernames is fixed so that they'll display in the lefthand sidebar without truncation, is there a specific use case you're looking for?

**Comment by christophlehmann** [comment]
Since companies use user scheme, 15 characters are not enough. For example "firstname.lastname"

**Comment by rompic** [comment]
Exactly thats the use case

**Comment by it33** [comment]
Thanks @rompic, @christophlehmann, makes sense, 

Are you looking at adding the longer usernames programatically, or having team members add them on sign-up? 

Just wondering if this is a UI issue, or a backend issue, and if we should consider an additional field on users to do the mapping to usernames beyond the current max length. 

We want to be careful around usability because we've had some users in the past inject GUIDs into the username field, and usability issues can arise,

**Comment by rompic** [comment]
Both I think. I guess this will come up automatically once mattermost supports ldap.

**Comment by it33** [comment]
Hi @rompic, appreciate your feedback and added detail. 

Since this isn't [regarding a regression or obvious error](https://github.com/mattermost/platform/blob/master/doc/process/overview.md#github-issues), propose either moving the discussion to the [LDAP thread](https://forum.mattermost.org/t/preview-ldap-sso-support/211) on the Mattermost forum, or [adding a feature idea](http://www.mattermost.org/feature-requests/) so other community members can upvote?
