### ISSUE TITLE
rename platform to mattermost?

### ISSUE THREAD

**Issue by rompic** [mattermost/platform#1393]
I really bugged me that this repository (platform) doesn't come up in githubs repository search. Did anyone think about renaming the repo? or is there a better way to increase visibility?

**Comment by it33** [comment]
In retrospect calling it mattermost/mattermost, though the cost of changing it now is probably too high. Open to other ideas

**Comment by christianpv** [comment]
@it33 I don't have much experience with changing a repository name, could you tell me why is the cost too high? I have seen the github article "renaming a repository" and it looks like it takes a lot in account for when you need to change a repository name. I'm asking because I was looking for the source before and I couldn't find it. mattermost/mattermost would be better but if you can't change the name at least put it on the description. Example: mattermost a Open source Slack-alternative in Golang and React http://mattermost.org

**Comment by it33** [comment]
At the minimum, it's changing all our install guides, build process and internal references. It's a lot of documentation, testing and updates to the community and that energy is probably better spent upgrading the product and documentation,

**Comment by it33** [comment]
Closing for now, please help [share a feature idea so community can upvote](www.mattermost.org/feature-requests/) if it feels like this is a priority?

**Comment by christianpv** [comment]
@it33 Now I understand, thanks! Could you at least change the description to "mattermost a open source Slack-alternative in Golang and React". That way if someone searches for mattermost, they will find it easier.
