### ISSUE TITLE
Feature request: Ability to change private room to public and vise versa

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [mattermost/platform#1435]
I feel this is quite an important feature to have https://mattermost.uservoice.com/forums/306457-general/suggestions/10553841-ability-to-change-private-room-to-public-and-vise

**Comment by fungos** [comment]
+1

**Comment by it33** [comment]
Thanks @phillip-white-sociomantic, highly appreciate the feature idea. Looks like it's up to 4 votes already. 

Please consider promoting it on the [Feature Idea Discussion](https://forum.mattermost.org/t/feature-idea-discussion-forum/63) for further discussion--and possibly support from developers who'd like to contribute to this change?

Also, there are some design questions that should probably be discussed--like what happens to history when a private room goes public?

Since this isn't a regression or obvious error, propose having the discussion continue either in the link you provided or perhaps a new one on the forums.

Please see our [community systems documentation](https://github.com/mattermost/platform/blob/master/doc/process/overview.md#community-systems) for an overview of how Mattermost uses GitHub Issues in coordination with other systems.
