### ISSUE TITLE
Improvement: Utilizing full width of screen for chat

### ISSUE THREAD

**Issue by jason-riddle** [mattermost/platform#1459]
There is a lot of wasted space on the right side of the screen. While not a bug, it's just a bit annoying. Are there any plans to update the width to ensure it uses the full width of the screen?

![screen shot 2015-11-18 at 2 08 57 pm](https://cloud.githubusercontent.com/assets/2156866/11251371/ec9e246e-8dfe-11e5-9a7a-912eefde4318.png)

**Comment by it33** [comment]
Hi @jason-riddle, appreciate the feedback,

Because this seems more like a feature idea than a regression or an obvious error, could we ask your help to [file a feature idea](http://www.mattermost.org/feature-requests/) for this so it can be upvoted by the community? 

There's been several discussions on this topic, but not yet a feature idea that can be upvoted and bring all conversations to one place (e.g. there are several formats for the center channel, which would be used in the full width rendering?)

Please see our [community systems documentation](https://github.com/mattermost/platform/blob/master/doc/process/overview.md#community-systems) for an overview of how Mattermost uses GitHub Issues in coordination with other systems.
