### ISSUE TITLE
@mentions should auto invite user to channel

### ISSUE THREAD

**Issue by matt-h** [mattermost/platform#1471]
Right now if someone is @ mentioned in a channel that they have not joined then they never see the notification of the message. It could either auto invite them (like Slack does) or show them the notification in some other way so they can join the channel if they would like.

**Comment by fungos** [comment]
+1

**Comment by it33** [comment]
Hi @matt-h, appreciate the feedback,

Because this seems more like a feature idea than a regression or an obvious error, could we ask your help to [file a feature idea](http://www.mattermost.org/feature-requests/) for this so it can be upvoted by the community? 

There's [an existing ticket with a third option right now](https://mattermost.atlassian.net/browse/PLT-882), open to other ideas. We just need them in the right flow. 

Please see our [community systems documentation](https://github.com/mattermost/platform/blob/master/doc/process/overview.md#community-systems) for an overview of how Mattermost uses GitHub Issues in coordination with other systems.

**Comment by it33** [comment]
@matt-h, thanks again for opening the discussion here, would this ticket address your issue? https://mattermost.atlassian.net/browse/PLT-882

**Comment by matt-h** [comment]
@it33 Yes, that would suit the needs for this feature request. Thanks!
