### ISSUE TITLE
Config request: Allow setting defaults for notification

### ISSUE THREAD

**Issue by yuvipanda** [mattermost/platform#1472]
By default mattermost notifies with a desktop notification for all messages. This can get really annoying really quickly. There should be an installation wide or team-wide setting to switch this to notify on mentions only, to prevent everyone from having to change their settings as soon as they log in.

Alternatively, the default could be changed to mention notifications only :)

**Comment by it33** [comment]
Hi @yuvipanda, appreciate the feedback,

Because this seems more like a feature idea than a regression or an obvious error, could we ask your help to [file a feature idea](http://www.mattermost.org/feature-requests/) for this so it can be upvoted by the community? 

Also, there's [a ticket to create an Introduction Message](https://mattermost.atlassian.net/browse/PLT-1262?jql=text%20~%20%22introduction%22) that could be used to suggest specific configurations be used by team members, different from the defaults. Wondering if this could help? 

Please see our [community systems documentation](https://github.com/mattermost/platform/blob/master/doc/process/overview.md#community-systems) for an overview of how Mattermost uses GitHub Issues and the Feature Ideas Forum in coordination with other systems.
