### ISSUE TITLE
Allows nontraditional TLDs

### ISSUE THREAD

**Issue by RobbieMcKinstry** [mattermost/platform#1492]
Upon starting a brand new Mattermost server, nontraditional TLDs are not accepted.
`robbie@robbiemckinstry.rocks` fails; producing the error `Please enter a valid email address`.

**Comment by it33** [comment]
Hi @RobbieMcKinstry, appreciate the feedback. 

Because this seems more like a feature idea than a regression or an obvious error, could we ask your help to [file a feature idea](http://www.mattermost.org/feature-requests/) for this so it can be upvoted by the community? 

The percentage of users with non-standard TLDs compared to the test automation necessary to properly validate such a system may make this challenging to implement.

Please see our [community systems documentation](https://github.com/mattermost/platform/blob/master/doc/process/overview.md#community-systems) for an overview of the different systems used to process community feedback.
