### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by npcode** [mattermost/platform#1520]
These links in README.md seem to be broken but I don't know the correct links.

https://pre-release.mattermost.com/core
https://pre-release.mattermost.com/signup_user_complete/?id=rcgiyftm7jyrxnma1osd8zswby
http://docs.mattermost.org/install/Docker-Single-Container/index.html
http://docs.mattermost.org/install/Amazon-Elastic-Beanstalk/index.html
http://docs.mattermost.org/developer/Code-Contribution-Guidelines/index.html

**Comment by npcode** [comment]
fyi: Here is [my script](https://gist.github.com/npcode/2cbf748a6e68f3a958d5) to find the broken links.

**Comment by esethna** [comment]
Thanks for finding this @npcode!

I've submitted a [PR](https://github.com/mattermost/platform/pull/1521) to update the last three broken links to point to the specific docs within the [GitHub repo docs folder](https://github.com/mattermost/platform/tree/master/doc) rather than docs.mattermost.org. The first two links seem to be working for me, can you confirm if they are still broken for you by manually checking them?

**Comment by npcode** [comment]
You're right. The first two links work well. It was a bug of my script.

Thanks for the fix!
