### ISSUE TITLE
Feature Request: Support UTF-8 characters in username

### ISSUE THREAD

**Issue by Kazaag** [mattermost/platform#1528]
For those of us that have non English first name it is impossible to user your real first name as user name.

The user name possible characters should be extended to all UTF-8 letters (UTF-8 define which characters are real letters).

**Comment by it33** [comment]
Hi @Kazaag, appreciate your feedback, 

Supporting UTF-8 in usernames may be difficult, as [usernames are intended to be used in URLs](https://mattermost.atlassian.net/browse/PLT-91). Some thoughts: 

1. There is an option to enter a **nickname** which does support UTF-8, and there is [a ticket accepting pull requests for adding the ability to receive mention notifications on the mention of a UTF-8 nickname](https://mattermost.atlassian.net/browse/PLT-114?jql=text%20~%20%22nickname%22)

2. Users can set their ["Teammate Name Display" option to view nickname, instead of username](https://github.com/mattermost/platform/blob/master/doc/help/Account-Settings.md#teammate-name-display), 

Just wondering to what extend these options could address your issue?

**Comment by lfbrock** [comment]
Closing this issue, it can be upvoted here: https://mattermost.uservoice.com/forums/306457-general/suggestions/11723076-support-utf-8-characters-in-username
