### ISSUE TITLE
`make clean && make dist` fails with an error

### ISSUE THREAD

**Issue by npcode** [mattermost/platform#1569]
Here is the error:

```
[12/02/15 13:34:12] [CRIT] Failed to ping db err:dial tcp 127.0.0.1:3306: getsockopt: connection refused
--- FAIL: TestGetLogs (1.00s)
panic: Failed to open sql connection dial tcp 127.0.0.1:3306: getsockopt: connection refused [recovered]
	panic: Failed to open sql connection dial tcp 127.0.0.1:3306: getsockopt: connection refused
```

**Comment by npcode** [comment]
I guess that mattermost-mysql and/or mattermost-postgres container should be started before running `dist` task.

**Comment by H3Chief** [comment]
I'm getting this when trying to use the cli to delete teams (actually any use of the cli fails with the same message).  The cli worked fine when I was on 1.2.1, and then I upgraded to 1.3, and ever since, I get the error below.

However, all the features accessible via the web UI are working perfectly fine.

```bash
[01/07/16 20:04:45] [CRIT] Failed to ping db err:dial tcp: lookup mysql on 10.248.252.201:53: no such host
panic: Failed to open sql connection dial tcp: lookup mysql on 10.248.252.201:53: no such host

goroutine 1 [running]:
github.com/mattermost/platform/store.setupConnection(0xbfe2e8, 0x6, 0xc820161f40, 0x5, 0xc820084eb0, 0x43, 0xa, 0xa, 0x0, 0x2)
	/go/src/github.com/mattermost/platform/store/sql_store.go:180 +0x5be
github.com/mattermost/platform/store.NewSqlStore(0x0, 0x0)
	/go/src/github.com/mattermost/platform/store/sql_store.go:59 +0x11c
github.com/mattermost/platform/api.NewServer()
	/go/src/github.com/mattermost/platform/api/server.go:31 +0xb5
main.main()
	/go/src/github.com/mattermost/platform/mattermost.go:57 +0x567

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 20 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 24 [chan receive]:
code.google.com/p/log4go.ConsoleLogWriter.run(0xc820072c60, 0x7f716061f1c0, 0xc820080008)
	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/termlog.go:27 +0x80
created by code.google.com/p/log4go.NewConsoleLogWriter
	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/termlog.go:19 +0x6e

goroutine 25 [chan receive]:
database/sql.(*DB).connectionOpener(0xc8201539a0)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336
```

**Comment by it33** [comment]
Thanks for the report, sorry for missing it for so long, we're working on cleaning out GitHub issues right now and getting around to this, @hmhealey, any thoughts?

**Comment by hmhealey** [comment]
Thanks @npcode for the report, and sorry that it took so long for us to get to. I've filed a ticket at https://mattermost.atlassian.net/browse/PLT-2070 and I'll be fixing the issue shortly.

@LongLiveCHIEF Since you're running mattermost directly when using the CLI, it doesn't know that the docker containers for the database need to be running. You can start them up by using `make start-docker` and then you'll be able to use it like normal

**Comment by hmhealey** [comment]
I just looked through the Makefile and you should actually be using `make dist-local` instead of `make-dist`. We don't actually want `make dist` to start up the docker containers since it is also used by our build server which builds the package differently.
