### ISSUE TITLE
System console link only accessible from the first team created

### ISSUE THREAD

**Issue by gsmet** [mattermost/platform#1575]
Hi!

In the Team menu, the System console link is only accessible from the first team I created: it's hidden for all the other teams and I have to switch to this very team before going to the System console.

I'm not sure it's the expected behavior.

Thanks!

-- 
Guillaume

**Comment by esethna** [comment]
Hi @gsmet 

This is expected behavior. Each user is distinct and owned by a team. They are different accounts with different roles. You can add other accounts on different teams as system admins from the System Console on your first account. Go to **System Console > Teams > Users**. Thanks for pointing this is out as we have to improve our help documentation on team and account creation.

**Comment by gsmet** [comment]
Hi @esethna 

Understood.

That being said, I find it weird because the system console is something global where you can modify the application setup.

**Comment by it33** [comment]
[Jira ticket now added to track this](https://mattermost.atlassian.net/browse/PLT-2057).

This is a pretty significant change, as it means making users first class objects instead of being included in teams. It does make sense.
