### ISSUE TITLE
Feature idea: Filter accents and diacritics in team url generation

### ISSUE THREAD

**Issue by gsmet** [mattermost/platform#1624]
Hi,

Currently, when a team name contains accents or diacritics, the whole letter is removed from the URL name. Example: "OWSI - Dév Spé" becomes "owsi---dv-sp". I was wondering if you could replace these accented letters by the ascii one to end up with "owsi---dev-spe".

I found this thread on stackoverflow which might be relevant: http://stackoverflow.com/questions/24588295/go-removing-accents-from-strings .

I was also wondering if we could replace the duplicate - with only one -.

(this is the last one, promise!)

-- 
Guillaume

**Comment by it33** [comment]
Hi @gsmet, appreciate the feedback, 

This sounds like two tickets to me, 

1. In Team and Channel URLs generated by default based on Team Name and Channel Name replace accented letters with ASCII equivalents. For example make "OWSI-Dév Spé" become "owsi-dev-spe" instead of "owsi-dv-sp"

2. In Team and Channel URLs generated by default based on Team Name and Channel Name only add one `-` per non-ASCII letter replaced. For example make name "tréé - top" create a default URL "tr-top" instead of "tr-----top"

^ I'm generalizing this for both team and channel URLs since the functionality is similar. 

Please let us know if this is correct, adding @esethna to take discussion from here and to file tickets for triage to see if these are appropriate to open accepting pull request tickets.

**Comment by gsmet** [comment]
Hi @it33 ,

Yes, that's it.

For 2., maybe, the example should be "tree - top" -> "tree-top" instead of "tree---top" because 1. will change the behavior of your example.

**Comment by it33** [comment]
Updated, thanks @gsmet, asking @esethna's help to open Jira tickets on these.

**Comment by esethna** [comment]
Thanks @gsmet 

Tickets created:
1. https://mattermost.atlassian.net/browse/PLT-1444
2. https://mattermost.atlassian.net/browse/PLT-1445

**Comment by lfbrock** [comment]
Closing issue, it will be tracked in Jira
