### ISSUE TITLE
Admin has ability to remove member from default channel

### ISSUE THREAD

**Issue by ralder** [mattermost/platform#172]
Is it bug or feature?

**Comment by it33** [comment]
Hi @ralder, you are correct, this is a bug. We remove the ability for users to leave the Town Square channel, but haven't disabled to the ability for admins to remove users. Town Square is to be the primary channel to reach all team members, so there's no reason an active user should not be a member. 

Happy to take a pull request for this if it's something you need as well. Otherwise we'll queue it internally.

**Comment by ralder** [comment]
I'll may pr it only for client side but not server

**Comment by it33** [comment]
Thanks @ralder, that would be appreciated, it'll at least save us some work in removing it,
