### ISSUE TITLE
Support mobile web push notifications

### ISSUE THREAD

**Issue by andrefreitas** [mattermost/platform#1723]
Even if you don't have a native android app, you can benefit of mobile web push notifications. Users just need to add the app to the homescreen in Chrome.

In this demo, the notifications work even if the app is closed: https://simple-push-demo.appspot.com/

You can read more at:
https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web?hl=en

**Comment by pedromorgan** [comment]
:+1:

**Comment by npcode** [comment]
It is really awesome! It works even after rebooting my phone! It is very helpful for android users who still don't have the native app.

**Comment by it33** [comment]
Thanks for bringing up this ticket and for @npcode for helping with an implementation, 

After review our thinking is that we want to unify how push notifications are done through mobile web and Android native and there's an investigation going on for doing that centrally. 

[Ticket available to track progress](https://mattermost.atlassian.net/browse/PLT-2051)

**Comment by bfontaine** [comment]
@it33 This ticket was eventually closed as "Won’t Do" in October. Is there something planned on this subject or has it been abandoned?

**Comment by m-lce** [comment]
@it33 I am also really interested in this feature. Let us know if we can help

**Comment by catbadger** [comment]
yes please

**Comment by bbodenmiller** [comment]
What can we do to get this reopened? Some of us are unable to install native app but mobile web notifications would even help.

**Comment by Andrew197** [comment]
Have to second this, web notifications would be very valuable in my organization

**Comment by it33** [comment]
@Andrew197 @bbodenmiller could you share more about your use case? 

If we were to add web notifications it would be through the notification server, not the main server. The issue is prioritizing means depriortizing other features. 

If you could share more about why you're not able to install native apps it could really help with the discussion.

**Comment by bbodenmiller** [comment]
Currently our organization's process to get applications VPN access inside the firewall is extremely complex and slow. We're attempting to get the app inside our firewall but it's not looking promising. Even if we get the app in we won't be able to use external notification services from Apple or Google so it looks like https://github.com/mattermost/mattermost-push-proxy won't work for us. Is there no way to implement a notifications feature similar to how the desktop app currently works?

**Comment by it33** [comment]
Hi everyone, I believe technically the push proxy server could be extended to do this. The questions are: 

# 1) How many people does this benefit? 

We moved this from a GitHub issue (not the right place, since GitHub issues are now only for bugs), to a Jira ticket (which typically means a design has been matured to the point where the ticket is ready to be implemented) however, after further analysis, the core committers weren't clear how many people this would benefit and so the ticket went to the feature propose forum, where it turned out we only had 5 votes on the proposal, so we are kind of stuck there. 

Anyone with an email address should be able to cast up to 3 votes for the ticket: https://mattermost.uservoice.com/forums/306457-general/suggestions/16853752-support-mobile-web-push-notifications

The fact that there's only 5 votes means somewhere between 2 to 5 people have cared enough to continue advocating for the feature. 

For the folks who have commented here, you should be getting email alerts and if you feel this feature is still priority, would love your help with a vote? 

# 2) Contributing who can help here 

The second issue is after we've determined people want this feature, we need someone to volunteer to implement it. If you're interested, please do indicated so in a feature proposal forum comment?

**Comment by stenrose** [comment]
@it33 any news on this? The ticket now has 39 votes.

**Comment by bbodenmiller** [comment]
Could implementing this feature also help the native app get notifications without having to use external notification services from Apple or Google?

**Comment by octavioamu** [comment]
Any update on this? 
seems now have 65 votes
![image](https://user-images.githubusercontent.com/1358093/69760452-55e87480-1143-11ea-8877-8daa8443b7be.png)
