### ISSUE TITLE
Desktop notifications are not displayed with Firefox 43 and 44 on Windows

### ISSUE THREAD

**Issue by GuillaumeAmat** [mattermost/platform#1806]
Notifications (native OS popups) are not displayed with Firefox 43 on Linux and Windows.
They are displayed when using Chrome with the same installation of Mattermost.

**Comment by it33** [comment]
Hi @GuillaumeAmat, we weren't able to repro this. 

Do you have desktop notifications enabled in Firefox for the site? 

A prompt would come up when you first started using Mattermost. 

Curious if anyone else has had the same problem?

**Comment by GuillaumeAmat** [comment]
@it33 Yes they are enabled. FYI it happens on 2 different computers (different OS and persons/users).

**Comment by tomswartz07** [comment]
I can confirm this on Firefox 43.0.4 on Linux.

**Comment by tomswartz07** [comment]
Confirming again on Firefox 44, running on Linux and Windows.
Channel icon does not get modified with new messages either.

@GuillaumeAmat: just out of curiosity: what are your notification settings? I noticed that when I enabled 'notify for all activity', I actually received less notifications than if I had 'notify for mentions only' enabled.

**Comment by GuillaumeAmat** [comment]
@tomswartz07 I didn't try enough another settings than the default one to be able to tell that sorry...

**Comment by GuillaumeAmat** [comment]
For the record, Firefox asks about display or block notifications. It detects that Matter most wants to send notifications. The problem comes after that, no notifications show up.

I didn't notice that in my previous messages...

**Comment by jlebleu** [comment]
I am using Firefox 43 on ubuntu qnd same problem, notification is working in chrome

**Comment by GuillaumeAmat** [comment]
Can anyone review my pull request? It seems to fix the issue. Thanks.

**Comment by GuillaumeAmat** [comment]
Oh, and I just signed the Mattermost Contributor Agreement ;)

**Comment by lfbrock** [comment]
@jlebleu @tomswartz07 Can you test out @GuillaumeAmat's changes on this pull request and see if it fixes your issue? 

You should be able to sign up to the spinmint test server linked in the pull request, 
https://github.com/mattermost/platform/pull/2112

**Comment by it33** [comment]
Hi everyone, 

1. Updating the title so we're clear on the issue--Firefox 43 or 44 on Windows is what we need to verify is working or not. 

2. For Linux, Mattermost only officially supports [Chrome 43+ on Arch 4.0.0 linux right now](http://docs.mattermost.com/install/requirements.html#software), and that's because of the one dev who has that as their desktop setup. We're okay taking pull requests that can support other versions but we're not tracking and repro'ing issues on those platforms because we don't have those easily available

@lindy65, can you please try to repro whether desktop notifications are working on Firefox (whichever version you have) and Windows, and see if you can verify the issue? 

Let's confirm first there's a bug, then we can take a look at the fix submitted.

**Comment by lindy65** [comment]
@it33 Notifications are not supported in Firefox 43 but are in Firefox 44.  Instructions for setting up notifications: https://support.mozilla.org/en-US/kb/push-notifications-firefox?as=u&utm_source=inproduct#w_upgraded-notifications

**Comment by tomswartz07** [comment]
Hi all: 

Apologies in advance for the wall of text:

@it33 I don't think that the Issue rename properly reflects the issue. I'm seeing the same issue on Archlinux.

I think @lindy65 is referring to 'web push' notifications, which were recently added to Firefox. These allow for notifications even if the website is closed. (Facebook chat recently added this feature, for example/reference).

However, that's not the issue here.
The main issue here is that any type of notifications are not being consistently shown; regardless if they are standard or 'web push' type notifications.
When I say notification, I am referring to the [standard W3 notifcation API](https://www.w3.org/TR/notifications/) and not the [Push API](https://www.w3.org/TR/push-api/). These standard notifications were part of Firefox [since version 4](https://developer.mozilla.org/en-US/docs/Web/API/notification#Browser_compatibility)

I can, again, confirm that notifications do not appear on Firefox 44.0.2 on Archlinux. 
`4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux`

For me, simply changing to Chrome is not reasonable, as I do not particularly care to run a RAM-heavy browser just for one web-chat program. I know for others, trying to match the Arch requirement to replicate your support structure might also be a huge headache.

I gotta say, I'm a bit disappointed that the past few responses were quite dismissive. 
We're obviously trying to help resolve this issue.
There are at least three folks here saying that they can repro the issue, but you still want to 'confirm [that] there's a bug' and then hand off generic Firefox instructions when we've clearly stated that we have allowed all notifications in the browser for our Mattermost instances.

I'm not quite sure what else there is that we could do at this point.
It's really frustrating to me that I am missing notifications of messages simply because I'm running Firefox, particularly when there's a fix offered.

**Comment by it33** [comment]
@tomswartz07 sorry, my fault, I didn't mean to sound dismissive, or suggest you change browsers--just wanted to be transparent on what we are able and unable to verify and support, 

We have a [test server up for the PR](https://github.com/mattermost/platform/pull/2249#issuecomment-188658767), thanks to @GuillaumeAmat 

Would you be open to verifying the fix works? 

If so, we can merge it,

**Comment by GuillaumeAmat** [comment]
Damn! I pulled the latest "dev" Docker image and I still don't see notifications in Firefox. Is it just me?

**Comment by hmhealey** [comment]
They still work fine for me on our pre-release server using Firefox 44 on Winows 10 although they've always worked for me. What does it print if you type `Notification.permission` in the Firefox dev console when you're in Mattermost?

**Comment by GuillaumeAmat** [comment]
@hmhealey What? They have always worked for you? How lucky you are! ;)
`Notification.permission` says `"granted"`.

**Comment by it33** [comment]
Does anyone else see notifications on Firefox not working after the fix? 

If so, please share what OS and which FireFox version?

**Comment by tomswartz07** [comment]
I don't have update access to our install here (just a lowly peon user), so
I'll have to wait for the latest release update is installed after the
16th.

I'll gladly report back after that.

**Comment by GuillaumeAmat** [comment]
Anyone? Am I the only one to have that bug anymore? I'm cursed... ;)

**Comment by GuillaumeAmat** [comment]
It's working! \o/ My last issue was caused by a bad Firefox profile (my bad...).

**Comment by acroyear** [comment]
I'm still having this issue on a Windows 7 Firefox instance, version 47 (just updated), on site http://p.subfireplayer.net/ - it works just fine on a mac. I've wiped the site from notifications, gotten the prompt, clicked always allow, and it continues to not work after doing so, silently.

**Comment by nimd4** [comment]
>  acroyear commented 17 days ago

I'm still having this issue on a Windows 7 Firefox instance, version 47 (just updated), on site http://p.subfireplayer.net/ - 

That whole site looks b0rked, opening http://p.subfireplayer.net/ throws me  into http://p.subfireplayer.net/#artists & the web page is, like, blank; screenshots@ 

![screenshot_2016-07-02_02-11-30](https://cloud.githubusercontent.com/assets/4793577/16537019/8e5fbe0e-3ffa-11e6-90c7-df204fd6f1ea.png)
![screenshot_2016-07-02_02-12-25](https://cloud.githubusercontent.com/assets/4793577/16537020/8e606f2a-3ffa-11e6-9c0a-28626053170e.png)

xD

**Comment by acroyear** [comment]
The notifications in question only happens when you actually start playing something.

The site there in your screenshot is in "artist" mode. It starts with just the letters on the left. click a letter and the list of artists that start with that letter appear. click an artist from there and you'll get the albums, with the ability to "play all", shuffle, top songs, etc.

Once that's clicked, you should see a notification (and/or get prompted to accept notifications). On Windows 7, I get a prompt to accept them, but after that, the notifications don't actually appear. It works fine on Mac and Linux.

**Comment by luisclaudiogama** [comment]
My Notifications is OK at Firefox only WITHOUT icon...the notifications with icon works fine in Chrome but not at Firefox...I´m using Linux.

			function notify(str) {
			    Notification.requestPermission(function() {
			        var notification = new Notification("SaborDelivery", {
			        //    icon: "<?php echo base_url()?>images/marca_sabor.png",
			            body: str
			        });
			    });
			}
