### ISSUE TITLE
New Community Items - Matterbot and Matterfront

### ISSUE THREAD

**Issue by LongLiveCHIEF** [mattermost/platform#1823]
> Check out some projects for connecting to Mattermost:

You may add [Matterbot](https://github.com/geekytime/matterbot) and [Matterfront](https://github.com/lloeki/matterfront) to your list if you wish.

**Comment by it33** [comment]
Thanks! 

[Matterfront is listed](http://www.mattermost.org/community-applications/#native). Per our discussion a few weeks ago, the name "matterbot" overlaps with a pre-released feature so it's difficult for us to promote due to potential confusion. If we could find a name with less risk, would be happy to list it. 

Also, there's now [a form available to share new community applications and installers](https://spinpunch.wufoo.com/forms/mattermost-integrations-and-installers/).
