### ISSUE TITLE
Accepting Pull Requests: Remove "Disable Files Storage" option from System Console > File Storage (Good First Contribution) 

### ISSUE THREAD

**Issue by okin** [mattermost/platform#1871]
I just did setup a mattermost instance and wanted to disable storing files in the System Console -> File Settings.
But upon selecting *Disable File Storage* and then pressing *Save* I got an error message:

    Invalid driver name for file settings. Must be 'local' or 'amazons3'

**Comment by it33** [comment]
Thanks @okin, we're planning to remove the _Disable File Storage_ option as it was originally included as and alternative to S3, but since we added local storage as an option, it probably doesn't make sense to support this any more. Also, file storage is needed for Profile Pictures. 

Just curious, were you reporting the issue because you happened to notice it, or is there a scenario where disabling file storage was important to your deployment?

**Comment by okin** [comment]
Hello @it33,
I did neither know about the requirement for profile pictures nor the plans to remove this setting. 
I'd be fine with removing this then as we do use profile pictures and plan on keeping them. ;)

My original plan was to disable storing of files on mattermost. We do have a central file storage and I did not want to have another place where people may need to look for files and that I'd need to backup.

**Comment by it33** [comment]
Closing since we have a Jira ticket for this

**Comment by digitalageexperts** [comment]
I'm looking to use Mattermost for my company mostly because Slack is blocked behind our clients firewall.  It's blocked due to the file sharing aspect.  I was hoping to be able to disable file sharing with mattermost, but it seems you've recently removed that option.  Is it possible to reintroduce the option and just default it to enabled?  Seems like it would be an easy win if it existed before.
