### ISSUE TITLE
posts don't auto-update after editing

### ISSUE THREAD

**Issue by finius** [mattermost/platform#1914]
After a user edits his post, he needs to reload the page to see his modified post in the chat history

**Comment by finius** [comment]
This issue is regarding the iOS app. Sorry for not specifying this

**Comment by it33** [comment]
Thanks @finius for your question, 

I've tested this on master and am unable to repro. 

Because this seems to be more a troubleshooting discussion than a product defect, could we have your help posting this to the [Troubleshooting Forum](http://www.mattermost.org/troubleshoot/)? 

Please include repro steps, so members from the community will better be able to help solve your issue. Please add a link back to your new post from this ticket and close this ticket so it’s easier to keep track of issues? 

The situation you're describing is one where web sockets isn't properly configured and the blue bar message is dismissed, which would cause the page to "appear" to load correctly but--because websockets don't work--there would be no real time functionality.
