### ISSUE TITLE
Webhook/bot support for direct messages

### ISSUE THREAD

**Issue by brightsparc** [mattermost/platform#1965]
Hi,

With the aim of being slack compatible. Are there any plans to support the slack bot users or webhooks for direct messages instead of being limited to public channels?
see: https://api.slack.com/bot-users

Thanks,
Julian.

**Comment by lfbrock** [comment]
There's no direct plan to implement bot users at the moment, but we are considering [allowing outgoing webhooks in private groups/direct messages](https://mattermost.atlassian.net/browse/PLT-1655). Our APIs are open, so it's possible to get a session token and connect that way if you want to build your own integration. 

We have also updated Slash Commands, which should be available in v1.5.

**Comment by brightsparc** [comment]
Outgoing webhooks in private groups would be a useful feature. I'm fine with working via webhooks instead of we sockets.

**Comment by it33** [comment]
You can also use [the full Mattermost API to create bots](http://docs.mattermost.com/developer/api.html)--not just a subset. 

There's a few ideas on this thread, could we have your help [adding a feature idea](www.mattermost.org/feature-requests/) that could be more openly discussed and upvoted by the community? 

Closing this issue for now since it seems more a like a feature idea,
