### ISSUE TITLE
Some settings reset to default after updating Gitlab Omnibus

### ISSUE THREAD

**Issue by reekers** [mattermost/platform#2006]
When updating Gitlab several settings are reset in Mattermost. Incoming and outgoing webhooks are set to false, but the webhooks are remembered, so just resetting them to true enables them again. 

Same goes for email settings. The settings are remembered, but have to reset it to use STARTTLS again. Also allow sign up with email is enabled, while I disabled it. 

Seems there are some defaults that get set when updating. This happened the last two times I updated Gitlab.

**Comment by it33** [comment]
Hi @reekers, please see [GitLab Mattermost documentation](https://gitlab.com/gitlab-org/omnibus-gitlab/tree/master/doc/gitlab-mattermost#upgrading-gitlab-mattermost) for updating GitLab Mattermost. 

If you're manually updating GitLab Mattermost instead of using the omnibus configuration file you can follow the documentation to migrate Mattermost to a different directory.
