### ISSUE TITLE
accidentally change port to 8065. 

### ISSUE THREAD

**Issue by kybin** [mattermost/platform#2024]
Hi, I tested things and accidentally change the port to 8065.
I restarted docker then everythings are blown away.
I tried change it back to 80 by change the ListenAddress in config.json
But it still listen from 8065. How do I change it back?
Thank you.

**Comment by it33** [comment]
Thanks @kybin for your question, 

Because this seems to be more a troubleshooting discussion than a product defect, could we have your help posting this to the [Troubleshooting Forum](http://www.mattermost.org/troubleshoot/)? 

Please include repro steps, so members from the community will better be able to help solve your issue. Please add a link back to your new post from this ticket and close this ticket so it’s easier to keep track of issues? 

Please note that if you downloaded the "Preview" Docker image, it's not intended for production use or significant configuration. Please consider the [Production Docker](http://www.mattermost.org/installation/) setup offered by the community if you're looking more long lasting.
