### ISSUE TITLE
"The database schema version of 1.2.1 cannot be upgraded.  You must not skip a version."

### ISSUE THREAD

**Issue by yetzt** [mattermost/platform#2035]
i use mattermost from gitlab. after upgrading gitlab, it says `The database schema version of 1.2.1 cannot be upgraded.  You must not skip a version.`. how can i fix that?

i found [this](https://github.com/mattermost/platform/blob/master/doc/install/Upgrade-Guide.md#upgrading-gitlab-mattermost-when-gitlab-upgrade-skips-versions), but there is no `platform` binary.

**Comment by yetzt** [comment]
so, i "fixed" it by downgrading gitlab again and pinning that specific gitlab-version. so, mattermost can't handle version upgrades, but new, breaking versions are bundled with gitlab. that isn't the best of ideas.

**Comment by it33** [comment]
Please see [GitLab Mattermost documentation on upgrading](http://docs.mattermost.com/integrations/gitlab.html#upgrading-gitlab-mattermost). The next release of Mattermost supports upgrading from 2 previous versions: https://github.com/mattermost/platform/pull/2016

Certainly appreciate the feedback--and agree improvement was needed. 

Closing this issue since there isn't an issue with the documented upgrade process.
