### ISSUE TITLE
mattermost docker cannot raise privileges of user to system-admin from command line

### ISSUE THREAD

**Issue by saundsr** [mattermost/platform#2078]
I have a case where I'm trying to promote a user to system-admin.  

I gain shell access to the docker via "docker exec -it mattermost-dev /bin/bash"

I navigate to /mattermost/bin

and run the command  ./platform -assign_role -team_name="team name" -email="useremail" -role="system_admin"

The user logs out and back in and doesn't have system admin access.  

After running the ./platform command the output is :

panic: Failed to open sql connection dial tcp: lookup mysql on 8.8.8.8:53: no such host

goroutine 1 [running]:
github.com/mattermost/platform/store.setupConnection(0xc13e50, 0x6, 0xc8201d4210, 0x5, 0xc82000aff0, 0x43, 0xa, 0xa, 0xc8200f3900, 0x2)
        /go/src/github.com/mattermost/platform/store/sql_store.go:180 +0x5be
github.com/mattermost/platform/store.NewSqlStore(0x0, 0x0)
        /go/src/github.com/mattermost/platform/store/sql_store.go:59 +0x11c
github.com/mattermost/platform/api.NewServer()
        /go/src/github.com/mattermost/platform/api/server.go:31 +0xb5
main.main()
        /go/src/github.com/mattermost/platform/mattermost.go:66 +0x688

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 9 [chan receive]:
code.google.com/p/log4go.ConsoleLogWriter.run(0xc820016d20, 0x7f0134fc41e8, 0xc820028010)
        /go/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/termlog.go:27 +0x80
created by code.google.com/p/log4go.NewConsoleLogWriter
        /go/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/termlog.go:19 +0x6e

goroutine 10 [chan receive]:
database/sql.(*DB).connectionOpener(0xc82013df40)
        /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:481 +0x336

It seems to be having a problem accessing the database, any recommendations?

**Comment by it33** [comment]
Thanks @saundsr for your question, 

Because this seems to be more a troubleshooting discussion than a product defect, could we have your help posting this to the [Troubleshooting Forum](http://www.mattermost.org/troubleshoot/)? 

Please include repro steps (including which Docker image you used, a link to instructions you followed and whether you were able to get Mattermost running before executing the command), so members from the community will better be able to help solve your issue. 

Please add a link back to your new post from this ticket and close this ticket so it’s easier to keep track of issues?
