### ISSUE TITLE
Lost administration permissions

### ISSUE THREAD

**Issue by vegegoku** [mattermost/platform#2084]
Dears,
i am just trying mattermost locally on my laptop, i was able to install it following the instructions from the site, but while trying app i changed my only account from system admin to team admin, i didnt click on save button was actually disabled, i cant open the system console since i have no permission , i checked the trouble shooting and they say that i need to execute a command to restore my administration permissions, but i cant find the location for the platform file from the command :
Command : 
```
./platform -assign_role -team_name="yourteam" -email="you@example.com" -role="system_admin"
Error : bash: ./platform: No such file or directory
```

i am using ubuntu 15.10

any idea where i can find the file to execute the command?

**Comment by coreyhulen** [comment]
Where did you unzip Mattermost?  maybe ~/mattermost/bin

**Comment by it33** [comment]
Thanks @vegegoku for your question, 

Because this seems to be more a troubleshooting discussion than a product defect, could we have your help posting this to the [Troubleshooting Forum](http://www.mattermost.org/troubleshoot/)? 

Please include repro steps, so members from the community will better be able to help solve your issue. Please add a link back to your new post from this ticket and close this ticket so it’s easier to keep track of issues?
