### ISSUE TITLE
Error regarding fonts on Chrome 48 and Arch Linux

### ISSUE THREAD

**Issue by raduab** [mattermost/platform#2098]
in the console, I get:

downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans" style:normal weight:600 stretch:normal src index:3) source: https://chat.webative.net/static/fonts/open-sans-v13-latin-ext_latin_cyrillic-ext_greek-ext_greek_cyrillic_vietnamese-600.woff2

After a quick search, I found that a possible solution is to change the fonts provider:

https://stackoverflow.com/questions/35206815/font-loading-error-downloadable-font-kern-too-large-subtable-table-discarded

**Comment by it33** [comment]
Hi @raduab, appreciate the report, could you let us know the browser and OS you're using and steps to reproduce?

**Comment by raduab** [comment]
I was using Chromium Version 48.0.2564.97 (64-bit) on Arch Linux (kernel version 4.4.1-1). However I am unable to reproduce it now. I'll come back if it happens again.

**Comment by it33** [comment]
Cool, thanks,

**Comment by danger89** [comment]
Happens still.. Firefox v75:

![image](https://user-images.githubusercontent.com/628926/80391841-96911900-88ae-11ea-8c12-9fdc8f257291.png)

**Comment by danger89** [comment]
Related:

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1185685#c3
And:
https://bugzilla.mozilla.org/show_bug.cgi?id=1211993#c2

This is due to Open Sans has a massive character set, and therefor kerning table. It's maybe up to Open Sans to fix it. Or could you reduce the Open Sans font, maybe by removing some features from the woff2 files (special chars or?).
