### ISSUE TITLE
browser cannot get css files when mattermost installed in windows environment

### ISSUE THREAD

**Issue by arazzak4u** [mattermost/platform#2174]
I need to install mattermost in windows environment. I compiled all the go code in windows. Got all the compiled react files from the latest distribution and run the compiled go file. Mattermost is up and running but the css is not loading.  i can see that the css files are listed in the source node of the developer tools in the browser but when i click to see the css there is nothing there. ALSO the browser successfully gets the JS files from server but not the css.If i run the css file link directly from browser it downloads the css file which means the link is working but it does not show the css file in the browser which it should.  Please HELP!

**Comment by it33** [comment]
Thanks @arazzak4u for your question, 

Because this seems to be more a troubleshooting discussion than a product defect, could we have your help posting this to the [Troubleshooting Forum](http://www.mattermost.org/troubleshoot/)? 

Please include repro steps, so members from the community will better be able to help solve your issue. Please add a link back to your new post from this ticket and close this ticket so it’s easier to keep track of issues?

**Comment by arazzak4u** [comment]
Hi,
I have posted this issue in troubleshooting forum : 

https://forum.mattermost.org/t/browser-cannot-get-css-files-when-mattermost-installed-in-windows-environment/921
