### ISSUE TITLE
Mixed content warning when loading images with unsecure URLs

### ISSUE THREAD

**Issue by webative-net** [mattermost/platform#2184]
When users are posting links to images with an insecure url and the server is hosted with ssl, a mixed content warning is shown in the browser's console and the security icon from the address bar is changed accordingly.

The reason is that the thumbnail image is not generated by mattermost and instead the thumbnail image source is taken from the posted link. A solution would be for mattermost to generate a thumbnail on the server on the fly, and use that local link instead, with the proper http scheme.

**Comment by lfbrock** [comment]
Thanks @patoupatou, appreciate your feedback, 

To keep feature idea discussions in one place, could we have your help: 

1. [Contributing this in the feature idea forum](http://www.mattermost.org/feature-requests/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)? If you're interested in implementing, please say so and we'll prioritize the review. 

2. Posting a link back from the feature idea forum to this thread?

**Comment by webative-net** [comment]
I thought this was a bug though.. anyways, as you say.

**Comment by jnugh** [comment]
I would consider this a bug, not only because of the mixed content warning when loading http content (which makes a lot of trouble e.g. in the desktop app, see https://github.com/mattermost/desktop/issues/161).

This is also related to the following: Imagine I would like to gather data about the users of a Mattermost team, there are public teams like Contributors on pre-release and there will "Single-Channel Guest Accounts" in the [future](https://about.mattermost.com/direction/):
* I could link to an image on my own server, maybe backed by a script which adds/reads cookies, gets user agent, ip address, ...
* I could embed a tracking pixel, like Google Analytics, to get detailed information about the users (age, sex, interests, ...)

The user does not even have to click somewhere, the image is being transferred automatically. Most sites that allow image embedding fix this, by running a proxy that fetches the image and delivers it to the user, this indirection would make all users look the same to the delivering server.
