### ISSUE TITLE
Not enough space between nick and email address

### ISSUE THREAD

**Issue by rompic** [mattermost/platform#2197]
![ohne titel 2](https://cloud.githubusercontent.com/assets/6322123/13184202/cd414e40-d73a-11e5-8224-54f99a78d1b0.png)

**Comment by it33** [comment]
Thanks @rompic for the bug report, 

Can you help [add more information](http://www.mattermost.org/filing-issues/) so we can reproduce the issue?

**Comment by rompic** [comment]
- open the system console in mattermost 2.0
- Click on the team/<your team>/users menu item
- the "more-name" and "more-description" spans are directly next to each other

**Comment by it33** [comment]
Sorry, clicked the menus in Mattermost 2.0 and I'm not seeing this. 

Can anyone in the community running Mattermost 2.0 repro this issue?

**Comment by Eadrom** [comment]
I'm running Mattermost 2.0 on an Ubuntu 14.04 machine using the production setup guide (not using the docker container).  I am also seeing this issue.  As far as reproducing this, I just followed the guide at http://docs.mattermost.com/install/prod-ubuntu.html to make a cloud-init script.  Here's my exact setup script if you want to see exactly what I'm doing:

http://gitlab.1geek4solutions.com/eadrom/mmsetup/blob/master/mmsetup.sh

**Comment by it33** [comment]
Thanks @Eadrom, thanks @rompic, 

Sorry, I just need help understanding where in the UI you're seeing this, as I'm not seeing it...

**Comment by PSchwarck** [comment]
@it33 @finius
Hi Ian, Martin ran into the same issue on friday, after we upgraded to 2.0. I can ask Martin to provide a screenshot for you.

**Comment by david-at** [comment]
Currently running 2.0 on CentOS 7. 

This is reproducible on the following for me:
Chrome 48.0.2564.109 on Mac
Safari 9.0.3 (11601.4.4) on Mac
Firefox 44.0.2 on Mac

I would more classify this as just visual styling more than anything.

How to reproduce:
1. Login as a System Admin on MM 2.0
2. Go into the System Console
3. Under Teams, find a team and select "- Users"
4. Any user on this page will have the problem.

Current issue: Spacing is not visually appealing.

<img width="1098" alt="screen shot 2016-02-21 at 5 46 42 pm" src="https://cloud.githubusercontent.com/assets/10410822/13206853/a80a72d4-d8c3-11e5-8c8e-225e882a11bc.png">

Expected Behavior: A more visually appealing look for usernames and emails (example image, first row):
<img width="1059" alt="screen shot 2016-02-21 at 5 46 55 pm" src="https://cloud.githubusercontent.com/assets/10410822/13206860/c2d72a76-d8c3-11e5-95f8-c5a750a67637.png">

The example was drawn up using the console in any browser to adjust the code on the fly. 
I adjusted the span tags to p tags and added the following css:

`.more-name {
    font-weight: bold;
    margin-bottom: 0;
}
.more-description {
    margin-bottom: 0;
}`

The margin-bottom cleans up some spacing that the p tag puts in place. and the bold is just to clean up and give some weight to the name. 

The P is created here: 

https://github.com/mattermost/platform/blob/45dfd516aab37c1c336ac3410ee8db0d7c56d65a/web/react/components/admin_console/user_item.jsx#L363

IT looks like .more-name and .more-description are used in a few places. maybe need to split out to a separate class for this page? I have not tested how this looks on windows or linux, it may render differently.

**Comment by david-at** [comment]
@it33 If you would like, I can put together a Pull Request for this if you're OK with splitting out into a new class for this item. I can see all the places that these classes are currently used and there might be some issues with styling on those pages.

**Comment by rompic** [comment]
@david-at thanks for the detailed analysis

**Comment by it33** [comment]
Thanks @david-at, highly appreciate the analysis, @asaadmahmoodspin, would this PR work for you?

**Comment by asaadmahmoodspin** [comment]
Hey guys, I've already fixed this, so no need for a PR.

**Comment by it33** [comment]
Thanks @asaadmahmoodspin!

If anyone still has an issue, please open a new ticket, or re-open this one, thanks again for the detailed reporting!
