### ISSUE TITLE
Bug in allow anyone to sign-up from login page?

### ISSUE THREAD

**Issue by chengweiv5** [mattermost/platform#2251]
I have a team and has **Allow anyone to sign-up from login page** enabled, however, an user without invited can not automatically join into the team from the team url.

BTW, I configured GitLab SSO and has sign up disabled because I'd like all user comes from GitLab.

Does this a bug?

**Comment by jwilander** [comment]
Hi @chengweiv5, is the user attempting to sign up with GitLab SSO and being denied?

**Comment by chengweiv5** [comment]
@jwilander I'm not sure if I understand **Allow anyone to sign-up from login page** clearly.

The situation is:

1. I have GitLab SSO setup
2. I **disabled signup**
3. Enable **Allow anyone to sign-up from login page**

What I expected is:

Any user **signed in** with GitLab SSO can join the team

The fact is:

The user **signed in** with GitLab SSO still can not join the team, nothing changed from **enabling Allow anyone to sign-up from login page**.

Is this expected?

**Comment by lfbrock** [comment]
Hi @chengweiv5, 

I think right now GitLab Sign In and GitLab Sign Up are combined into one setting. I created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-2177) to split them into two settings, like how it currently is for email sign in/sign up. 

Would that fix this issue? 

Also to clarify, the expected behaviour of "[Allow anyone to sign-up from login page](http://docs.mattermost.com/help/settings/team-settings.html#allow-anyone-to-sign-up-from-login-page)" is that when true it adds the "Create an account" link to the login page. Turning off "[Enable Sign Up with GitLab](http://docs.mattermost.com/administration/config-settings.html#gitlab-settings)" would not let anyone sign up with GitLab, even if it was from an email invitation or the "Get Team Invite" link.

**Comment by chengweiv5** [comment]
@lfbrock thanks, I'm not quite clear now with this.

**Comment by chengweiv5** [comment]
After having **EnableSignUpWithEmail** turns to `true`, a newly created account can join the channel automatically, **but doesn't works for existing users**.

How about enable that for **exist user**? so that the team behaves like a **public** team.

**Comment by lfbrock** [comment]
Hi @chengweiv5, sorry I'm not understanding what you mean. Can you describe what you mean by a **public** team? 

To allow anyone (new or existing) to join a team with a GitLab account:

1. Set `Enable Sign Up With GitLab` to `true`
2. Set `Allow anyone to sign-up from login page` to `yes`
3. To get on to the team, New Users must use "Create an Account" and Existing Users must use "Sign In with GitLab". 

There is a [bug](https://mattermost.atlassian.net/browse/PLT-2044) where New Users must use the *Create an Account* option to join the team. Clicking the "Sign In with GitLab" will not work for New Users. 

![capture 2016-03-05 at 15 20 55](https://cloud.githubusercontent.com/assets/9354841/13539186/c8a83154-e21c-11e5-94a2-a0f4fea292cc.png)

To allow Existing Users to sign in with GitLab, but to not allow any New Users to sign up:

1. Set `Enable Sign Up With GitLab` to `true`
2. Set `Allow anyone to sign-up from login page` to `no`
3. Existing Users must use "Sign In with GitLab", and there is no "Create an Account" link for New Users
4. Optional: Set `EnableUserCreation` to `false`, and New Users will not be able to sign up from an email invitation or the "Get Team Invite" link.

**Comment by chengweiv5** [comment]
@lfbrock, thanks for your detail answer! I think PLT-2044 is exactly what I want, +1 there.
