### ISSUE TITLE
email notifications on @all mentions doesn't seem to work in 2.0 ENT-7

### ISSUE THREAD

**Issue by finius** [mattermost/platform#2311]
When a user uses @all in any channel, no email notification is send to every member of the team.

**Comment by lfbrock** [comment]
Hi @finius, 

We turned off `@all`, and plan to add it back in with a permission setting on who can use it (so teams can choose if they want to restrict it so only admins can use it). 

In the mean time, you should be able to use `@channel` in town square to mention all users on the team. 

You can upvote the feature request for adding `@all` back in here: https://mattermost.uservoice.com/forums/306457-general/suggestions/11459901-add-all-mention-as-a-mention-as-a-configurable-op

**Comment by finius** [comment]
Hm, okay. But if one could reach the same behaviour using @channel in "town square" instead of @all, why did you remove that feature at all, when everybody has to be member of town square?

**Comment by lfbrock** [comment]
We removed it because some people were having problems with users over-using `@all` and had no way to turn it off, and since the same behaviour could be achieved using `@channel` in Town Square we didn't see what the benefit of `@all` was. 

It seems like `@all` is more obvious for users though, so we do plan on adding it back in, we just want to make it more useful by adding the option to set permissions on who can use it.

**Comment by finius** [comment]
ok, hopefully these users didn't know @channel yet ;-) 
Thanks for the feedback on this! I'll inform our team about it

**Comment by finius** [comment]
one last hint: maybe it could make sense to disable auto completition for @all to not make users think, this feature still exists and should be functional

**Comment by esethna** [comment]
Thanks @finius, agree, filed a [bug](https://mattermost.atlassian.net/browse/PLT-2193) on this.
