### ISSUE TITLE
Searching keyword with spaces not returning specific result

### ISSUE THREAD

**Issue by pmsudhi** [mattermost/platform#2315]
when i search for "Dev Task" (within quote), the search result comes for "QA Task" and "Dev Task" also. any suggestions

**Comment by lfbrock** [comment]
Hi @pmsudhi, 

What database are you using? 

There's a known issue with quotation searches not working properly in postgres, we have a [ticket](https://mattermost.atlassian.net/browse/PLT-1459) to go look into it.

@esethna, can you help update our documentation on what kinds of searches are supported by each database at the moment?

**Comment by esethna** [comment]
@pmsudhi , search behavior is heavily dependent on the database you are using. Please see the [Search Notes](http://docs.mattermost.com/help/getting-started/searching.html#search-notes-and-known-issues) section of the documentation for what is currently supported and known issues.

**Comment by pmsudhi** [comment]
Sorry for not providing full details. I am using matter most with gitlab8.4 omnibus package. so i guess currently i have to live with it.Since lots of information pushed into channel in a Devops environment, searching is very critical thing.

**Comment by it33** [comment]
Thanks @pmsudhi, there's [a ticket to add support for searching phrases in Postgres](https://mattermost.atlassian.net/browse/PLT-1459) and I've set it to retriage to reconsider the priority and to open it up for community contributions to fix. You can track the status of the issue in Jira as an approved change to be made. 

If you're using GitLab, the default database is Postgres, which is why you're hitting this issue (it works for MySQL users). 

One workaround to consider is using hashtags like `#qa-task` and `#dev-task`, which create hashtag links and can help you quickly tagged posts from your automated systems (it's what the Mattermost core team uses internally).
