### ISSUE TITLE
Missing date stamp in Search Results

### ISSUE THREAD

**Issue by tvld** [mattermost/platform#2379]
MM 2.1:
![mm-2 1-date](https://cloud.githubusercontent.com/assets/986182/13601885/67e5a684-e533-11e5-80d6-3f23be115154.png)

**Comment by lfbrock** [comment]
Hi @tvld, 

The date stamp should be available if you scroll up in the centre channel?

To make this more usable, we also have tickets to:
1) [Switch all time stamps to absolute time](https://mattermost.atlassian.net/browse/PLT-1914) (instead of using  the "14 days ago")
2) [Have date markers stick to the top of the channel](https://mattermost.atlassian.net/browse/PLT-1920) so they are more visible

**Comment by tvld** [comment]
ok, @lfbrock  was indeed the inconsistency between "Feb 23" and "14 days ago" that was missing, one only notices when new to the tool ))
