### ISSUE TITLE
App Android 1.14 flaw on Sony Xperia Z3 Compact, Android 5.1.1

### ISSUE THREAD

**Issue by githubkoma** [mattermost/platform#2422]
Except one flaw/issue the Android  App 1.14 works fine:
- It displays a "Loading" overlay Widget at first start and on reopening it
- The app is not usable for 5-10 seconds, before the Widget disappears
- Same when reopening the App after a while
- The iOS App in Comparison doesnt have this loading overlay and shows the normal elements much ealier and smoother

**Comment by it33** [comment]
Thanks @githubkoma! Can we have your help opening a separate ticket for the issue similar to [this one?](https://github.com/mattermost/platform/issues/2271)

**Comment by githubkoma** [comment]
Hi There,

of course, what do i have to do?

best regards

**Comment by it33** [comment]
Thanks @githubkoma, 

Sorry, my fault, I should have been more clear. 

Here are instructions for [reporting a bug](http://www.mattermost.org/filing-issues/). A moderator will create the other ticket after your issue is confirmed,

Thanks for your help!

**Comment by lfbrock** [comment]
Hi @githubkoma, I think this is more visible on Android because the default loading icon on Android is more obvious, iOS also has a loading screen but the default one is more subtle. 

The Android app does seem to load slower than the iOS app, and we're working on a few things we hope will improve the speed.
