### ISSUE TITLE
Question: Does mattermost have Github issues/PRs integration?

### ISSUE THREAD

**Issue by garagatyi** [mattermost/platform#2454]
Does mattermost have Github issues/PRs integration?
I haven't found such information.

**Comment by forelabs** [comment]
I don't think so, but it is not that hard to write your own because of the Incoming Webhooks.
I've written a small Github webhook handler for opening, closing and merging pull requests in php.
Message looks like this:
![image](https://cloud.githubusercontent.com/assets/3809644/13839450/6b4f47be-ec1b-11e5-9bad-1ae94e616c13.png)

The first blackened is the actor (creator of PR, active 'merging/closing person' of PR), the second is the title of the PR which also is a link to the PR and the last one is the repository.

If you are interested, I can provide you the script.

**Comment by it33** [comment]
Please see: https://github.com/softdevteam/mattermost-github-integration
