### ISSUE TITLE
How open source is MatterMost?

### ISSUE THREAD

**Issue by kramer65** [mattermost/platform#2467]
Yesterday [I asked a question](https://github.com/mattermost/platform/issues/2464) about the licensing to which a rather strange answer came.

My question was the following: In your [LICENSE.txt](https://github.com/mattermost/platform/blob/master/LICENSE.txt) I read that the source code is subject to the following:

 1. Under the Free Software Foundation’s GNU AGPL v.3.0, subject to the exceptions outlined in this policy; or
 2. Under a commercial license available from Mattermost, Inc. by contacting commercial@mattermost.com

[You answered](https://github.com/mattermost/platform/issues/2464#issuecomment-198079309) that you do not encourage ... etc. 

I'm not asking whether you encourage anything, **I'm asking if your license legally permits removing Mattermost branding to sell the software under a different name.**  If it would be an MIT(-like) license, something like this would not be a problem. But since you're talking about exceptions and commercial licenses, it is very unclear for me how "open source" mattermost really is. Please be more clear about your licensing.

(ps. Since the issue was immediately closed I open this new issue to continue the discussion. Please do not close this question immediately just to get it off your list of issues.)

**Comment by it33** [comment]
Hi @kramer65, 

Sorry, I didn't mean to be dismissive of your question, I was just following our [documented procedure](http://docs.mattermost.com/process/community-systems.html#github-issues-workflow).

You've clearly spent a significant amount of time looking at Mattermost and in asking your question, and it is 100% inappropriate to make you feel dismissed. I apologize. If you want to speak directly, I'm at it33 at mattermost.com, just mail me. 

Regarding your question on whitelabelling, it has been [discussed at length on the forums.](https://forum.mattermost.org/t/theme-ing-whitelabel-ing/1017)

Please note that [per the Mattermost product documentation GitHub issues is for bug reports and help requests from the core team](http://docs.mattermost.com/process/community-systems.html). Licensing questions should go to info@mattermost.com and general discussion should go to the forum. 

Please note that your issue was not singled out for being closed prematurely, it's just that issues that don't follow the documented procedure are closed. Here are examples from the last day of other misfiled issues that were closed: 
- https://github.com/mattermost/platform/issues/2460
- https://github.com/mattermost/platform/issues/2452

We want to be transparent and efficient about addressing community questions. We ask your help to [follow the documented procedure](http://docs.mattermost.com/process/community-systems.html) so your question gets to the right people.

Because this is not a [bug report](http://www.mattermost.org/filing-issues/) or a request from the core team for help, closing this issue so it can be continued: 
- [On the existing thread regarding whitelabeling](https://forum.mattermost.org/t/theme-ing-whitelabel-ing/1017.)
- Or asking about licensing via info@mattermost.com. Please be specific in your question whether you're planning to obscure copyright information from the Mattermost license file and from the [NOTICES.txt](https://github.com/mattermost/platform/blob/master/NOTICE.txt) file regarding the open source licenses of other software used in Mattermost. After your specific question is understood we can look at posting an FAQ.

Again, don't mean to dismiss your question, just want to get it to the right place, and if you want to talk, just mail me.

**Comment by kramer65** [comment]
I must say that from the thread you linked to, it is still very unclear to me what your policy is on white labeling (just like it is unclear to the guy named Tom in that specific thread). You seem to have an obscure list of exceptions for which you need to know every single case. On every public place you list that "Mattermost is an **open source**, self-hosted Slack-alternative. " and in various places you make hints toward the MIT license. 

First of all, the source clearly has nothing to do with the MIT license (only the compiled images), and the source itself is published under the AGPL "with exceptions", and governed by some kind of "_promise that we will not enforce the copyleft provisions_". I'm not a lawyer, but if something adheres to a license with exceptions and additional promises it seems to have little to do with the license to start with.

Since Mattermost did come out well in our intial tests I want this sorted out, so I'll continue this discussion on the forums. I do prefer to have this discussion on public forums though, instead of taking it into the obscurity of private email messaging.

**Comment by johnythompson** [comment]
So ... Still no clear, concrete answer to this, despite such a lengthy response from it33? 

This shouldn't be so opaque. Multiple different licenses while claiming "Open Source" and MIT OSS licensing is misleading. 

MM Team, please provide a clear answer and not a multitude of links that only serve to further confuse those of us seeking an answer. 

Best,
John

**Comment by johnythompson** [comment]
Anyone wanting a clear OSS alternative, check out: https://rocket.chat/ (MIT license *only*), many of the same features as MM

**Comment by it33** [comment]
Hi John, please see https://www.mattermost.org/licensing/

**Comment by kramer65** [comment]
@it33 - It is clear that you guys playing a nasty game with the MatterMost licensing. You keep totally unclear and claim to have an MIT license which simply is not true.

For all others reading this; just like @johnythompson our company also went with Rocket.Chat ([github here](https://github.com/RocketChat/Rocket.Chat)) which is actually clear about their (MIT) licensing.

@it33 - Please stop misleading people about your license.

**Comment by pcinat** [comment]
@kramer65 - I'm hold the same views as you.  Mattermost licensing is very obscure and unclear at best.  I cannot confidently answer if something as simple as White labeling is permitted.  And those links referred to in this thread claiming to discuss this issue at length are not available anymore.

Curious what you ended up doing and if you moved over to another comparable product as I'm contemplating?

**Comment by ci5er** [comment]
In an ideal world, I would be able to make commercial enhancements, using closed-source libraries, to the open source Mattermost code, and offer this "upgrade" commercially. I'd be happy to pay something substantially similar to the Enterprise licensing rates for the ability to do so, but I haven't been able to get anything except "Go talk to the Forum" whenever I ask about negotiating commercial terms with the support personnel manning the 'contact@mattermost.com' email address. 

Technically, where the code-base is is almost ideal for us to use as a fork-off point for an enhanced product for the healthcare industry (HIPAA, HL7, syndication, physician identify verification, patient identifiers, ...). But I am at a loss on how to get an answer from the company about who talk to about negotiating a commercial contract to make that possible.  The email address 'commercial@mattermost.com' goes unanswered.

I hope that something comes of this issue - because would prefer not to spend 6+ months getting to `here`, when we could almost certainly work out a license that would work to everyone's benefit.

**Comment by it33** [comment]
@pcinat if things aren't clear, that's our fault. We should fix it. Can you share specifically what you're trying to do when you say "white label"? Would you be altering or removing Mattermost copyright notices? Is this for internal use only, or would you be offering an altered version to a 3rd party? We should get a clear answer and post it officially. 

@ci5er also, sorry you didn't hear back. Please join our community server https://pre-release.mattermost.com/ you can DM me at it33 and we can discuss?

**Comment by pcinat** [comment]
@it33 - White labeling provides the option of removing or replacing the branding of Mattermost in the front-end UI that users get exposed to.  I would not be altering or removing Mattermost copyright notices embedded in the source code.  What I'm interested in is the ability to provide a slightly altered version of mattermost source code that can integrate within an existing web application by potentially removing the Mattermost logo from the UX. 

The confusing language with the license is the following (specifically clause b below):
> We promise that we will not enforce the copyleft provisions in AGPL v3.0 against you if your application:
>  (a) does not link to the Mattermost Platform directly, but exclusively uses the Mattermost Admin Tools and Configuration Files, AND
>  (b) you have not modified, added to or adapted the source code of Mattermost in a way that results in the creation of a “modified version” or “work based on” Mattermost as these terms are defined in the AGPL v3.0 license.

The language seems to suggest that you can take a copy of the source BUT cannot modify, add or adapt any part of the source code.  This really restricts what can be done and very unlike a standard MIT license.

Is anyone able to confirm?

**Comment by it33** [comment]
Thanks @pcinat, appreciate the feedback, 

First, thank you for your specific questions. They help a lot. I think after we get to your answers we'll write-up a specific FAQ on what you're trying to do. 

1) Here are our licenses and philosophy around open source licensing: https://www.mattermost.org/licensing/. If you're looking to modify the source code, instead of using the compiled Mattermost Team Edition our policies are there. High level, Mattermost is an open source alternative to proprietary messaging because of how the project started: https://www.mattermost.org/why-we-made-mattermost-an-open-source-slack-alternative/

It's designed to meet the needs of people who agree with our purpose and it won't be as useful for people who do not agree. 

2) Mattermost Team Edition is the compiled version of Mattermost under MIT license. You can go into the en.json file and change the Mattermost name and you can modify the images directory to get the logo you like. The important thing is if you're going to modify the branding you're clear what you're shipping is not Mattermost, i.e. calling it something completely different like "HealthPoint" is fine, but not "Mattermost Health Care Edition", etc. full trademark policy here: https://www.mattermost.org/trademark-standards-of-use/ 

PS: From your GitHub profile, it sounds like you're from Toronto. I'm from Toronto too, and went to Waterloo. If you'd like to discuss some time over a video call, you can join our community server https://pre-release.mattermost.com/ and DM me at it33 and [we can jump on call](https://docs.mattermost.com/deployment/webrtc.html).

**Comment by it33** [comment]
@pcinat have a new draft FAQ, let me know what you think? https://github.com/mattermost/docs/issues/1006
