### ISSUE TITLE
Hipchat Import

### ISSUE THREAD

**Issue by ylluminate** [mattermost/platform#2514]
Has anyone worked to implement Hipchat importation yet to facilitate a move from Hipchat to Mattermost with all history, users, etc?

**Comment by lfbrock** [comment]
Hi @ylluminate, no one has worked on HipChat import yet. Is that something you would be interested in working on?

If you'd like to discuss it as a feature idea, you can upvote it and add comments here: https://mattermost.uservoice.com/forums/306457-general/suggestions/8936269-add-import-from-hipchat

**Comment by herrsebi** [comment]
Hi, I think I could look into this one, could you point me towards docs to get started with importers?

**Comment by ylluminate** [comment]
@herrsebi are you still interested?  We were just sideswiped by some misinformation from the Mattermost documentation:
https://docs.mattermost.com/administration/migrating.html#migrating-from-hipchat-server-and-hipchat-data-center-to-mattermost
![text](https://cl.ly/3W2Q2v261I1I/Image%202018-07-17%20at%2012.15.35%20PM.png)

I just heard back from the `[mattermost-etl](https://github.com/Brightscout/mattermost-etl)` developers and this ONLY supports Jabber and so there's no way of importing directly Mattermost at the moment it appears...

**Comment by vcazan** [comment]
This import feature is the only thing holding us back from ditching Hipchat for Mattermost. We are definitely not going to be using Slack. Any progress on this?

**Comment by vcazan** [comment]
@ylluminate Will we be able to import private messages and files as well?

**Comment by ylluminate** [comment]
So far private messages import, but we've not spent any time on files since we use other mechanisms for sharing files.

**Comment by ylluminarious** [comment]
@ylluminate @vcazan Hey, sorry for the delayed reply. I think we are ready for a release of the gem. We have some known bugs which have not been fixed yet, but it is because we have been unable to devote the time and attention that the project needs to be in perfect working order. Hopefully releasing it to the public will help us to get the help we need.

Unfortunately, it does not handle Hipchat files yet. I want to work on this and make it happen, but sadly we just don't have all the time & resources necessary to devote to this kind of thing. But textual importing seems to work rather well, although it is rough around the edges right now. Again, we could use help in making it a smoother experience.

**Comment by jasonblais** [comment]
@ylluminarious That sounds exciting! Our team would love to help test it as well and possibly help with bug fixes and/or additional support for things like files if I can get the resources behind it.

Super exciting 👍

**Comment by ylluminarious** [comment]
@jasonblais Thanks for the encouragement! I will ping you here once we release it so watch our for that in the next few days or so. We would very much appreciate any help so thank you again!

**Comment by vcazan** [comment]
@ylluminarious Any updates on this release? We are very excited to give it a try :)

**Comment by vcazan** [comment]
@ylluminarious Thank you very much for all your hard work, I will give it a go and let you know how I do.
