### ISSUE TITLE
Show the user name/profile picture on Account Settings/Integrations

### ISSUE THREAD

**Issue by kt-ssp** [mattermost/platform#2554]
We are posting messages from several different applications to the same group and each is coming via a different user (one per application). With a user logo set, it is quick to identify which application it comes from and also doesn't look like I am posting every message. However, when viewing Account Settings/Integrations, all that can be seen when viewing the existing incoming webhooks is a list of URLs so it isn't immediately obvious which one is for which user.

Could either the user name and/or profile picture be shown next to the link.

**Comment by lfbrock** [comment]
Hi @kt-ssp, we're working on moving integrations to a separate page right now to give them more room and make them easier to view. 

We also plan on adding fields for a title and description, and who created the webhook to make them easier to tell apart. I don't think we can show the icon/username if it's overridden by an incoming webhook since that's done on the other end and not set inside Mattermost, but hopefully the other new fields will help make them easier to tell apart.

**Comment by kt-ssp** [comment]
What you mention sounds fine. The icon/username was for the person creating the webhook (in my case, incoming ones), which, from my limited time using Mattermost, has been the icon ultimately shown next to the posted message.

I look forward to the seeing and using the change.
