### ISSUE TITLE
Android app: Unable to "Switch to..."

### ISSUE THREAD

**Issue by agolden** [mattermost/platform#2613]
If I have used GitLab login for multiple teams from the mattermost web client, I correctly see an option to "Switch to [other team name]" in the main menu.  I see no way of accomplishing the same thing from the android client; you must log out of one team and then log back in on the other team.  Not sure if this is a bug or a feature request.

Edit: It appears that the 'GitLab login' is a red herring, this is an issue / feature request no matter what type of login one uses.  Title has been updated appropriately.

**Comment by Bellis-JLR** [comment]
I don't see it either, that would be a very helpful feature add.

**Comment by lfbrock** [comment]
Hi @agolden, we made a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-2528

This will need to wait until after the [user model change](https://forum.mattermost.org/t/unifying-user-accounts-across-teams-for-mattermost-2-3/1126/12) goes in (likely v2.3). Switching teams wasn't in the app previously because there were some issues getting push notifications to work properly when switching between teams, but it should be possible after the user model change.
