### ISSUE TITLE
Hardcoded town-square channel

### ISSUE THREAD

**Issue by jolks** [mattermost/platform#2676]
Across Go and React code, town-square channel is hardcoded. Maybe we can make it configuration-based so teams can easily change it and the platform can redirect correctly to `/channel/<new name>`.

However doing this, we also have to change the mobile app code e.g. [mattermost/android](https://github.com/mattermost/android/blob/master/app/src/main/java/com/mattermost/mattermost/MainActivity.java#L137) code.

**Comment by Darren66** [comment]
Second that.

**Comment by lfbrock** [comment]
Hi @jolks + @Darren66, 

Right now it's not possible to change the URL for town square to make redirects easier, since there are various times we need to redirect people back to town square. 

I created a ticket [here](https://mattermost.atlassian.net/browse/PLT-2565) in the backlog to fix it, if you want to you can also add a [feature suggestion](https://mattermost.uservoice.com) so other people can upvote it if it's important to them.

**Comment by jolks** [comment]
Thanks for your feedback @lfbrock. I have posted to the feature suggestion at [here](https://mattermost.uservoice.com/forums/306457-general/suggestions/13403289-easily-change-default-channel-town-square).

**Comment by lfbrock** [comment]
Thanks!

**Comment by megapctr** [comment]
Sorry to dig this up, do you think it would make sense to add a concept of a _default_ or a _main channel_? That way we avoid hardcoding a channel id, while still having a safe place to redirect to.

**Comment by lfbrock** [comment]
@megapctr - is there a reason you would want to have a default channel instead of just being able to change the URL for town square? 

Also feel free to [sign up for our daily builds server](https://pre-release.mattermost.com/signup_user_complete/?id=b8230f359369ed80c46ecb8696901b3e) and come join our [UX Design](https://pre-release.mattermost.com/core/channels/ux-design) channel if you'd like to discuss it more in depth.

**Comment by megapctr** [comment]
I guess that the channel url is some sort of an id. Changing an id not a good idea, as other things may depend on them (db table relations for example). Because of that, a "default channel" flag would make more sense architecture-wise.

**Comment by Philmod** [comment]
I see that we can rename the "town square" channel, but can we change the id too (in the url)?
