### ISSUE TITLE
mattermost 2.2: register a new application, but no action

### ISSUE THREAD

**Issue by ttllyy** [mattermost/platform#2725]
Developer Settings:
Applications (Preview)
register a new application, save, but no action.

What use register a developer application? 
Where there is an example and docs for register a new application?

**Comment by ttllyy** [comment]
How to use register a new third-party application?
Thanks!

**Comment by lfbrock** [comment]
Hi @ttllyy, that's an in progress feature that hasn't been fully released yet. It allows you to connect third party applications to your Mattermost account using OAuth2 instead of username and password. 

Since it hasn't been officially released, there's no docs available at the moment. They will be added in a future release.
