### ISSUE TITLE
Multiple teams on same domain

### ISSUE THREAD

**Issue by moogle19** [mattermost/platform#2777]
I have multiple teams on the same domain (e.g. mattermost.example.com/team1 and mattermost.example.com/team2) and cannot be logged in at both.
If I log in to 'team1' and then go to the site of 'team2' I see the pages for 'team1'.
I think this is because of the Cookies, which are for path '/'. I am not quite sure if you can just change the path in the cookies to the appropriate team or if this is a bigger change.

**Comment by lfbrock** [comment]
Hi @moogle19, this will be fixed in the next release when we [switch the user model so users have one account per server instead of one account per team](https://forum.mattermost.org/t/unifying-user-accounts-across-teams-for-mattermost-2-3/1126). 

However, the upgrade process for teams who currently use multiple teams on the same domain will involve more work than usual. Users who have accounts on multiple teams will need to switch to using only one account as their main account, and then re-add that account to the other teams and groups the old accounts were a part of. 

More information can be found here: https://forum.mattermost.org/t/draft-upgrade-procedure-to-mattermost-3-0-after-may-16/1392

**Comment by moogle19** [comment]
Perfect. Thanks for the info.
