### ISSUE TITLE
Why do we need ToJson() for every model ?

### ISSUE THREAD

**Issue by haseebr** [mattermost/platform#2779]
Hi There,

I'm a Golang newbie, I just want to know why do we need a ToJson() for every model ?

Instead, We could do the following that accepts a struct and outputs a json string.

I'm sure Dev's have tried something like that, why aren't we it in production though ? Is there something I'm missing ?

```
func StructToJson(s interface{}) string {
	b, err := json.Marshal(s)
	if err != nil {
		return err.Error()
	}
	return string(b)
}
```

Thanks,
Haseeb

**Comment by jwilander** [comment]
Hi @haseebr,

There's no technical reason we can't convert the structs to JSON like in your example but it is much more convenient and readable to call `user.ToJson()` rather than `model.StructToJson(user)`. That said    adding `model.StructToJson` as a utility function would be useful in places where it we want to convert non-model structs to JSON.

If you'd like to discuss it some more feel free to join us over on our [Mattermost instance](https://pre-release.mattermost.com/signup_user_complete/?id=b8230f359369ed80c46ecb8696901b3e). Please join the developer channel where stuff similar to this is discussed all the time :)
