### ISSUE TITLE
Add simple Slash Commands

### ISSUE THREAD

**Issue by mackelito** [mattermost/platform#2810]
Example...
When writing "/really?" I want this image to show https://media.giphy.com/media/gTfyyVLTicxCE/giphy.gif

**Comment by lfbrock** [comment]
Hi @mackelito, 

You can build custom slash commands yourself, we have some documentation on it here: http://docs.mattermost.com/developer/slash-commands.html

If you have more questions on how to build slash commands, you can [ask on the forums](https://forum.mattermost.org/).

**Comment by mackelito** [comment]
I have read the doc.. sorry I was not clear in my initial post...
I guess it´s just me but I cant get the image into the chat..

`
Command Trigger Word: hello
Request URL: https://media.giphy.com/media/gTfyyVLTicxCE/giphy.gif
Request Method: GET
Response Username:
Response Icon:
Autocomplete: no
Autocomplete Hint:
Autocomplete Description:
`
and when typing the command /hello it gives me "Command with a trigger of 'hello' returned response 405 Method Not Allowed"

**Comment by lfbrock** [comment]
@mackelito, I think the problem is the request URL. Slash commands and outgoing webhooks let you interact with an external application, so you would need to write an external application to return the reply  you want (https://media.giphy.com/media/gTfyyVLTicxCE/giphy.gif). Then your request URL should point to that application. 

There's an example we wrote for outgoing webhooks [here](https://github.com/mattermost/mattermost-integration-giphy), and a community member [extended this example](https://github.com/numberly/mattermost-integration-giphy) to create a slash command as well.

We're planning on adding an FAQ for webhooks and slash commands to hopefully make it more clear how integrations work.

**Comment by mackelito** [comment]
ahaaa... ok.. I kind of expected slash commands to be simpler ;)
Kind of like the slackbot.. 

eg. When a user types "lunch" we can have a custom replay like the name of a random lunch restaurant :)

Does that exists in mattermost? a similar bot? (if not I´ll add a feature request)

**Comment by lfbrock** [comment]
@mackelito no that doesn't exist, but I think that would be good to add. A feature request for it would be great, thanks :)

**Comment by mackelito** [comment]
For reference, https://mattermost.uservoice.com/forums/306457-general/suggestions/13702560-preinstalled-matter-bot
