### ISSUE TITLE
No Internet Connection Blue Bar never goes away

### ISSUE THREAD

**Issue by irfaneitw** [mattermost/platform#2992]
**Summary**
I'm always getting a blue bar telling me I have no internet connection on Mattermost Web while I'm actively browsing the internet. 

**Environment details**
- Mattermost Enterprise v2.2.0
- Chrome  v50.0.2661

**Steps to reproduce**
None? 

**Expected behavior** 
I should not see the blue bar if I have an active Internet connection

**Observed behavior** 
Blue bar shows telling me I have no Internet connection but I'm using updates in Mattermost

**Possible fixes**
Check the internet connection every 30s?

**Comment by TwizzyDizzy** [comment]
Hi @irfaneitw,

did you make sure you did set up your webserver properly so that it flawlessly handles websocket connection upgrades? That's the first that comes to my mind when it comes to "the blue bar".

You may have a look at [this forum post](http://forum.mattermost.org/t/how-to-setup-a-simple-apache2-proxy-to-mattermost/495/2) and all it's subsequent posts. Please remember: there may be differences in your setup so you better see this as an inspiration rather than an actual guideline.

Cheers
Thomas

**Comment by irfaneitw** [comment]
Hi @TwizzyDizzy,

Turns out we had to play with the websocket ports to fix the issue.

Bug is resolved!
