### ISSUE TITLE
Manage Members: Can not change Members to Inactive after upgrade from v2.2.0 to v3.0.1

### ISSUE THREAD

**Issue by ron-from-nl** [mattermost/platform#3028]
However set Member Inactive does seem to work for System Admins in the System Console User List, but Team Admins no longer can set Members Inactive, because System Console is only available for System Admins

**Comment by ron-from-nl** [comment]
![schermafdruk van 2016-05-17 18 34 07](https://cloud.githubusercontent.com/assets/19412983/15330800/abfbce54-1c5e-11e6-89dc-fa8d635cfe2a.png)

**Comment by lfbrock** [comment]
Hi @ron-from-nl, 

This was moved to the System Console in v3.0, since making an account inactive now makes it inactive across the whole server. 

We have a ticket to add the option ["Remove from team" to the Manage Members dialog](https://mattermost.atlassian.net/browse/PLT-2863), which would basically make users inactive per team.
