### ISSUE TITLE
Guide on how to compress javascript

### ISSUE THREAD

**Issue by geraldvillorente** [mattermost/platform#3306]
I already searched the doc about compressing Javascript but I didn't find anything. Please see the below screenshot. The `bundle-3.0.2.js` is a bit heavy on a slow network.

![slow_loading](https://cloud.githubusercontent.com/assets/820842/15953852/74ffb846-2f02-11e6-9acd-467bcdbbfed3.png)

**Comment by it33** [comment]
We need to break bundle.js into different files using Web Pack (https://webpack.github.io). Anyone from the community interested in helping with this? Could be a very significant resume builder, ("decreased first page load of the Mattermost open source project by 50%"). We would want this in the next release so ideally this would come in some time in the next week.

**Comment by geraldvillorente** [comment]
I would love to help but I have zero encounter with Webpack. I will explore that tool today so I can contribute on this wonderful project.

**Comment by it33** [comment]
Hi @geraldvillorente, no worries. If you're not experienced with Web Pack, we'll ask another community member to work on this, and [we have a ticket where you can track status on this](https://mattermost.atlassian.net/browse/PLT-2341). [There are many other ways you can contribute](http://docs.mattermost.com/developer/contribution-guide.html). 

Thanks for reporting this, agree this is something that should be addressed. 

Closing this issue for now since it's tracked in Jira.
