### ISSUE TITLE
RequireEmailVerification does not work

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#3365]
Hello,

On our team, we first did not have email verification enabled but I decided to enable it. However if I set `RequireEmailVerification` to true, no one can login anymore.

#### Summary
RequireEmailVerification does not work if it was disabled before.

#### Steps to reproduce
1. Set `RequireEmailVerification` to false
1. Register a new account
1. Set `RequireEmailVerification` to true
1. Login with the account

#### Expected behavior
It should login or resend a new verification email.

#### Observed behavior
It asks me to confirm my email address but if I click on the button, it fails with this error:
```
[2016/06/17 00:16:50 CEST] [EROR] /api/v3/users/resend_verification:SqlUserStore.GetByEmail code=500 rid=k5jh6tesm3gw585uykjtq6ci3h uid= ip=2a00:5881:8118:500::14 We couldn't find an existing account matching your email address for this team. This team may require an invite from the team owner to join. [details: email=rudloff, sql: no rows in result set]
```

**Comment by esethna** [comment]
Thanks for the report @Rudloff , can anyone form the community help reporoduce this issue?

**Comment by jasonblais** [comment]
Thanks @Rudloff for the report,

On which operating system and browser is the error reproducing for you? If you haven't yet, you may also try upgrading to [Mattermost v3.1](http://www.mattermost.org/mattermost-3-1-apple-watch-notification-upgrades-shortcuts-compact-view-openshift-and-more/), to see if it reproduces on the most recent release.

**Comment by Rudloff** [comment]
I am running Mattermost 3.1.0 on Ubuntu 14.04.4.
I can reproduce with Firefox 47.0 and Chromium 50.0.2661.102 on Ubuntu 16.04.

**Comment by jasonblais** [comment]
Thanks @Rudloff, very helpful. Would you be able to try re-generating the email invite salt? You can do this by clicking "Re-Generate" in **System Console** > **Security** > **Sign Up** > **Invite Salt**.

I just want to make sure there aren't any issues with the email invite salt setting.

**Comment by Rudloff** [comment]
I regenrated the salt but I still get the same error.

**Comment by MacGuinness** [comment]
Saw similar behavior here, might describe it a bit differently, however.

Originally installed 3.0.3, then created admin user to access the system (in demo mode, no configurations yet, so notifications still disabled.)

After system working, configured email and got it working.  Enabled email verifications required, and created a few new users to test -- all worked correctly.   Had system admin account logged in on one device, and other accounts from several other devices/computers.   Did not have to verify system admin account after enabling email verification.   (important?!)

Then, updated to 3.1.0.  Afterward, could not connect/log in as system admin account -- kept prompting for need to respond to verification email, IIRC.

I recall being able to log into account on one of the other devices that had saved login info from an account that had gone through the email notification...

Was able to stop service, disable email notification in config.json, restart, and then could log into system admin account.   Stopped and re-enabled, restarted and still could not start the client and log in.

At this point, I'd concluded the problem was with not allowing unverified accounts to connect, yet a basic install uses first account created as the system admin account, which has to be created at a time that no email verification has been configured yet... so the system admin account cannot be email verified.   I saw no easy way to trigger the email verification for the account, either...

What I did to fix the issue:   went into database, identified the user record and found the field used to record the verification status -- set this from '0' to '1', and then could successfully start client and log in as system admin account.

Perhaps there needs to be a startup procedure -- part of the schema update perhaps -- to force the initial user / system admin account to email verified status, so that can connect successfully after email verification enabled...

**Comment by lfbrock** [comment]
Hi @MacGuinness, after trying to log in with the System Administrator account, did you not see a page asking you to verify the email with a "Resend Email" button?

<img width="433" alt="screenshot 2016-06-27 11 14 17" src="https://cloud.githubusercontent.com/assets/9354841/16384813/6cb281c4-3c58-11e6-895b-62fa2abe5a9b.png">

**Comment by lfbrock** [comment]
@Rudloff, I think I figured out what the bug is - were you trying to log in using username? 

I think the verification email might be failing to send if you sign in with username. Can you test logging in with email to see if that works?

**Comment by happyalu** [comment]
I had the same issue. Logging in with email address works. (You still have to click the Resend button).

**Comment by Rudloff** [comment]
@lfbrock You're right, it works.

**Comment by MacGuinness** [comment]
Correct, only tried logging in with username... failed to send notify.

Frankly, didn't think to try email login when it's indicating email not
verified... :-)

**Comment by lfbrock** [comment]
Alright thanks everyone :) Will [track this bug in Jira](https://mattermost.atlassian.net/browse/PLT-3454). 

If anyone from the community would like to contribute a fix for it, please feel free as well.
