### ISSUE TITLE
Twitter styling in mattermost

### ISSUE THREAD

**Issue by MetalCar** [mattermost/platform#3406]
#### Summary
The styling of twitter messages in mattermost have a little layoutbug.

#### Steps to reproduce
Search for a tweet on twitter and post the url in a mattermost channel.

#### Expected behavior
I think, a picture can told us more than 1000 words.
The last text line below is cutted by the border.
![twitterinmattermost](https://cloud.githubusercontent.com/assets/1355298/16331146/786c75e0-39ee-11e6-9340-7378f235ba49.png)

#### Possible fixes
Add more padding to this twitter box.

**Comment by lfbrock** [comment]
Thanks @MetalCar, there's a few different issues we've run into with the current link previews which is why it's still behind a preview setting. (For example, shortened twitter links seem to trigger a blank preview right now.)

To fix the issues, we're considering removing most of the current link previews, and replacing them with the functionality described in this ticket: https://mattermost.atlassian.net/browse/PLT-1835

We could also do something similar using the meta tags for twitter. If you have any feedback on this approach, it would be great to hear it!

Also, if anyone from the community is interested in working on this, we can discuss whether it would be a good fit for a feature to accept pull requests on.

**Comment by jsg2021** [comment]
If the "height: 110" prop is omitted, the embed looks normal :}

react component with height:
![react component with height](https://cloud.githubusercontent.com/assets/577453/17564544/4c848e7e-5ef9-11e6-9036-bf8f5d6ba3d5.png)

found height-limiting element:
![found height-limiting element](https://cloud.githubusercontent.com/assets/577453/17564543/4c7c83fa-5ef9-11e6-883b-6521ad24ac18.png)

removed height:
![removed height](https://cloud.githubusercontent.com/assets/577453/17564542/4c79d7cc-5ef9-11e6-9971-91449dac0ac4.png)
