### ISSUE TITLE
Web browser freezes after sending a message which includes an ugly url in a private group

### ISSUE THREAD

**Issue by npcode** [mattermost/platform#3407]
#### Summary

Web browser freezes after sending a message which includes an ugly url in a private group.

#### Steps to reproduce

How can we reproduce the issue (what version are you using?)

Send [URL HIDDEN] in a private group.

#### Expected behavior

The message is displayed.

#### Observed behavior

Web browser freezes.

**Comment by npcode** [comment]
I think this also occurs in a public channel but I didn't try it.

**Comment by hmhealey** [comment]
Thanks for the report. We've filed aticket that you can track at https://mattermost.atlassian.net/browse/PLT-3430. Also, I've edited your post to hide the URL since it could be used to deny access to someone's Mattermost instance, but we've got a note of it internally

**Comment by hmhealey** [comment]
Closing to track on Jira

**Comment by npcode** [comment]
@hmhealey Is there a safe way two delete the message which causes this freezing?

**Comment by hmhealey** [comment]
Yes you can delete it cleanly by doing the following:
1) Go to the system console > developer settings  and check Enable Testing. Note that in upcoming the 3.2 release, you'll need to Enable Developer Mode instead because enabling testing temporarily opens up some dangerous functions that all users can access.
2) Exit the system console and go to Account Settings > Advanced > Enable Formatting to turn off post formatting. This is a debugging feature, but it will allow you to view and delete the post without your browser crashing.
3) Refresh the browser, go to the channel, and delete the post.
4) Re-enable formatting in your Account Settings and then disable Testing/Developer Mode in the System Console
