### ISSUE TITLE
Post text cause javascript failure.

### ISSUE THREAD

**Issue by niwenhao** [mattermost/platform#3467]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Post a message like next will frozen the page.

#### Steps to reproduce
Version: Mattermost Team Edition 3.1.0 3.1.0

#### Expected behavior
Post a message like next will frozen the page.

(url hidden)

and I can operate others channels.
After removing the Post record from database Anything became OK.

#### Observed behavior
There has not error.

**Comment by hmhealey** [comment]
Thanks for the report, @niwenhao. I've edited your post to hide the URL since it could be potentially used for a denial of service attack, and added it to [the Jira ticket that we have on the issue](https://mattermost.atlassian.net/browse/PLT-3430). There's a fix going in for it soon that'll be in the 3.2 release of Mattermost in a couple weeks.

Instead of having to mess about in the database directly, you can also remove the post by following the instructions [here](https://github.com/mattermost/platform/issues/3407#issuecomment-228636464).

**Comment by niwenhao** [comment]
Thanks, It is helpful.
