### ISSUE TITLE
Private conversation update is shown in all channels

### ISSUE THREAD

**Issue by prakashprabhakar** [mattermost/platform#3529]
For feature requests, please see: http://www.mattermost.org/feature-requests/.  
For troubleshooting questions, please post on the forums: http://forum.mattermost.org/.

For issues with the product, please follow the steps at http://www.mattermost.org/filing-issues/ and post here in the following format: 

#### Summary
Private conversation update is shown in all channels

#### Steps to reproduce
Ubuntu 64 Bit - 1.2.1.

1) Ask a person in a particular group to open a conversation (DM).
2) Observe the notification.

#### Expected behavior
On the client a seperate tab must be opened or it should be displayed in the team which is common between us.

#### Observed behavior
Instead the update (and notification "1") is displayed in all teams windows. Observe the pic attached.

![selection_050](https://cloud.githubusercontent.com/assets/13349934/16677271/9625cd80-44f1-11e6-950a-a69680831926.png)

**Comment by jasonblais** [comment]
Thanks @prakashprabhakar for the feedback,

I'm not sure if opening a separate tab would be the best approach: for instance, which team should be opened in that case? And should the user appear in the direct message list of other teams?  

On the other hand, if a mention indicator only appears for users that you share a team with, what would happen with users who don't share a team with you?

It's a good issue you have raised, but I'm not sure what the best approach would be in this case.

Any thoughts from other community members?

**Comment by prakashprabhakar** [comment]
@jasonblais Thanks for the update.

I changed the strategy for now. I just have one URL and teams under this space.

I will reply to your other queries shortly.

**Comment by jasonblais** [comment]
Thanks again @prakashprabhakar for the feedback.

Circling back if anyone in the community would like to offer any thoughts on the design.

**Comment by jasonblais** [comment]
Closing this issue for now -- if anyone in the community would like to share their thoughts, feel free to reopen the issue

**Comment by jfperusse-bhvr** [comment]
Here's how I think this should work. This is one of the most annoying issues for us since we're all part of multiple teams.

Suppose that:

- User A is part of teams X and Y (default team is X)
- User B is part of teams X and Z (default team is X)

What should happen:

- When user A writes to User B from team X, User B should receive the notification under team X.
- When user A writes to User B from team Y, User B should receive the notification under team X (his default team).

To me this makes a lot of sense since I can talk to another user from the team which makes the most sense for the topic.
