### ISSUE TITLE
Not responding javascript after placing non-standart text input

### ISSUE THREAD

**Issue by Kilmar** [mattermost/platform#3531]
#### Summary
Broken javascript bundle in parsing specific text input

#### Steps to reproduce
Using last stable 3.1.0 version

On any machine (tested win, linux, mac) and in any browser (tested all new version ff, chrome, safari, edge)
1. Place the url (showed at the end of this sentence) to any text message input(direct message, channel message, etc.).  URL: (URL Hidden)
#### Expected behavior
Expected is: i can see channel content and messages after pasting the new one, or in direct messages i can see history of messages and loaded content.

#### Observed behavior
After saving that problem text input (that long url) some weird javascript error occurs (static/bundle-3.1.0.js:87) with message: Script not responding

This error occurs on every page where the url was pasted. Only possible way to get rid off this issue right now is manualy delete posts from database or call the api to delete this messages.

#### Possible fixes
Possible fix of parsing text inputs ?

**Comment by hmhealey** [comment]
Thanks for the report @Kilmar. I've edited the URL out of your post since it could be used for a denial of service attack, but I've added it to an internal ticket. This has already been fixed on master and will be shipping in the 3.2 release on July 16th.

If it happens again before you update to 3.2, there's instructions [here](https://github.com/mattermost/platform/issues/3407#issuecomment-228636464) on how to delete the post without having to manipulate the database directly.
