### ISSUE TITLE
Can not display custom emoji origin size

### ISSUE THREAD

**Issue by mouson** [mattermost/platform#3624]
#### Summary
Can not display custom emoji full size

#### Steps to reproduce
1. add a new custom emoji with 128x128px
2. new message with new custom
3. new message display emoji size only 20x20px 

#### Expected behavior

1. Custom emoji origin size 128x128px will display 128x128px.

**Comment by lfbrock** [comment]
Hi @mouson - This is expected behaviour, it was designed that way so the custom emoji scale to be the same size as normal emoji. 

You can manually make them bigger in messages by using markdown headers, so for example:

<img width="291" alt="screenshot 2016-07-19 12 39 11" src="https://cloud.githubusercontent.com/assets/9354841/16958277/d061b846-4dad-11e6-9f6f-c78da8e2d2d6.png">

**Comment by lfbrock** [comment]
If you want to discuss making it a larger size, someone else opened a forum thread here on the issue: http://forum.mattermost.org/t/larger-custom-emoji-team-server-3-2-0/1910

We're open to suggestions on how this should work, but I think some people will expect all emoji to be the same size so we need to take that into consideration. Anybody who is interested in the topic, please feel free to comment on the forum thread.

**Comment by esethna** [comment]
Closing this issue to move discussion to the [forum](http://forum.mattermost.org/t/larger-custom-emoji-team-server-3-2-0/1910)
