### ISSUE TITLE
Leak goroutine

### ISSUE THREAD

**Issue by canhlinh** [mattermost/platform#3993]
#### Summary
Maybe leak goroutines. 
I see in the code https://github.com/mattermost/platform/blob/master/api/post.go#L244
`if result := <-tchan; result.Err != nil {
    return
}
`
In  function `handlePostEvents`
If has error at tchan so `cchan` and `uchan` will never be free.

#### Steps to reproduce
Every one can check number of goroutine after the function `handlePostEvents` out

#### Expected behavior
`cchan` and `uchan` will be free.

#### Observed behavior
`cchan` and `uchan` will never be free.

#### Possible fixes
Change to the below code into every `store` query.
Suppose the querry can not be slower than 3 second.
```
	storeChannel := make(StoreChannel)
	go func() {
		result := StoreResult{}
		defer func() {
			select {
			case storeChannel <- result:
				close(storeChannel)
				break
			case <-time.After(time.Second * 3):
				break
			}
		}()

....sqlquerry.....

	}()

	return storeChannel
````

**Comment by hmhealey** [comment]
Hi @canhlinh,

Thanks for the report, but luckily we aren't leaking any memory in the scenario you described. We don't leak goroutines in any of the store functions because we only pass a single object through each StoreChannel meaning they will never block. And then even though we don't read from `cchan` and `uchan`, Go's garbage collector will still free them after they go out of scope. I wrote a [short test script](https://gist.github.com/hmhealey/7e443cf07b3612089443f45c592b9461) to confirm that and as long as the garbage collector is enabled, the inaccessible channels will still be cleaned up.

**Comment by canhlinh** [comment]
@hmhealey Please explain for me why the memory still leak ?
 https://gist.github.com/canhlinh/3e8ab1468eab02b0790093ac857197af

**Comment by hmhealey** [comment]
Oh, I think I see what's going on here, and you're right about the leak. The reason your example leaks and mine doesn't is because you're using unbuffered channels (like Mattermost uses)
```
c := make(chan int)
```
 and I'm using buffered channels.
```
cs[i] = make(chan int, 10)
```
Since your channels are unbuffered, the `c <- n` call blocks waiting for another thread to read from them. If you change that line in your file to `c := make(chan int, 1)`, it stops leaking memory.

I've filed [a ticket on Jira](https://mattermost.atlassian.net/browse/PLT-4144) to fix this which we'll get in as soon as possible. Thanks!

**Comment by canhlinh** [comment]
Yep. Your solution is simpler than me. Do you have a test case for this one.

**Comment by marcosinger** [comment]
in my company we're running a self hosted MM instance and after a few days up our machine increased the CPU and memory usage.. this issue could be the culprit

**Comment by esethna** [comment]
Thanks for all the input on this. Closing this issue to be tracked in [JIRA](https://mattermost.atlassian.net/browse/PLT-4144) moving forward.
