### ISSUE TITLE
Slack import: works in one team, doesn't work in the other

### ISSUE THREAD

**Issue by arnuschky** [mattermost/platform#4126]
#### Summary

Imported a slack export in two teams, only one worked.
#### Steps to reproduce

In 0.3.4, create two teams. Then import the same slack export in both teams. 
Using chrome version 53.0.2785.116 (64-bit)
#### Expected behavior

Slack data is imported into both teams.
#### Observed behavior

Team 1: import reported a failure, but all channels, messages and users were properly imported.
Team 2: import reported success, but only empty channels were imported (no users, no messages).

**Comment by jasonblais** [comment]
@grundleborg would you have any thoughts on the reported issue?

**Comment by grundleborg** [comment]
I've also noticed that things don't work nicely if you import the same Slack export into multiple teams on a server. At first glance, this appears to be because the importer imports the users twice, bypassing the check for duplicate usernames (which I believe are assumed to be server-unique), and thus breaking things. However, I think the issues may run deeper than that - we'll have to really dig in to find out.

There is also a second issue that may be related here, which is that if you join a channel before it has finished importing, the messages will not be correctly imported. No idea on the cause of this at this stage.

These two might well explain the issue with Team 2 in the original bug report, however, they do not explain the reported failure with Team 1. @arnuschky any chance you could provide the import log for Team 1 that is produced when the import is completed?

@jasonblais I would suggest that you make PLT tickets for the two contributing issues that I have mentioned above for the problem with Team 2, and if @arnuschky can provide us with the log, or we can find a way to reproduce it, a PLT ticket for the Team 1 import failure too.

**Comment by jasonblais** [comment]
Thanks @grundleborg for the feedback - @yangchen1 please take a look when you get the chance?

**Comment by arnuschky** [comment]
Sorry had to redact the files.

First import, on team 1, reported as failed, but created channels and users: 
[MattermostImportSummary.txt](https://github.com/mattermost/platform/files/531325/MattermostImportSummary.txt)

Second import, on team 1, reported as success, but didn't create any channels or users:
[MattermostImportSummary2.txt](https://github.com/mattermost/platform/files/531324/MattermostImportSummary2.txt)
