### ISSUE TITLE
[Help Wanted] Recent mentions and flagged posts icons next to the search bar should toggle results

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4140]
We're looking for anyone interested in helping contribute this improvement.

If you're interested please comment here or come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

-----

#### Improvement: Recent mentions and flagged posts icons next to the search bar should toggle results

1) Clicking on the following icons should toggle results open and closed:

 - recent mentions icon ("@") next to search bar
 - flagged posts icon (![image](https://cloud.githubusercontent.com/assets/13119842/19018610/3e529794-8837-11e6-8e51-44aea3f6226f.png)) next to search bar

![image](https://cloud.githubusercontent.com/assets/13119842/19018617/82f0a350-8837-11e6-982f-9c7bf4f3aa62.png)

2) Using the keyboard shortcut (CTRL/CMD+SHIFT+M) should also toggle the sidebar with recent mentions open and closed

**Comment by pepf** [comment]
This looks doable, currently inspecting the related code and I came up with some questions regarding the scope.

Wondering if someone can tell me more about ```doStrangeThings()``` in [sidebar_right.jsx](https://github.com/mattermost/platform/blob/93f2b6a83302ceef5c98be4fb696840608ad3bc3/webapp/components/sidebar_right.jsx#L78) ? 
What is the purpose of this? 

Also, wouldn't the ```getFlagged()``` also need a shortcut for toggling in order to make the interaction consistent? Otherwise toggling using the mentions shortcut would also need to toggle the sidebar even if the flagged posts are shown in the sidebar?..

Finally, I assume should the current behaviour of the Close sidebar button stay the same?
<img width="131" alt="screen shot 2016-10-02 at 16 55 42" src="https://cloud.githubusercontent.com/assets/1265435/19021427/16689802-88c1-11e6-918f-abd843448b9a.png">

**Comment by jasonblais** [comment]
Sweet, thank you for your interest @pepf! 

To answer your questions:

> wouldn't the getFlagged() also need a shortcut for toggling in order to make the interaction consistent?

1) The 'flagged posts' feature doesn't have a shortcut at the moment, but we might add one in the future. If we did, the shortcut should toggle the sidebar results as you mentioned.

> Otherwise toggling using the mentions shortcut would also need to toggle the sidebar even if the flagged posts are shown in the sidebar?

2) If the sidebar is currently showing flagged posts, clicking on the "@" button or using the `CTRL+SHIFT+M` shortcut should show results for recent mentions. If the "@" button or `CTRL+SHIFT+M` are pressed for a second time, then the sidebar should close.

> Finally, I assume should the current behaviour of the Close sidebar button stay the same?

3) You're correct, the "Close Sidebar" button shouldn't change -- it should always close the sidebar

> Wondering if someone can tell me more about doStrangeThings() in sidebar_right.jsx ? What is the purpose of this?

4) @DavidLu1997 Would you be able to help @pepf with his question regarding the `doStrangeThings()` function?

-----------------

@pepf Would the above help answer your questions?

Please let us know if I can help with anything else. Thank you again for your interest :)

**Comment by pepf** [comment]
That would be enough, thanks for the info :)

**Comment by jasonblais** [comment]
Thanks @pepf for your work, highly appreciated!

Closing by #4169
