### ISSUE TITLE
[Help Wanted] Links "Terms of Service" and "Privacy Policy" on account creation page incorrect

### ISSUE THREAD

**Issue by bof-sysadmin** [mattermost/platform#4156]
#### Summary

The hyperlinks under the "Create Account" button link to /static/help/terms.html and /static/help/privacy.html instead of the URLs specified under "Legal and Support" in the System Console.
#### Steps to reproduce

OS and Mattermost version: Ubuntu 14.04.5 and Mattermost 3.4.0
#### Expected behavior

When creating an account, the links to the terms of service and privacy policy should point to the values set in the System Console, under "Legal and Support".
#### Observed behavior

The hyperlinks under the "Create Account" button link to /static/help/terms.html and /static/help/privacy.html instead. These pages don't exist which results in the message "404 page not found
".
#### Possible fixes

The faulty links can be found in [signup_email.jsx](https://github.com/mattermost/platform/blob/master/webapp/components/signup/components/signup_email.jsx#L432), [signup_ldap.jsx](https://github.com/mattermost/platform/blob/master/webapp/components/signup/components/signup_ldap.jsx#L182) and all the webapp/i18n/*.json translation files.

**Comment by jasonblais** [comment]
Great catch! Would you like to submit a PR to fix?

**Comment by jasonblais** [comment]
Adding a Hacktoberfest label, would anyone be interested in working on a fix? This would be a good first contribution that introduces you to the Mattermost code base.

Thanks again @bof-sysadmin for the initial report!

**Comment by karanjthakkar** [comment]
@jasonblais I'd love to give this a shot!

**Comment by jasonblais** [comment]
please go ahead @karanjthakkar!

**Comment by jasonblais** [comment]
Hey @karanjthakkar , thank you for working on this fix, highly appreciated!

Just wanted to give you a heads up about upcoming dates for our 3.5 release that are relevant to this issue:
 - Mon 10/31: last date community pull requests should be submitted for testing and review
 - Thur 11/3: last date when community pull requests can be merged prior to code complete Fri 11/4.

If you'd like to work on getting the fix for 3.5, those would be the dates to meet -- just wanted to let you know so it doesn't come as a surprise if you were aiming for the 3.5 release.

Once again, big thanks for your help!

**Comment by karanjthakkar** [comment]
@jasonblais Hey thanks for the update. This is really an easy fix but I'm running into issue setting up the project on my Mac because I'm unable to install Docker using the Docker for Mac setup. I'll try to find some solution this week, hopefully. If not, I guess I'll have to pass on sending in a fix.

**Comment by jasonblais** [comment]
Many thanks @karanjthakkar, much appreciated!

If you need any help setting up your environment, feel free to post a question in our Troubleshooting forums](https://forum.mattermost.org/c/general/trouble-shoot) or join our [Developers community channel](https://pre-release.mattermost.com/core/channels/developers) where you can ask from other community members and the Mattermost core team.

**Comment by jasonblais** [comment]
Hey @karanjthakkar , just checking how you're doing - let us know if we can help with the developer machine setup, would be happy to provide some tips to help you.

**Comment by cpanato** [comment]
Can I take this ticket?

**Comment by karanjthakkar** [comment]
@cpanato Sure. Go ahead. I won't be able to do this. :)

**Comment by cpanato** [comment]
cool! thanks!

**Comment by cpanato** [comment]
almost done, tomorrow I will create the PR

**Comment by cpanato** [comment]
sent the PR

**Comment by jasonblais** [comment]
Closed via #4506
