### ISSUE TITLE
[Help Wanted] URL links containing a "%" sign do not parse as clickable links

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#4322]
#### Summary
[This URL](http://www.associationmodeemploi.fr/PAR_TPL_IDENTIFIANT/25062/TPL_CODE/TPL_REVUE_ART_FICHE/PAG_TITLE/Pourquoi+les+%E9tudiants+s%27engagent+dans+les+associations/2605-fiche-article.htm) is not identified as an URL.

#### Steps to reproduce
Post a message containing this link: http://www.associationmodeemploi.fr/PAR_TPL_IDENTIFIANT/25062/TPL_CODE/TPL_REVUE_ART_FICHE/PAG_TITLE/Pourquoi+les+%E9tudiants+s%27engagent+dans+les+associations/2605-fiche-article.htm

#### Expected behavior
It is parsed as an URL and can be clicked.

#### Observed behavior
On Mattermost 3.4.0, the link is not clickable.

**Comment by jasonblais** [comment]
Thanks @Rudloff for the report, looks like it's caused by the `%` signs. Ticket created here: https://mattermost.atlassian.net/browse/PLT-4490

Would you be interested in submitting a fix?

I changed the GitHub issue to 'Help Wanted' and added the Hacktoberfest label if you're interested [participating in the event](hacktoberfest.digitalocean.com).

**Comment by Rudloff** [comment]
Yes, I will try to submit a fix for this.
