### ISSUE TITLE
Missing messages when scrolling back through history

### ISSUE THREAD

**Issue by itsmartin** [mattermost/platform#4324]
#### Summary

When you scroll to the top of visible messages, and click "Load more messages", a significant number of messages are missing between those originally displayed and the newly-loaded ones.
#### Steps to reproduce

In an active chat, scroll to the top and click "Load more messages"
#### Expected behavior

The stream of messages would be continuous.
#### Observed behavior

~3 hours worth of messages were missing.

Opening a message above the gap (via its permalink) _will_ show the missing messages.

(This was confirmed by a couple of other users in our team).

**Comment by jasonblais** [comment]
Thanks for the report @itsmartin! And very sorry for the delay in response,

Just a couple questions to help investigate the problem:
1) Which browsers (or desktop apps) has this reproduced?
2) Which Mattermost server version are you running?
3) Does the problem reproduce consistently? Is it on a particular channel?
4) Have you noticed it appearing more often after the computer has been on standby?

Any further information is helpful,

**Comment by jasonblais** [comment]
We haven't received an update so we will assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information.

**Comment by martinambrus** [comment]
This is happening for us as well. Here's answer to your questions:

1. latest Chrome
2. 3.4.0, mysql
3. it's not consistent and not on a single channel - I just tried to reload the page where this happened and history worked fine the second and third time as well as subsequent number of times after some (2 hours) of inacvitity (i.e. opening the page, not typing anything from anyone & trying the history again afterwards)
4. it appears very randomly

Also, please note that since this is a live server we use it on, it's not really possible for us to test in-dev versions there.

I guess this issue can be re-opened.

**Comment by jasonblais** [comment]
Hey @itsmartin and @martinambrus! We were later able to reproduce a case where messages might get hidden when clicking the "Load more messages" button: https://mattermost.atlassian.net/browse/PLT-5105

The issue should be resolved in Mattermost v3.7.0. Sorry for not posting back here about the resolution.

Issue details:
```
Missed messages when clicking "Load more messages" after searching a message on that channel and opening its thread in right-hand side
Repro (WIndows 10, Chrome)
1) Go to https://pre-release.mattermost.com and refresh the page
2) Search for "welcome in:town-square"
3) Scroll down the list of search results, and find a post dated earlier than December 18th. Call the post "POST-1"
4) Click the reply arrow next to POST-1, to open a thread containing POST-1 in your right-hand sidebar
5) Go to Reception (if not already there)
6) Scroll up the channel and observe the last message viewable in the channel. Call the post "POST-2"
7) Click "Load more messages"
Observed: Messages between "POST-1" and "POST-2" are not loaded in the channel.
Expected: Previous 60 messages in Reception are loaded
```

**Comment by martinambrus** [comment]
ok, thanks for the info :)

**Comment by vicp-iq** [comment]
This behavior seems to be back in the mobile app... Is this the right place to talk about that?

**Comment by jasonblais** [comment]
> This behavior seems to be back in the mobile app... Is this the right place to talk about that?

Thanks @vicp-iq! Tagging @amyblais on this report in case it's similar to another one we have

**Comment by vicp-iq** [comment]
Oh no!  I got here by searching google for "slack missing messages" and this thread was the first hit!  I didn't realize that this was the wrong place entirely!

**Comment by jasonblais** [comment]
@vicp-iq No worries! In case you're curious about Mattermost, you can find out more here :) http://mattermost.com

**Comment by vicp-iq** [comment]
Thanks, I'll take a look!

**Comment by matandd** [comment]
Hi! :)
While not _exactly_ the same, I feel like the root cause is the same.

```
Mattermost Version: 5.12.3
Database Schema Version: 5.12.0
Database: mysql
Mattermost macOS Version: 4.2.1 (4.2.1.62)
```
Message randomly disappear and appear in a way we could not reproduce.
So far we saw it happening in a private chat and a private room.
We are two people (Both on mac) experiencing the same issue, the same messages disappeared for both of us in a private chat.
The message show up when we access mattermost with Chrome (75.0.3770.142).
They would usually re-appear approximately 10 minutes later.

**Comment by jasonblais** [comment]
Hey @matandd, thanks for the report. We fixed an issue with missing messages that were occurring on 5.12.3. Would you be open to upgrading to 5.12.5, or the latest version 5.13.2? https://docs.mattermost.com/administration/changelog.html

**Comment by matandd** [comment]
Thank you, I will give it a test!
