### ISSUE TITLE
[Help Wanted] Display a message when post is over 4000 characters

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#4356]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

---

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-4318))

**Repro**:
Copy paste a text that's over 4000 characters into the message box.

**Observed**:
Message is truncated at 4000 characters.

**Expected**:
Message should not be truncated. Alert message and character account appears (see image - message should be same grey as formatting help text), and prevents user from sending the message. 
If user attempts to send message, a yellow highlight appears around the alert message, then fades out in .75 seconds (see 2nd picture). 

![image](https://cloud.githubusercontent.com/assets/13119842/20678146/aa279d8a-b563-11e6-8ad1-1a4f84f59470.png)

![image](https://cloud.githubusercontent.com/assets/13119842/20678153/b1c5285a-b563-11e6-9734-7746321a1551.png)

**Comment by fraziern** [comment]
Taking a look at this. One initial question - how should the alert display on mobile/tablet widths?

**Comment by fraziern** [comment]
So there is an existing alert message with a slightly different positioning. Setting aside the functionality/text and looking solely at placement, is this positioning acceptable or should it really be more aligned with the ` **bold** _italic_ ...` text?

![screenshot 2016-11-28 07 02 38](https://cloud.githubusercontent.com/assets/963391/20667706/aadeaea6-b538-11e6-8f17-2de497336223.png)

(Position's a little cozier in narrow widths):

![screenshot 2016-11-28 06 58 09](https://cloud.githubusercontent.com/assets/963391/20667838/6e8c367a-b539-11e6-8d20-4300ef018f9a.png)


If that works I will reuse the existing positioning - which would be easier since it's part of the same component that houses the message submission logic.

**Comment by yangchen1** [comment]
Hey @fraziern, thanks for your interest! Having it replace the help text in smaller widths similar to the 2nd picture is fine. :) Also as an FYI I updated the actual error message so that it doesn't have an exclamation mark.

**Comment by jasonblais** [comment]
Closed via #4687, thanks @fraziern!
