### ISSUE TITLE
Custom emoji naming is case-insensitive while emoji picker is case-sensitive

### ISSUE THREAD

**Issue by timrsmith** [mattermost/platform#4539]
#### Summary
Emoji picker is case-sensitive (e.g. :rainbow: works, while :Rainbow: doesn't), which is probably good/expected. However, custom emoji unique name validation is case-insensitive. 

#### Steps to reproduce
1. Create a custom emoji, all lower (e.g. :foo:)
2. Try to use it with a character upper cased (e.g. :Foo:)
3. Try to create an upper-case variant of the emoji

#### Expected behavior
If emoji picker is case-sensitive, then custom emoji naming should be too. We notice there are some upper/lower variants of standard emoji (e.g. :D: and :d:). We'd like to replicate this with custom emoji.

#### Observed behavior
We have a custom thumbs-up emoji :y:
<img width="209" alt="screen shot 2016-11-11 at 11 01 26 am" src="https://cloud.githubusercontent.com/assets/1857984/20226835/952cef74-a7fe-11e6-979e-5b858d55a7fb.png">

when matching case, picker works fine
<img width="182" alt="screen shot 2016-11-11 at 11 05 48 am" src="https://cloud.githubusercontent.com/assets/1857984/20226918/f67d3bc6-a7fe-11e6-9d6c-6cef647b0a50.png">

When case isn't matched, doesn't
<img width="63" alt="screen shot 2016-11-11 at 11 06 17 am" src="https://cloud.githubusercontent.com/assets/1857984/20226935/02210e62-a7ff-11e6-9ef0-34d919d01b9d.png">

But when we try to create an upper-case variant, it isn't possible:
<img width="657" alt="screen shot 2016-11-11 at 11 01 10 am" src="https://cloud.githubusercontent.com/assets/1857984/20226963/1df98d9e-a7ff-11e6-8def-2a0a246054ca.png">

#### Possible fixes
Make custom emoji unique name validation case-sensitive.

**Comment by jasonblais** [comment]
Thanks @timrsmith for the report,

We made custom emoji naming case insensitive so you don't have different custom emoji for :dancing:, :Dancing:, :DANCING: and so forth. Otherwise that could get confusing fast.

That being said, the emoji autocomplete should also be case insensitive. That is, after creating a custom emoji for `:y:`, typing either `:Y` or `:y` in the message box should show the newly created emoji.  I've created a ticket for it here: https://mattermost.atlassian.net/browse/PLT-4789

If anyone is interested contributing a fix for it, please let us know!
