### ISSUE TITLE
Incoming messages not received after connecting to a VPN unless refreshing

### ISSUE THREAD

**Issue by daramousk** [mattermost/platform#4669]
#### Summary
Issue in one concise sentence
Messages not getting received when I connect to a VPN

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Connect to a VPN on Ubuntu 16.04, if messages are sent on Mattermost you will not be able to receive them. If you click refresh though you will be able to receive them normally and the functionality gets restored.

This issue occures when using the browser and the native application

Edit: This happens on my ubuntu 16.04

**Comment by jasonblais** [comment]
I'm really sorry about the delay here.

We typically direct users to post these types of issues in [Troubleshooting forums](https://forum.mattermost.org/c/general/trouble-shoot), just because there tends to be more activity compared to GitHub. 

Given the long response time, I've posted a question to the forums myself and called on the community to help. If there hasn't been a response in a couple of days, I'll ping someone on our team to get this resolved for you.

Here's the forum post: https://forum.mattermost.org/t/incoming-messages-not-received-after-connecting-to-a-vpn-unless-refreshing/2638
