### ISSUE TITLE
White bar

### ISSUE THREAD

**Issue by S6066** [mattermost/platform#4691]
There's a white bar, and I can't see "XXX is typing" (same without the white bar)
http://i.imgur.com/npg5ip8.png
MM Entreprise 3.5.1, I don't know how to reproduce the bug

**Comment by jasonblais** [comment]
Hey @S6066, thanks for the report - do you see it consistently, or does it happen rendomly? 

Which operating system and browser does this reproduce, if applicable?

Is it if you shrink the window on desktop, or do you see it on your mobile device?

**Comment by S6066** [comment]
It's random  
I use Windows 10 x64 and MM app  
It's on desktop, resizing the window or something does nothing  
But when I don't have this bug, I don't have the "Help" button too

**Comment by S6066** [comment]
The white bar bug occurs when the window is not maximized, shrinking or growing does nothing but maximizing it made the bar black again.  
Minimizing it after that just hid the bar and the "Help" button

**Comment by jasonblais** [comment]
I filed a bug ticket that I found, wondering if you're seeing something similar? https://mattermost.atlassian.net/browse/PLT-4971

I'm not 100% sure if it's related, but I suspect the issue is that the "Help" button is misplaced, causing a white bar at the bottom. If so, this ticket should hopefully fix the issue.

**Comment by S6066** [comment]
I don't think it's related.  
And is it normal that if window is not maximized I don't see the help button & "XXX is typing" bar, but when window is maximized I don't see the send image button ?

**Comment by jasonblais** [comment]
Yeah, we support three different views for the web app: 
 - **mobile view**, which is shown if the Mattermost window is shrinked to a size similar to mobile. Here we hide the "help" button and "XXX is typing" to match the user experience on mobile apps
 - **tablet view**,  which is shown if the Mattermost window is shrinked to a size similar to a tablet (e.g. iPad)
 - **desktop view**, which is matching the experience in full screen mode (or anything bigger than a tablet). Here we don't show the "send" button given users typically use the Enter key to send a message

I'm wondering if you'd be interested joining our [demo community instance of Mattermost](https://pre-release.mattermost.com/core/channels/tickets) and see if the issue is resolved there? We submitted a related fix that might solve your issue.

**Comment by S6066** [comment]
I was in the tablet view then.  
Okay for the demo, but do I have to enter my username & password or should I create an account ?

**Comment by S6066** [comment]
Oh, I know how to reproduce the bug !  
It's in tablet mode of course, and it occurs when you answers to a message

**Comment by jasonblais** [comment]
Thanks @S6066! You can create an account by clicking "Create one now" [on the sign in page](https://pre-release.mattermost.com/login)

![image](https://cloud.githubusercontent.com/assets/13119842/21269410/a2f5e7f8-c380-11e6-8c27-79babb8e347c.png)

Thanks also for the updated repro steps! I tried and I suspect it was fixed by a recent PR that addressed a related issue.

Would be good if you had time to test it too, just so that we'd be able to confirm it's fixed and will appear on the next Mattermost release on January 16th

**Comment by S6066** [comment]
Tested, and I don't have the bug in tablet mode or desktop mode.
