### ISSUE TITLE
Document return values of golang api 

### ISSUE THREAD

**Issue by XANi** [mattermost/platform#4723]
Trying to write anything more advanced is exercise in frustration, most commands require digging in source code just to guess what output they return [for example](https://godoc.org/github.com/mattermost/platform/model#Client.GetProfilesInChannel) have no ducumentation saying that it returns `map[string]*User`, and that is pretty much same with every function. 

Also is there a reason why every response is wrapped in `*Result.Data` interface and need to be cast every time to be used ?

**Comment by jwilander** [comment]
Hi @XANi,

The reason for using the `*Result` interface was so that we could supply some extra information, such as the etag, with the response. That was a legacy decision that we've now realized isn't as useful as we thought it would be. We now have a policy for new additions to have at least some documentation and to return the proper models rather than a `*Result`. For example, [ListEmoji()](https://github.com/mattermost/platform/blob/master/model/client.go#L2074) uses the new method.

I've also queued this for discussion during our public developer meeting tomorrow if you would like to attend to give your thoughts. If so, you can [join our Mattermost instance](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) and find a link to [the meeting here](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676).

We'd also love help improving the documentation and moving old methods to return the models directly if you'd be interested in contributing

**Comment by XANi** [comment]
> We'd also love help improving the documentation and moving old methods to return the models directly if you'd be interested in contributing

Is there any concrete plans for that migration ? Because just changing return value would basically break any and all software written with it. I don't really mind contributing and then fixing our bots (we have some extra inhouse LDAP integration on top of MM enterprise) but I'd imagine a lot of people would get annoyed if their bots break every time there is new version released

**Comment by jwilander** [comment]
We talked about it during our developer meeting and decided that we're going to make the effort to do it with our next API version. The [still-in-progress specification](https://docs.google.com/document/d/197JwEBMnK8okFilTfGSpbsrXPY5RZOJ4gG2DXwcbwYE/edit#) for API version 4 indicates how we'll handle versioning in the future. We welcome any feedback on the spec as well

As for the current APIv3, moving forward we will not remove any existing APIs or modify existing driver functions unless there is a critical reason for doing so (security or server-breaking issue). New driver functions will use the new method.

**Comment by jasonblais** [comment]
Thank you @XANi for starting a discussion on this topic.

We welcome you to continue it in our [Mattermost developers community channel](https://pre-release.mattermost.com/core/channels/developers) and leave feedback on the [in-progress specification for API version 4](https://docs.google.com/document/d/197JwEBMnK8okFilTfGSpbsrXPY5RZOJ4gG2DXwcbwYE/edit#) linked above. We hope to work with the community as we finalize it.

Given this is an extended discussion rather than a product defect, I'll close this issue for now, and continue it in the Developers channel instead.
