### ISSUE TITLE
Ability to set default notification preferences for new user

### ISSUE THREAD

**Issue by XANi** [mattermost/platform#4729]
We're hitting a problem where new users that log in first time to the service (we have LDAP-backed corporate instance so everyone's email account is company's one) complain about spamminess of default notifications.

Current defaults (notice for all activity, send email immediately) are VERY spammy with busy chats and there is no way to change it so every user needs to be trained on where to click to turn it off.

**Comment by esethna** [comment]
Totally makes sense, I would suggest that you please submit the idea to our [feature idea forum](https://www.mattermost.org/feature-requests/) where users can up vote and discuss. Internally we have been discussing the idea of team defaults for themes and other account settings, I think notifications makes sense too.

**Comment by MexHigh** [comment]
Is there any progress with this issue? I've been running Mattermost as a simple chat- and filetransfer server for quite a while now but nobody is using it because they don't have to reconfigure default notification settings in Telegram to not get spammed, so we're stuck with it, because people are lazy.
