### ISSUE TITLE
curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused

### ISSUE THREAD

**Issue by anismilali** [mattermost/platform#4833]
curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused
curl: (7) Failed to connect to 127.0.0.1 port 8065: Connection refused

**Comment by lfbrock** [comment]
Hi @anismilali - can you give more details about your issue? 

If it's a problem getting Mattermost to run, can you post on the [troubleshooting forums](https://forum.mattermost.org/)?

**Comment by jasonblais** [comment]
We haven't received an update so we will assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If it's a problem getting Mattermost to run, please post on the [Mattermost troubleshooting forum](https://forum.mattermost.org/)?

**Comment by ferdaws9** [comment]
curl -v 127.0.0.1
* Rebuilt URL to: 127.0.0.1/
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 80 failed: Connexion refusée
* Failed to connect to 127.0.0.1 port 80: Connexion refusée
* Closing connection 0
curl: (7) Failed to connect to 127.0.0.1 port 80: Connexion refusée
