### ISSUE TITLE
[MM 3.6 RC2] Emoji autocompletion starting after two characters.

### ISSUE THREAD

**Issue by DrLynix** [mattermost/platform#5015]
Caused by https://github.com/mattermost/platform/pull/4895, I don't think it's a desirable behavior (it has been quite boring since we upgraded), I think `:P` should be part of the auto-completion list, with it starting to show after one character.

**Comment by jasonblais** [comment]
Thanks @DrLynix, really appreciate the feedback:

If we included `:p` in emoji autocomplete list, then the side effect would be that the user would have to press twice in order to post a `:p` message:

1) Type `:p`
2) Hit enter to select the emoji [not really necessary]
3) Hit enter to choose the emoji

What would be your thoughts on that use case?

Also, I'm wondering  -- if the user wants to write `:p` within a message, there wouldn't really be a need for an autocomplete. The autocomplete is there to help users to choose an emoji without fully writing them out.

**Comment by DrLynix** [comment]
I didn't think of that, you are right, my bad.

It's better this way then (and reflects Slack usage).
