### ISSUE TITLE
Custom 128x128 emojis are wrongly scaled with the new update.

### ISSUE THREAD

**Issue by patoupatou** [mattermost/platform#5099]
#### Summary
Emojis are wrongly scaled with the new update.

#### Steps to reproduce
Use a 128x128 emoji

#### Expected behavior
The emoji fits inside a square

#### Observed behavior
The emoji is wrongly resized and is more "squashed" horizontally. For instance, if you type :emoji: and someone +:emoji: this comment, the two images used are not scaling the same way, the image inside the "reaction" will be correct, whereas the one inside the post is wrongly horizontally.

See http://i.imgur.com/HzfTn2x.png

Also it seems it only affects all the custom emojis, even though they were resized to EXACTLY 128x128 before uploading them to the server. Also some custom emojis which were 64x64 are unaffected by this. I can provide sample gimp files of custom emojis if needed.

Thanks and keep up the good work.

**Comment by patoupatou** [comment]
After tinkering with it for a while, I think it might actually be fine now the way it is, however, this new update introduced something new. For instance, before the update, a 128x96 emoji would not be scaled because the 128 pixel limit was already reached. Now with this update the horizontal portion of the emoji is scaled to 128 whereas it stays the same vertically. 

I think if an icon needs be scaled, it should keep the same proportions or else it looks very weird.

**Comment by lfbrock** [comment]
Hi @patoupatou thanks for the report, I think I can reproduce the issue, let me know if this describes the issue properly: 

1. Create a non-square custom emoji
Observed: The emoji thumbnail does not maintain the aspect ratio on the set up page
<img width="450" alt="screenshot 2017-01-23 16 57 07" src="https://cloud.githubusercontent.com/assets/9354841/22224581/256f0dd4-e18d-11e6-9da0-52ff177eeb44.png">

2. Post the emoji in a channel
Observed: The emoji is correctly scaled (this is the expected behaviour)
3. Add an emoji reaction to the post
Observed: The emoji reaction does not maintain aspect ratio 
<img width="119" alt="screenshot 2017-01-23 16 57 38" src="https://cloud.githubusercontent.com/assets/9354841/22224595/2c212a68-e18d-11e6-8d8c-900e7c78e097.png">

**Comment by jasonblais** [comment]
Hey @patoupatou, we created a Jira ticket for us to track the issue: https://mattermost.atlassian.net/browse/PLT-5358

Let us know if anyone is interested helping with a fix?

Also, @patoupatou, if the issue doesn't describe your scenario, please let us know.

**Comment by patoupatou** [comment]
Thanks! I think the issue correctly describes my problem, except for me I noticed it with the emoji instead of the reaction (the reaction "appeared" to be fine whereas the emoji was wrongly scaled). I think this has to do with either the height or width that is longer than the other.

This can probably be fixed with css but I'm not much of a web dev so I'm not sure where to fix it. I'll be following the bug on jira :)
