### ISSUE TITLE
Change of 3.6 /execute request format undocumented

### ISSUE THREAD

**Issue by jtdaugherty** [mattermost/platform#5281]
#### Summary
Apparently 3.6.0 changed request parsers, making the `execute` endpoint field requirements change (e.g. from `channelId` to `channel_id`) and this change is undocumented and causing 500 responses to outdated clients.

Specifically, 3.5.0:
https://github.com/mattermost/platform/blob/3f19ccf1b1a6efdcc990cf8a0270ec4ffc0c6e22/api/command.go#L92
and 3.6.0:
https://github.com/mattermost/platform/blob/master/model/command_args.go#L12

The changelog does not mention a change of parser that caused this behavioral change and it does not mention that the field naming convention changed. The error message in response *also* doesn't mention the specific cause:
```
An error while saving the command response to the channel
```
As a result this was very difficult to track down.

CC @aisamanra @dagit

**Comment by jasonblais** [comment]
Thanks @jtdaugherty for the report!

Would you have a suggestion for what error message would be more useful? Would be happy to update or accept a pull request for it.

I'll also bring this up to the team and discuss the best way to communicate request parser changes (maybe under "compatibility" changes in the changelog)

**Comment by jtdaugherty** [comment]
I think something like this would be the most useful:
```
Request missing required field "channel_id"
```

**Comment by jasonblais** [comment]
Hey @jtdaugherty , sorry for the delay in replying, much of our team was on the road last week.

This was a one-time change and we don't expect to change request parsers. Hence, you shouldn't expect to have the request missing a field in the future.

Really sorry for the inconvenience that it caused, and thank you for reporting it to us.

**Comment by jasonblais** [comment]
I also added the change to our 3.6 changelog here: https://github.com/mattermost/docs/commit/0e4edf408e120e4b56df90d93ba72db45f818b5c

I tried submitting a pull request that updates the error message to `Request missing required field "channel_id"`, but then realized the change is a little more involved. I think the current error message  `An error while saving the command response to the channel`  captures other errors where the missing `channel_id` field is simply one of them. 

Not sure if you'd be interested / had time to submit an update for the error message?

**Comment by jtdaugherty** [comment]
I have no doubt that changing the error-reporting to provide more granular messages would be somewhat involved. While the current error message may in fact capture a number of different conditions, it is really not very useful when trying to diagnose a problem because it provides no guidance on what should be changed to send a proper request. (And from glancing at the code, it appears that some errors are recoverable by the user submitting the request, whereas others are not - and it makes a difference to know which kind of error it is!)

I don't have time to submit a patch for this. On a more general note, if I thought this kind of request fell under the "nice to have" heading, then I think getting community contributors to help with it would be totally appropriate. But I think fixing this is the responsibility of the core maintainers.

Thanks!

**Comment by jasonblais** [comment]
Thanks @jtdaugherty for the feedback,

As you know, we're in the process of moving to APIv4 which will have updated status codes ([see spec for more details](https://docs.google.com/document/d/197JwEBMnK8okFilTfGSpbsrXPY5RZOJ4gG2DXwcbwYE/edit#heading=h.9wfmvlte5ycz)).

Quoting from the developer:
> the goal is to only return 500 when there is an actual server error (DB hit gone wrong, bad pointer, etc.) and to always use 400 when it's due to a bad request.

Although not the complete solution, it should help us move in the right direction.

Any thoughts / feedback?

**Comment by jtdaugherty** [comment]
@jasonblais while I'm glad to hear that 500 responses will be used differently going forward, the problem I reported here was just that the response didn't contain enough information for me to diagnose the problem with my request. I only mentioned the 500 response to describe the observed behavior.

**Comment by aisamanra** [comment]
I should jump in here and remark that the lack of a relevant error in the response looks like it was associated with another bug which appears to have since been fixed: namely, the error-handling for invalid commands would swallow specific errors in favor of a generic "save" error: this can be observed in version 3.6.1 (and presumably in newer versions; I just looked for this in a random older version) and appears to be associated with [this snippet of code](https://github.com/mattermost/platform/blob/0d8bb03b5773923cf52f4d8cb2711131caae105c/api/post.go#L227-L229):

```
if _, err := CreatePost(c, post, true); err != nil {
	c.Err = model.NewLocAppError("command", "api.command.execute_command.save.app_error", nil, "")
}
```

If the `CreatePost` function fails with an error, then that error would get thrown away in favor of a less informative catch-all error. This looks like it's [no longer the case in HEAD](https://github.com/mattermost/platform/blob/master/app/command.go#L20) where the relevant line now reads:

```
return CreatePost(post, teamId, true)
```

which returns the same error variable directly from `CreatePost`.

**Comment by jasonblais** [comment]
Hey @jtdaugherty and @aisamanra 

Have chatted with one of our developers and here's our plan.

Created a ticket for us to [improve error reporting of the execute endpoint (for APIv4)](https://mattermost.atlassian.net/browse/PLT-5673):

1) Make the error messages clearer to identify what's causing it
2) Return errors when there's an error instead of an ephemeral message
3) Have the client do the conversion from error to ephemeral message

We'll start with the execute endpoint and continue with others afterwards as necessary.

Let me know how that sounds?

**Comment by jasonblais** [comment]
Thanks again @jtdaugherty and @aisamanra -- I'll close this ticket and we'll track it in Jira: https://mattermost.atlassian.net/browse/PLT-5673

**Comment by jtdaugherty** [comment]
@jasonblais that sounds good to me; thank you!
