### ISSUE TITLE
can't search for a literal .

### ISSUE THREAD

**Issue by activedecay** [mattermost/platform#5317]
#### Summary
can't search for a literal .

#### Steps to reproduce
1. type a message like `db.json`
1. type in the search box `db.json`

observed that there are no results. this is an error because i expect results.

there are no known workarounds
1. wrapping in quotes did not help, as `"db.json"` also gave no search results
1. found that while searching for words without the literal dot '.' character, the search works fine. it's only when i want to search for a dot that I run into trouble
1. I tried `db\.json` `db\\.json` `"db\.json"` `"db\\.json"` and still no search results

Build Hash: aafb8be87c79c60df7534b3b69f967c6301b157e
EE Build Hash: 0cce9c15a3a5411cca6ca90164e94a666bd4b94a

**Comment by lfbrock** [comment]
Hi @activedecay - what database are you using? 

We're currently using full text search, so depending on the database you're using and the minimum word length I think it's not finding the term because it's breaking the word up into "db" and "json", and searching for two letter terms doesn't work. 

We have a note here about [2 letter search with MySQL](https://docs.mattermost.com/install/requirements.html?highlight=cjk%20search#database-software), and are looking at what we could do to make search better in the future.

**Comment by activedecay** [comment]
I just did docker-compose up, so I took the defaults. Thank you I'll provide more info when I get a chance

**Comment by activedecay** [comment]
actually, i ran into this issue when searching for longer words separated by dot characters, as in `john.smith`

    john.smitheleyer@companycompany.example.com

**Comment by lfbrock** [comment]
Hmm interesting, that's a weird one. 

I filed a ticket here on it, it seems to be something with the postgres full text search but I'm not sure what's causing it: https://mattermost.atlassian.net/browse/PLT-5471

For full text search tickets, I just started [an epic](https://mattermost.atlassian.net/browse/PLT-5472) and we'll add related tickets there to track them - I think we'll need to look at them as a group, and then decide what the best approach is for fixing some of these issues.

**Comment by lfbrock** [comment]
Closing this + will track in Jira
