### ISSUE TITLE
Slack migration not working

### ISSUE THREAD

**Issue by twalk6** [mattermost/platform#5352]
#### Summary
The migration of posts from Slack is not working

#### Steps to reproduce
Mattermost 3.6.1
To Reproduce:
I created a new Slack team, just a single user. I added some text, file/image attachments, etc. I then did the Slack export. I then ran the Slack Advanced Exporter on the output. After that, I tried both the platform command and client webui command for import. I had to add an email field to users.json. It created channels, but wasn't happy if the channels already existed. No posts or attachments ever got inserted. The Posts DB table is missing the posts in question

#### Expected behavior
Slack data migration to MM

#### Observed behavior
Posts and attachments were not inserted into the DB

#### Possible fixes
I haven't looked at the code, but it's my guess that Slack made a small change to their output

**Comment by jasonblais** [comment]
Thanks @twalk6 for providing the Slack output file on https://pre-releast.mattermost.com/core.

We'll investigate the issue further on Monday

**Comment by jasonblais** [comment]
@twalk6 Jira ticket created here to track: https://mattermost.atlassian.net/browse/PLT-5479

If anyone is interested submitting a fix, please let us know?

Issue details: We assume that all users in the Slack export will have an email address set, but in reality they don't always. We will need to find a way to work around this, since Mattermost currently enforces all users to have a valid (non-empty) email address set.
