### ISSUE TITLE
Publish versioned docker images for MatterMost releases

### ISSUE THREAD

**Issue by jtdaugherty** [mattermost/platform#5818]
As far as I know, the `mattermost-preview` Docker image is the only published image that I can get without building my own production images from scratch. Since `mattermost-preview` is a moving target, it's not very useful for automated testing purposes since changes in the upstream image will break my test suite. As a result I'd *really* love it if I could get access to versioned Docker images for MatterMost for each public release, e.g., `mattermost-3.6.3` or `mattermost-3.7.1`, that are as easy to use as `mattermost-preview` is now.

Do those already exist? If so, where can I find them? If not, can they be made available going forward?

CC @aisamanra @dagit

**Comment by xcompass** [comment]
@jtdaugherty we have production ready image: https://hub.docker.com/r/mattermost/mattermost-prod-app/. This is the source: https://github.com/mattermost/mattermost-docker

Let me know if you have any question.

**Comment by lindy65** [comment]
Hi @jtdaugherty 

Just circling back to see whether you've managed to resolve your issue?

**Comment by jtdaugherty** [comment]
@xcompass and @lindy65 - thanks for the update. Not being a docker user, it isn't clear to me whether I need to use `docker-compose` to make the production image. What I'd like, ideally, is a docker image similar to `mattermost-preview` that can be used without any other steps such as `docker-compose`. Is that possible?

**Comment by lindy65** [comment]
Hi @jtdaugherty, thanks for your question...  @xcompass is the expert on Docker so I'll defer to him to respond...

**Comment by xcompass** [comment]
@jtdaugherty Because the prod images are built for production use, all the components (app, db, etc.) are in separate images so that you can deploy them on separate hosts and maybe cluster the app node as well. You don't have to use docker-compose for the production image. It is just a way to make things easier. Because you can bring up everything in one command `docker-compose up`. You also can run the pre-build prod image by using `docker run` similar to the preview image. Please see the options inside `docker-compose.yaml`. Let me know if you have any question.

**Comment by lindy65** [comment]
Hi @jtdaugherty,

Circling back to find out whether `xcompass` message above has helped solve your issue?

**Comment by jtdaugherty** [comment]
@lindy65 - I don't think so. What I think I've hard at this point is that what I want is *possible*, but I still don't know how to do it. I'll break down the response bit by bit:

> Because the prod images are built for production use, all the components (app, db, etc.) are in separate images so that you can deploy them on separate hosts and maybe cluster the app node as well. You don't have to use docker-compose for the production image. It is just a way to make things easier.

That makes sense, and it'd be okay with me if I had to run multiple docker instances on the same host just to get a working system running for testing purposes.

> You also can run the pre-build prod image by using docker run similar to the preview image. Please see the options inside docker-compose.yaml.

I don't know where `docker-compose.yaml` is located, but even if I did, I'm not sure it would help yet; right now what would help me most is one or more commands that I can run to run a specific version of MatterMost within Docker for testing purposes. I initially opened this issue because I couldn't find out whether this was even possible using public MatterMost documentation.

The closer such a procedure is to the procedure for running the `mattermost-preview` image, the better it will work for me. The less I have to learn about Docker, and the less I have to depend on moving parts and setup, the better it will work for me. The result that I need is to be able to run my test suite against a known version of MatterMost in a way that is repeatable and stable.

An additional result that I think would be helpful is to have whatever steps you recommend for this be added to the public documentation that already talks about running `mattermost-preview`.

**Comment by lindy65** [comment]
Thanks for your detailed response @jtdaugherty!

I'm sure @xcompass will be able to respond / assist with some answers for you!

**Comment by xcompass** [comment]
> That makes sense, and it'd be okay with me if I had to run multiple docker instances on the same host just to get a working system running for testing purposes.

In this case, you may want to try `docker-compose up -d` after you clone this repo: https://github.com/mattermost/mattermost-docker. The detailed instructions are in readme.md.
Docker-compose will spin up multiple containers for the whole mattermost system. If you want different versions, you can checkout different tags, which are listed here: https://github.com/mattermost/mattermost-docker/tags

> The closer such a procedure is to the procedure for running the mattermost-preview image, the better it will work for me. The less I have to learn about Docker, and the less I have to depend on moving parts and setup, the better it will work for me. The result that I need is to be able to run my test suite against a known version of MatterMost in a way that is repeatable and stable.

Because the way mattermost production images are built is different than preview image (as I mentioned above, they are broken into different containers), you can't simply run one `docker run` command to spin up the whole system. Though you can still use `docker run`, but it will be three different commands, one for each container. That's why I was suggesting to use `docker-compose`, which is a tool for defining and running multi-container Docker applications. If you would like to use docker container to deploy your production instance, I would suggest you to learn some basics about docker/docker-compose, because: 1. they are very simple to learn, 2. it will help you in the future for managing your application and troubleshooting. If you really want to avoid learning docker, you can still deploy mattermost from binary on a traditional server. Through you need to manage other components (db, proxy) yourself.

> An additional result that I think would be helpful is to have whatever steps you recommend for this be added to the public documentation that already talks about running mattermost-preview.

Actually all the deployment options and instructions are here: https://docs.mattermost.com/guides/administrator.html#installing-mattermost

Let me know if you have further questions.

**Comment by lindy65** [comment]
Thanks @xcompass!

@jtdaugherty, have you managed to resolve your issue with xcompass' help above?

**Comment by lindy65** [comment]
Closing this issue off for now.  Please feel free to reopen if you are still experiencing issues @jtdaugherty
