### ISSUE TITLE
[Help Wanted] Clicking on @mention of a user in a post should show the profile popover.

### ISSUE THREAD

**Issue by jasonblais** [mattermost/platform#5915]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Details** ([Jira ticket](https://mattermost.atlassian.net/browse/PLT-1031))

Clicking on @mention of a user in a post should show the profile popover.

Repro:
1) Post a message `hey @username`
2) Click on the mention, `@username`

Observed: Currently clicking on an @mention searches for the user's name.

Proposed change: Clicking on an @mention opens the "profile popover". (This should be the same popover that shows up when clicking on a person's name beside their profile picture in the center channel - see screenshot for an example).

![image](https://cloud.githubusercontent.com/assets/13119842/20106443/2891d13e-a5a3-11e6-967f-45fd6e789460.png)

**Comment by saturninoabril** [comment]
@jasonblais i'd like to work on this one if available. thanks

**Comment by jasonblais** [comment]
That would be awesome @saturninoabril! Thank you 👍

**Comment by saturninoabril** [comment]
@jasonblais just to let you know that i'm looking into this and had several attempts to work it out but I found limitations due to html composition used in `post_view_message.jsx` where formatted message is being passed as `dangerouslySetInnerHTML={{__html: TextFormatting.formatText(this.props.post.message, options)}}`.
I'm currently testing out one solution right now where I'm able to reuse/implement user_popover but it introduced other third party library ([html-to-react](https://github.com/aknuds1/html-to-react)).
Before I proceed with further testing using this library and subsequently issue a PR, please let me know if you're open in adding this library and if its license is permissive enough/in line with Mattermost.
If you have other work around to solve this issue, please let me know as well. thanks!

**Comment by jasonblais** [comment]
Added in Mattermost v4.1
