### ISSUE TITLE
"Write a message box" blocked by URL while hovering over channel name

### ISSUE THREAD

**Issue by sanfords** [mattermost/platform#5936]
Web App Version: 3.6.0  (3.6.2)
Mac App: Version 3.6.0 (3.6.0.3.6.0)

#### Summary
"Write a message box" blocked by URL while hovering over channel name.

#### Steps to reproduce
This issue can be reproduced in the Mac Mattermost app and a Mattermost Web site.  When the message area is narrow, the "Help" link in the lower right disappears.  This removes the gutter from the bottom of the window where the URL appears.  _The problem is especially bad with direct messages where the URLs are much longer._

1. Open Mattermost Mac app.
1. Make window narrow enough for the "Help" link in the lower right to disappear.
1. Click a channel in the channel list on the left.
1. Leave the mouse pointer there over a channel name.
1. Attempt to "write a message".
1. The URL bar blocks the text box and you can't see what you're typing.

#### Expected behavior
For the URL box to not block the message box.  I'd prefer no URL bar when hovering over channels.

#### Observed behavior
Please see attached screenshot.

<img width="469" alt="screen shot 2017-04-01 at 9 25 06 am" src="https://cloud.githubusercontent.com/assets/1291701/24580569/0403076a-16bf-11e7-8057-e2b7d7d545f8.png">

#### Possible fixes
This is more of a UI design issue.  It might be sufficient to add a margin to the bottom of the message box if there is no help link.  I see className='help__text' around that area.

**Comment by sanfords** [comment]
Whoops, this is an issue with the web app too.  When the window is narrow.  Moving this ticket to the proper project.

**Comment by sanfords** [comment]
Wait, this is the platform area.  Reopening.

**Comment by lindy65** [comment]
Hi @sanfords,

Thank you for your issue report!  Appreciated :)

I have tried to repro on the Desktop app in Windows and in the browser on Windows 7, Chrome but am not able to.  Tried as narrow as possible a window while still being able to see the channel list in the left-hand-side (as per your screenshot).

Could you clarify if you are seeing this issue in the browser or in the desktop app?  If you're seeing it in your browser, could we have your help [upgrading to the latest version of Mattermost](https://about.mattermost.com/download/) as it seems the issue is fixed in v3.7.3.

For the desktop app, what version of Windows are you using?

Thanks!

**Comment by sanfords** [comment]
This is most definitely fixed in 3.7.3.  Thank you!
