### ISSUE TITLE
Users can not leave a channel

### ISSUE THREAD

**Issue by realrolfje** [mattermost/platform#6152]
#### Summary
Some users report that they are immediately re-joined after leaving a channel.

#### Steps to reproduce
Login to with the same user on the same mattermost server twice (two different browsers, or a phone and a browser). We'll call the browsers A and B.

- Join channel X in both browsers.
- In browser A, leave channel X.
- In browser B, press reload (if browser B is on an Android phone, all you need to do is unlock the device to trigger a browser reload)

Other users in the channel will see a "...has left the channel" immediately followed by "...has joined the channel".

We believe this is caused by users having sessions on multiple (mobile) devices, which [constantly reload pages](https://www.quora.com/Why-do-all-Android-browsers-start-to-reload-the-page-after-minimizing-browser-activity) when activating the browser app. Another cause for this problem is people having bookmarked the Mattermost site while being on the channel they are now trying to leave.

#### Expected behavior
People should be able to leave the channel, even if they have it open in another session. The system should be user centric, not session centric.

#### Observed behavior

- People not being able to leave the channel
- Noise from join/leave messages of people trying to leave channels.

#### Possible fixes
A solution to this problem would be to make the join action explicit, as described in the issue [6153 Peek Channel before Joining](https://github.com/mattermost/platform/issues/6153).

**Comment by jasonblais** [comment]
Thanks @realrolfje - the observed behaviour is by design given you automatically join a channel from a public link.

So the user does indeed leave it, but clicking the link (or refreshing a page containing a URL to the channel) will have the user re-join the channel.

I agree that #6153 would solve the problem. [We have an existing feature proposal here](https://mattermost.uservoice.com/forums/306457-general/suggestions/12877668-ability-to-view-channels-without-joining). Would you like to contribute to the discussion and upvote it?

**Comment by realrolfje** [comment]
Done.

**Comment by jasonblais** [comment]
Thanks again for all the feedback! We can track the feature proposal here: https://mattermost.uservoice.com/forums/306457-general/suggestions/12877668-ability-to-view-channels-without-joining
