### ISSUE TITLE
[Help Wanted] [PLT-6403] Add Slack-compatible Action button for webhooks

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6293]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6403)

Per [this](https://mattermost.uservoice.com/forums/306457-general/suggestions/17678305-actions-and-buttons-to-incoming-webhooks) UserVoice request.

The scope of this ticket is limited to Message Buttons - Message Menus will be investigated separately in future, as it will be a much larger task to fully implement.

Developing this feature will necessitate:
- Alterations to the configuration of Incoming Web Hooks (& potentially Slash Commands)
- Additional server side code to support the action call-outs.
- Additional API/App layer code to support the new integration message button presses.
- Additional UI layer code to support the display (and API calls back to the server) of the message buttons.

If you wish to take on this ticket, once you have determined how you would like to implement each part of it, please discuss your plans with the core developer team in the [~developers](https://pre-release.mattermost.com/core/channels/developers) channel of our Mattermost server.

**Comment by ccbrown** [comment]
On it.

**Comment by ccbrown** [comment]
Hmm. While I could certainly add action buttons for webhooks, it looks like this would _not_ be Slack-compatible. Slack actually doesn't allow action buttons with webhooks. A Slack app is required (see [Slack FAQ: Message Buttons](https://api.slack.com/faq#message_buttons)). And we don't really have an equivalent to that right now.

So the options seem to be to either work on building out a system for Slack-compatible apps or implement this feature in a non-Slack-like way.

**Comment by ccbrown** [comment]
We don't have Slack-compatible apps on the roadmap, so this can't be Slack compatible to the extent of being able to use existing Slack integrations with the feature, but I can make it as close as possible for now.

In Slack, interactive messages are configured in the Slack app settings:

![screen shot 2017-07-17 at 8 54 59 pm](https://user-images.githubusercontent.com/1731074/28304419-5dfd3ff6-6b4c-11e7-8c3e-9fdb05a7573d.png)

For interactive Mattermost messages, I'll most likely just be adding that "request URL" or "action URL" to the incoming webhook settings. And I'll be implementing Slack attachment buttons using the same format as Slack.

But since you can't just plug in your existing Slack apps anyways, I'd also be extremely interested in hearing ideas on what interactive capabilities people would find useful beyond what Slack currently offers.

**Comment by pichouk** [comment]
For example, we would like to get this for the [Giphy integration](https://github.com/numberly/mattermost-integration-giphy). Currently, the Slash command return a GIF and post to channel. It could be great to have the same behavior as the Slack integration for Giphy :
- user use the `/giphy` command
- the server return a set of 10 possible GIF. The message is hidden and the user can choose (with interaction buttons) to :
  - post the proposed GIF
  - switch to another GIF (don't know if it is client or server side, but we will handle it anyway)
  - cancel the command

Some screenshots :
1) I launch the `/giphy` command and server send me [this](https://framapic.org/4uDNFqGHKnY5/MzRHFV426kl6.png)
2) Don't like the GIF, so I click on `Shuffle` button and then got [this](https://framapic.org/iDXjdvd0POS7/Q1veml1Ukm7N.png)
3) Like the new one so I click on `Send` button and [it post the GIF](https://framapic.org/KvUSoDyQ6lh4/Krhuvx2czAiO.png)

I don't know if it help, because I don't know how it run internally, but it is an interesting use case.

**Comment by jasonblais** [comment]
Closing the help wanted issue as we're working on this ticket internally.
