### ISSUE TITLE
[Help Wanted] [PLT-6469] Send HELO request containing domain name to SMTP server

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6318]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6469)

**Comment by cpanato** [comment]
I can take this one

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/platform/pull/6322

**Comment by cpanato** [comment]
I will make the change if you dont mind

**Comment by hmhealey** [comment]
I've re-opened this issue as the ticket may have had incorrect information on how to fix the issue. I'll post back here once we've made a decision on how to properly fix it

**Comment by hmhealey** [comment]
@nevesnunes Regarding your comment on https://github.com/mattermost/platform/pull/6322, would using `os.Hostname()` instead of the SiteURL setting be good enough here? We'd like to get this working properly, but using go-fqdn still seems like an unnecessary dependency. `os.Hostname` returned identical results to go-fqdn everywhere we tested it.

**Comment by nevesnunes** [comment]
It is a better solution, but will fail if the reported hostname doesn't match the FQDN.

`os.Hostname()` gets the name from the kernel, which on Linux is set on boot based on `/etc/hostname`. From what I can tell, traditionally this file only has the hostname, so we can't assume that every server will have the FQDN here. This difference also happens in my case. Indeed, the commands `hostname` and `hostname --fqdn` give me different results. For example, my hostname can be `foo` while the FQDN is something like `foo.bar.com`.

It's a messy situation, because there's no system library to provide this info directly. However, mail filters will use the FQDN to compare it with the ip of the server or the HELO string, depending on how picky they are.

**Comment by hmhealey** [comment]
Hi @nevesnunes,

Thanks for the feedback. I took it back to our core team, but we've decided that sending the Site URL (minus the protocol and port) should be enough to fix this issue. For a mail server on the local network, we haven't found it necessary to support sending a HELO with anything more than localhost, and for an external mail server, neither `os.Hostname()` nor go-fqdn's reverse lookup would make sense as they would both return the internal name for the server which would be useless for the external SMTP server. We'd like to focus our support on more standard setups with which we haven't had this issue reported before, so we won't be adding anything for this for the time being.
