### ISSUE TITLE
Custom emoji can be added/deleted by anyone

### ISSUE THREAD

**Issue by realrolfje** [mattermost/platform#6321]
#### Summary
When custom emoji are enabled, anyone can add or delete emoji. Disable emoji also breaks displaying existing custom emoji. This should be split in 2 rights.

#### Steps to reproduce
1. Enable custom emoji.
2. As user A, create a custom emoji, and use it in a post
3. As user B, delete a custom emoji, and/or replace the same emoji keyword with a different emoji
4. The original post from user A now has a completely different meaning (different or missing emoji).

#### Expected behavior
The system settings page shoud have two emoji settings:
- Display custom emoji (displays custom emoji in posts)
- Allow users to create custom emoji (enabeling this allows any user to create an emoji, but only delete his own emoji)
- System/Team admins should always be able to create custom emoji (company logo or other related things)

#### Observed behavior
When custom emoji is enabled, anyone can create or delete any emoji, enabeling some very annoying trolling.

#### Possible fixes
Split emoji rights as described above.

**Comment by it33** [comment]
### Please help us share your proposal in the feature proposal forum? 

Thank you for making an effort to contribute to the Mattermost open source project. Your time is valuable, and we highly appreciate your investment. 

Hundreds of engineers from around the world have contributed to this project through [community processes](https://about.mattermost.com/help/) that are openly documented. 

In the context of the [issue template](https://github.com/mattermost/platform/blob/master/ISSUE_TEMPLATE.md) presented when you created this issue, it seems this report is more a **feature proposal** (a change in the software's design) than a **bug report** (obviously unintentional behavior). 

Per the [issue template](https://github.com/mattermost/platform/blob/master/ISSUE_TEMPLATE.md), GitHub issues are used for [filing bug reports](https://www.mattermost.org/filing-issues/). 

We request your help to: 

- Consider closing this issue, because it does not meet the issue template requirements. 

You are welcome to continue discussion on this ticket after it is closed. 

We also welcome you to [open a feature proposal](https://www.mattermost.org/feature-ideas/) in the feature proposal forum where your idea can be discussed and upvoted by the community, 

Alternatively, if a similar proposal already exists, please consider upvoting and commenting?

Over [100 feature proposals](https://mattermost.uservoice.com/forums/306457-general/status/1588363) from the community have been added to the Mattermost open source project.

**Comment by realrolfje** [comment]
If person A can delete person B's smiley, that, to me, sounded like a bug. This is based on "common sense" and not specifications. So I'd like to update this issue and refer to the design, or post a "feature request". But in order to do that, I need an answer to the following question:

Is there a way for me to find out which functionality is by design and which is not?

**Comment by lindy65** [comment]
Hi @realrolfje,

Thanks for your question!

[Here](https://mattermost.atlassian.net/browse/PLT-3141) is the epic Jira ticket for custom emoji.  In the comments of the ticket is a link to custom emoji spec.

Hope this helps!

**Comment by realrolfje** [comment]
Hello @lindy65, I'm sorry to say this did not help. The JIRA issue links to (part of) the specifications I presume, but I do not have the rights to see that document or issue.

Is there a central, open, *complete* set of specifications for Mattermost? I notice that my expectations differ from what the Mattermost team has in mind when developing. Not only in functionality, but also in what the definition of "bug" is, and I'd like to prevent getting into arguments about that, because it slows down fixing the issues/features however you call them.

Thanks in advance, have a great weekend!

**Comment by lindy65** [comment]
Hi @realrolfje,

So sorry, my error entirely!  The link to the spec was in an internal ticket which prevented you from viewing the document.  [Here](https://docs.google.com/document/d/1-Ady_trvQuwvP7RoJ92HQ4k8dUrtN9aA7tj71MSEyNY/edit#heading=h.q4hh23uza3m4) is the spec.

The best place to ask about specs for Mattermost is in the [Spec Reviews](https://pre-release.mattermost.com/core/channels/spec-reviews) channel of our [Contributors Team](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676).  

Apologies again for the run around!

**Comment by lindy65** [comment]
Hi @realrolfje,

Circling back to check whether you have access to the spec and/or whether you joined Contributors Team to chat about the spec in the Spec Reviews channel?

**Comment by lindy65** [comment]
Hi @realrolfje, we haven't received an update so we'll close this off for now.  Feel free to reopen the issue if you need assistance accessing specs or joining the Contributors Team.
