### ISSUE TITLE
[Help Wanted] [PLT-6416] Add a status indicator to the profile picture in the header

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6327]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6416)

Add a status indicator to the profile picture in the header. The status indicator shows the current status (online/away/offline) of the account and let's them change their status manually.

![image](https://cloud.githubusercontent.com/assets/13119842/25904862/7d8b11c2-356e-11e7-8635-b71c1212b048.png)

Clicking the status icon or the profile picture offers a dropdown menu to select a status, one of online, away or offline.

Choosing one of the statuses should perform the same action as when executing the corresponding slash command (/online, /away, /offline).

Note: Currently the profile picture is hidden from the top left if it hasn't been manually set yet. Change it so the profile picture is always shown in the top left, even if it is the default generated profile picture.

**Comment by drojas** [comment]
Hi, can I pick this one?

**Comment by jasonblais** [comment]
sure thing! Thanks @drojas!

**Comment by drojas** [comment]
I've been doing some advancements and have some questions and comments.

Currently the entire sidebar header area is used to trigger two changes:

- On hover. A semitransparent black background appears and the username color changes.
- On click. The account settings dropdown is toggled.

The issue requests that the profile pic and status icon should trigger a status selector dropdown. So, in order to maintain a clear UI, how this entire sidebar header area should work with the new interactions (new dropdown with status changes)?  

1. Should we reduce the area that triggers the dropdown to cover just the menu icon on the right or to cover just the area of the icon plus the area with team and name information?
2. Should we change the area that triggers the onHover effect to match the dropdown toggles?
3. What about preserving the current mouse interactions and just add the statuses changes to the account dropdown.

**Comment by asaadmahmood** [comment]
Hey Drojas, really appreciate your help and interest here.
This is how it should behave.
1. Reducing the area should probably be a bit hard to do, something easier can just be that when a user is hovering over the profile picture, or the status icon, then it triggers a different even.
2. When a user is hovering over the profile picture, or the status icon, we can just have a different icon and style applied to the status icon. So instead of the online/away, if a user is hovering over it, maybe we can just place a "fa-edit" icon inside it, and have it take the `sidebarHeaderText` theme color.
3. I think we'll keep it separate for now, it would reduce clutter, and would also let the user easily focus on changing the icon, rather than searching for what he needs to do in a long list.

**Comment by drojas** [comment]
Thanks @asaadmahmood!

**Comment by jasonblais** [comment]
Great work @drojas! Excited to release this feature in Mattermost 3.10 :tada:
