### ISSUE TITLE
[Help Wanted] [PLT-6659] File preview images uploaded from mobile may be rotated

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6495]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6659)

This may require an additional library to read the EXIF flags from the image file and manually rotate the image, but there may be a CSS property or something we can use to do it without that

Repro steps:
1) Take a photo on a mobile device
2) Log into Mattermost using the old mobile app or browser
3) Upload the photo as a file attachment or profile picture

Observed: Before sending the post/saving the profile picture, the image appears rotated. After sending/saving, it will be upright
Expected: The image is upright in the preview

**Comment by emptyarray** [comment]
I'll take this one.

**Comment by coreyhulen** [comment]
@emptyarray it's all yours.

**Comment by emptyarray** [comment]
There are two places that image previews occur: the profile picture, and file uploads.

## Profile picture

The problem was that reading the image client-side and displaying was failing to account for EXIF rotation in images (e.g. from mobile phones). I came up with a fix by reading the EXIF rotation in JS.

## File uploads

This one works differently because the images are handled server side. The thumbnail and preview images get oriented on the server correctly. The reason the upload previews are different is because they are using the full-size original image. Not sure exactly why the EXIF rotation is being ignored, but it is. Either way, scaling down full-sized images is probably not optimal.

I can use the thumbnail or preview image instead, which are correctly oriented, though that has another issue: the aspect ratio may not work. The thumbnail rectangles have a fixed size. I've attached an image to illustrate the issue and some options:

![image](https://user-images.githubusercontent.com/1262053/27505004-0f469980-584a-11e7-8104-c61ddb3ba745.png)

Some of the possible ways to go:

- Use preview image, and let the thumbnail crop the image
- Use thumbnail, and have there be white padding due to the fixed dimensions of thumbnail rects.
- Use thumbnail, change the dimensions of thumbnail rects (more work than the other options)

As a separate issue, once images are uploaded, the thumbnail rect also has white padding around some images.

**Comment by coreyhulen** [comment]
@hmhealey or @jasonblais thoughts on the cropping?

**Comment by emptyarray** [comment]
Another possibility:

![image](https://user-images.githubusercontent.com/1262053/27519419-963cd0da-59a8-11e7-85f9-a30fe43d83de.png)

This is with `max-width: 120px` instead of `width: 120px`, which allows the width to size to fit the thumbnail.

The other issue is that once posted, the thumbnail images still have white padding, which doesn't match the preview. Not sure whether the posted thumbnail display is in the scope of this particular ticket, though.

**Comment by lfbrock** [comment]
Hi @emptyarray - we discussed it and decided Option 2 (cropped with no padding) is more consistent with our other file thumbnails at the moment, so let's go with that one.

**Comment by lindalumitchell** [comment]
Tested on master, Android old app, attachment and profile image; working as described. Closing.
