### ISSUE TITLE
Get a file API - NO FILE EXTENSIONS

### ISSUE THREAD

**Issue by andreydanil** [mattermost/platform#6497]
When I call the **Get a file** API, the return type is unknown. The URLs are BLOB URLS. There is no file extension, for example I want to return an MP4 video file. 

API CALL: 
https://your-mattermost-url.com/api/v3/files/{file_id}/get

Can the get a file api return the absolute path to the file? I am not able to stream video.

**Comment by prixone** [comment]
Not sure if that is by design or not, bu you have:

https://api.mattermost.com/#tag/files%2Fpaths%2F~1files~1%7Bfile_id%7D~1get_info%2Fget

```
 Copy Expand all Collapse all

{

    "id": "string",
    "user_id": "string",
    "post_id": "string",
    "create_at": 0,
    "update_at": 0,
    "delete_at": 0,
    "name": "string",
    "extension": "string",
    "size": 0,
    "mime_type": "string",
    "width": 0,
    "height": 0,
    "has_preview_image": true

}
```

**Comment by canhlinh** [comment]
@andreydanil Can you show me the response?

**Comment by lindy65** [comment]
Hi @andreydanil, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
