### ISSUE TITLE
[Bug] No user count update on town Square channel when add/remove users to the team

### ISSUE THREAD

**Issue by cpanato** [mattermost/platform#6517]
#### Summary
No update in the users counts for the `Town Square` channel when add/remove users to the team. Also when removing users there is no notification message saying the user leave the team.

#### Steps to reproduce
Add a user to the team or remove. The user count in the header of the channel will keep the same. Only after a refresh.

#### Expected behavior
Users count updated.

Videoscreen:
![8c4muwsz2q](https://cloud.githubusercontent.com/assets/4115580/26571493/7a2d44de-4516-11e7-8784-ceb5a1b1d393.gif)

**Comment by lindy65** [comment]
Thanks @cpanato !

I've repro'd your issue about total number of users in Town Square not updating when a person is added to the team (even although the join message is displayed in Town Square channel).  I've created a bug [ticket](https://mattermost.atlassian.net/browse/PLT-6693) to fix.

I think not displaying the `[USER] has been removed from the channel` is by design but perhaps @jasonblais can confirm this?

**Comment by jasonblais** [comment]
@cpanato @lindy65 

We actually have a help wanted ticket to update channel member count after adding a member to the team: https://github.com/mattermost/platform/issues/5978

We also have a help wanted ticket to add/update the system message when adding/removing someone from the team: https://github.com/mattermost/platform/issues/6483

**Comment by cpanato** [comment]
ah!! :)

I will try to take a look on those :)

**Comment by lindy65** [comment]
Thanks Jason! I'll close off the bug ticket I created as well as this issue and we can track via the help wanted tickets you linked above.
