### ISSUE TITLE
Feature Request: Add ability to serve Mattermost with own SSL certificate without Ngnix

### ISSUE THREAD

**Issue by damianwilczek** [mattermost/platform#652]

**Comment by coreyhulen** [comment]
The current recommendation is to use something like nginx for SSL termination, but it would be nice for Mattermost todo it all.  I've created https://mattermost.atlassian.net/browse/PLT-251 to track this issue.

**Comment by it33** [comment]
Hi @damianwilczek, closing this issue since there's a tracking ticket for it now. 

Would you be open to [filing a feature idea in the feature idea forum](http://www.mattermost.org/feature-requests/) so this change could be upvoted by the community? 

The work here is substantial, and having more community members showing interest would help raise its priority.
