### ISSUE TITLE
[Help Wanted] [PLT-3893] Clean up our common logger and move to structured logging

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#6603]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3893)

**Comment by MusikPolice** [comment]
Talked to @coreyhulen. I'll take a shot at this.

**Comment by coreyhulen** [comment]
Yup...go for it.

**Comment by MusikPolice** [comment]
- Looks like the project is using [log4go](https://github.com/alecthomas/log4go)
- That repository has been abandoned, but there is some documentation available [here](https://godoc.org/github.com/alecthomas/log4go) and on the [Google Code Archive](https://code.google.com/archive/p/log4go/wikis)
- One way to structure log messages might be to implement a custom [LogWriter](https://godoc.org/github.com/alecthomas/log4go#LogWriter) that transforms [LogRecord](https://godoc.org/github.com/alecthomas/log4go#LogRecord) objects into JSON strings. It's not clear how to add context to the existing LogRecord object.

## Alternatives to log4go
- While Googling about, I found an extremely mature log4go alternative that appears to support JSON formatting and context-based logging out of the box called [logrus](https://github.com/Sirupsen/logrus). Might be worth a look
- Another alternative could be [rlog](https://github.com/romana/rlog/). Doesn't appear to support JSON/context-based logging, but has a very rich configuration system

**Comment by coreyhulen** [comment]
We've been wanting to swtich off of log4go for a while because it's abandoned and it has know threading issues.  We've fixed a few of the most critical issues with our fork https://github.com/mattermost/log4go.

From an MM perspective creating our own logging interface would be best so we could switch from log4go to something like logrus once the code base is using our common logger interface with our context.

I would lean towards logrus, we've heard good things about that package.

**Comment by coreyhulen** [comment]
We also have some funky stuff coming down the pipe like https://github.com/mattermost/platform/pull/6499/files#diff-642801e00d0a75c05b55a6c11016ea74 which redirects the std log into our log.

**Comment by MusikPolice** [comment]
Spent some time poking around the codebase tonight, trying to sort out how everything works. Notes for my own sanity:
- entrypoint is in `mattermost.go`, which in turn calls `runServerCmd(...)` in `server.go`
- the current log library is very simple. the entire source is in vendor/github.com/alecthomas/log4go/log4go.go
- the Context object that Corey mentioned appears to live in api/context.go. It's pretty advanced. Might take some time to understand
- ideally, every call to `log4go.Info(...)` (or any other public method in log4go) would somehow access and include the current Context

**Comment by jostyee** [comment]
imo `logrus` is too heavy
https://dave.cheney.net/2015/11/05/lets-talk-about-logging

**Comment by coreyhulen** [comment]
For now I would probably ignore our context object in `api/context.go` and `api4/context.go` and work with the new builtin go context at https://golang.org/pkg/context.  There is another tix somewhere to refactor our context to use the new builtin one.

our context.go has a lot of http middleware type stuff built into it that needs to be refactored out :)

**Comment by coreyhulen** [comment]
For reference our context.go pre-dates the new builtin one introduce in go 1.7 (I think).

**Comment by coreyhulen** [comment]
Hopefully our interface will be pretty simple since we currently only use DEBUG, INFO, and ERROR and which logger we use (logrus or another) will be abstracted away.

Something to consider is allowing the context to have a `tracer=true` flag that when set overrides the output to DEBUG_PRINT=on.  We get a lot of requests for `Tracing all the way from the client request for a specific user` for customers who are trying to debug a production issues under heavy load.

**Comment by MusikPolice** [comment]
@jostyee I agree that logrus is heavier than it strictly needs to be. In general, I agree with the overall sentiment of that article, but I think the author takes it too far. The fact of the matter is that logs are not only meant to be human readable. Some applications require logs to be machine readable, so adding additional context to the log message is valuable. Further, applications that are intended to be long running should not default to dying a horrible death when an error occurs. Mattermost is a web application. It's acceptable for one web request to fail without tanking the entire application. To that end, I feel that DEBUG, INFO, and ERROR are all acceptable log levels. I'm not sure that I'd add any more than those.

**Comment by MusikPolice** [comment]
I've been reading about Go's `context` package, and have run into a potential problem with serializing it into a JSON string that can be logged.

Ideally, I'd like to use the `context` package in a manner similar to the `MappedDiagnosticContext` from Java's `Logback` library: A key-value store that is a property of the request thread on which values pertinent to the current request can be temporarily stored. In my day job, we log all sorts of context information (authenticated username, ip address, requested URL, etc) on the `MDC`, and serialize it into every log message (it's just a map of type `<String, String>`, so it's trivial to represent as a JSON object).

Go's `context.Context` object contains a map of values (both the key and the value of the map are of type `interface {}`, so any object can be used for either), but the Go docs strongly suggest a few best practices that make it less than ideal for carrying context information to be logged:

1. A `context.Context` object should never be stored in a `struct`, which means that our logger can't buffer log messages prior to writing them out, unless it serializes the `context.Context` at the time that the message is logged, rather than at the time that the buffer is flushed - this isn't actually a problem, but it's important to keep in mind

2. The keys in the `context.Context` value map should not be of type `string`. Rather, they are meant to be unexported types that belong to the class that adds them to the context. This prevents different classes putting keys that clash onto the same context and clobbering one another's values. Smart idea, since this is a common problem with the `MDC` in Java. This probably means that we have to create a central place to store all of the keys that we wish to use because...

3. There doesn't appear to be any way to iterate over the map of values in a `context.Context` object. It provides a `WithValue(...)` function that adds a value to the map, and a `Value(...)` function that retrieves the value for a supplied key. As such, the logger has to know about all keys that are put into a `context.Context`, or at least all keys that we wish to serialize into the log message.

None of these issues are insurmountable, but they will inform the design of the logger in a very real way, so they're worth noting.

**Comment by MusikPolice** [comment]
Discussed with @coreyhulen. Decided that the logger will keep the context keys in internal consts, as this is [suggested best practice](https://medium.com/@matryer/context-keys-in-go-5312346a868d). The logger will export some functions that let users add specific items to the `Context`. This will give us whitelist control over what values are logged, in case sensitive stuff is inadvertently put on the `Context`.

These functions probably look something like this:
```
func LogUsername(ctx context.Context, username string) context.Context {
    return context.withValue(ctx, usernameContextKey, username)
}
```

Eventually, these individual functions will probably be replaced with a single function that takes a Request object or similar as a parameter and adds all relevant values to the Context in one shot. Then this method call could be placed at the start of every request handler and it would automagically populate the Context with relevant values.

**Comment by jasonblais** [comment]
Beign worked on by Mattermost staff, closing this help wanted ticket https://mattermost.atlassian.net/browse/PLT-3893
