### ISSUE TITLE
Path in a message result in message error (command not found)

### ISSUE THREAD

**Issue by michael87** [mattermost/platform#6646]
As developer sometimes i try share a path in a command. I sometimes forget that / in the beginning not works, because it can not find a path. But in stead of show a message that it has the wrong command and leave the message in the input field. It clear the input field. 

After writing a long message, it ends in frustration that i lost my message. Can it change to leave the message and show a message?

#### Steps to reproduce
Type in the input field:
/path/to/directory and a nice message 

Hit the enter key

#### Expected behavior
Leave the message in the input field how it is and show an error to inform the user that it can not fulfill what he wanted to do. In this case (s)he can change the message by adding something before the pad
 
#### Observed behavior
What happen is: 
Command with a trigger of 'path/to/directory' not found

At this point you can write the message again, because the message not appear anymore in the field. Also the history of the field is empty.

#### Possible fixes
Leave the message in the input field and show a error.

**Comment by lfbrock** [comment]
Hi @michael87 - thanks for the report, 

I think it will be hard to just send a message starting with a `/` since we don't know if it's a slash command or not, but I wrote a [ticket](https://mattermost.atlassian.net/browse/PLT-6847) here to improve the experience by: 

1. Keeping the message in the text box if it fails to send 
2. Updating the error message to let users know to include a space at the beginning if they need to send a message starting with a slash 

Let me know if there's feedback on those proposed changes?

**Comment by michael87** [comment]
Hi @lfbrock ,

Thanks for responding. This is exactly what i mean. I didn't saw this ticket. :+1:

**Comment by lfbrock** [comment]
I actually just made the ticket based on your report, so thanks for bringing it up :) 

I'll close this GitHub issue, and track the issue in Jira. 

We also have a Help Wanted ticket here if anyone would like to contribute a fix for this: https://github.com/mattermost/platform/issues/6659
