### ISSUE TITLE
New Channel - When editing the channel URL to an empty value it does not fallback to the channel name

### ISSUE THREAD

**Issue by fasterforward** [mattermost/platform#6670]
#### Summary
New Channel - When editing the channel URL to an empty value it does not fallback to the channel name 

#### Steps to reproduce
As a system administrator

1) Create new channel
2) Directly edit the Channel URL e.g. "Dev"
3) Give the channel a name e.g. "Development"
4) Edit the Channel URL again to an empty value and click the button "Change Channel URL"
5) Mattermost throws the message "URL must be two or more characters."

#### Expected behavior
As a user the expected behavior is that after step 4 the URL is automatically changed to the given channel name in step 2 and no message is thrown.

**Comment by lindy65** [comment]
Hi @fasterforward,

Thank you for your feedback,

I'll ask one of the product managers to take a look at your issue as it does seem that it would make sense to fall back to the default channel name given in step 2. if the user goes back to edit the channel URL to be an empty value as per step 4.

**Comment by esethna** [comment]
Hi @fasterforward, thanks for your comment,

Can you please help me understand why it is expected behavior to repopulate the field with the old channel URL if the user clicks "Change Channel URL"? The "Close" button will revert the channel URL to the old value. In my mind I think it would cause more confusion to have a value save something different than the user input in the text box.

**Comment by lindy65** [comment]
Hi @fasterforward, 

It seems this is no longer an issue for you so I'll close it off for now.  Please feel free to reopen and continue the discussion.

Thanks!
