### ISSUE TITLE
"view channel" API race conditions

### ISSUE THREAD

**Issue by kquick** [mattermost/platform#6803]
Need ability to synchronize client's time with servers.

The need to determine any possible skew between the client's time and the server's time can be important for handling message updates.  For example, if a message is delivered to the client (via WebSocket) and the user then selects that channel, the client sends a POST to indicate the channel has been viewed (https://api.mattermost.com/v4/#tag/channels%2Fpaths%2F~1channels~1members~1%7Buser_id%7D~1view%2Fpost).  The POST doesn't provide a timestamp or get a timestamp in response, so the client must associate that POST with a local time.  Any subsequent post delivered via Websocket has a timestamp that the client can compare to the POST time to see if it should indicate that there are new messages, but this will fail if there is significant skew between client and server.

This can be exacerbated if the server or client loses NTP access and suffers significant drift or reboot reset.

If the client config response (https://api.mattermost.com/v4/#tag/system%2Fpaths%2F%7E1config%7E1client%2Fget) included the server's current timestamp value, the client can observe the potential skew and make appropriate allowances (or warnings).

**Comment by kquick** [comment]
Upon further reflection it would also be nice to have the response to the view/post contain the timestamp that the server actually applied to the channel.

Having the timestamp in the view/post response would allow the client to utilize only server time values for management, alleviating the need to reconcile any skew with local time.

Having the timestamp in the config/client/get response would allow the client to warn the user (or take some other action) if there was significant skew between the client's time and the server's time.  This is less important if the view/post response contains a timestamp, but it still may be useful since times sent from server to eyeball will differ from local system eyeball values.

**Comment by jwilander** [comment]
Hi @kquick, it would be relatively simple to add a header to each response that has the server time. Would that suit your purposes?

**Comment by ccbrown** [comment]
I think the best way to eliminate the race conditions around this would actually be for the "view" API to accept an additional request parameter: The timestamp of the latest post viewed. Otherwise, there will always be race conditions just as a side-effect of the request's transit and processing time. For example:

* I start in channel A.
* I switch to channel B to clear a notification.
* My client fires off a "view" request for channel B.
* I quickly switch back to channel A.
* My Wi-Fi is shaky, so that "view" request for channel B hasn't gotten through yet.
* Messages are posted in channel B.
* The "view" request for channel B finally gets through to the server.
* The server considers messages in channel B that I haven't actually looked at viewed.

So you can eliminate those types of race conditions if the client says "I've seen all of the posts up through this time.". Then of course, it doesn't need the server to respond with a timestamp or anything else.

**Comment by ccbrown** [comment]
Also, @jwilander, @kquick, all of the responses already have the server time in the "Date" header. That's placed there by the Go standard library, so you should always have that available to get the server time.

**Comment by jwilander** [comment]
I wasn't aware the "Date" header was already added, good to know.

As for adding the extra request parameter to the view request, that makes sense to add. The client will need to make sure to provide the create_at time of the most recent post it has, rather than the time the request was made, but that should be trivial enough. Only other consideration is that the extra request parameter should be optional for backwards compatibility and for if the client doesn't care about possible races like this.

**Comment by jtdaugherty** [comment]
@ccbrown - I'm not sure the response Date header will be helpful here. Presumably the timestamp given in that header is the time at which the response is sent, but what we need is the timestamp that ends up being stored in the Mattermost database *as a result of the view API call*, i.e., the value that we will get next time we request the user-specific metadata for that channel to get the user's last-view time.

Still, I'm inclined to agree that a better approach is for us to supply the server timestamp associated with the most recent message we know about rather than relying on side effects.

**Comment by kquick** [comment]
While the Date header is interesting for the purpose of approximating the skew between server and client times, it doesn't seem like quite the right thing to use for the "viewed" POST since (I assume) it's generated by the transmit logic and doesn't necessarily correspond to the date entered into the DB.  Normally this is probably a very small difference, but it's weaker for busy channels, and what if I am on that shaky WiFi...

Regarding adding the "create_at" time to the viewed POST request: that sounds intriguing, but how does that work relative to edited or deleted posts?  I guess I'm asking what the purpose of the "viewed" POST is.  Is it primarily to allow the client to know where to draw the "New" line on startup and send push notifications, or is there more to it beyond that, and are edits and deletions expected to be ignored for the "New" marker and notifications?  What if I'm highlighting every message that has changed since the last viewing time? 

I understand that I'm potentially creeping the scope here, but if we are examining alternatives to improve correctness I'm just trying to make sure the target is well defined.

**Comment by ccbrown** [comment]
@jtdaugherty Yeah, I would definitely recommend against clients using the Date header for things like this. I don't think it really solves any problems. Just wanted to mention that it's already there, since it was specifically considered.

@kquick No behavior would really change. The effects of the API invocation would just rely less on real-world timing. Currently, when you make that POST request, it more or less just sets your "LastViewedAt" time to the channel's "LastPostAt" time, which may have changed since you initiated the request. My proposal is just that you send an additional parameter so that the API can set your "LastViewedAt" time to the channel's "LastPostAt" time as it was when you initiated the request rather than when the server received it. As @jtdaugherty pointed out, your new "LastViewedAt" time is the thing the client really wants to know when making this request. And since it's something you would set yourself, no additional response fields would be necessary.

**Comment by kquick** [comment]
Further experimentation shows that we would also need to look at Edited and Deleted times for posts as well as LastPostAt, and use the maximum reported time for any of those as the value we would send to the server for a "viewed" update.  Based on that, it seems like getting the server's assigned value back in the POST response would be the simplest and most accurate approach.

**Comment by ccbrown** [comment]
I don't really have anything new to add, but I do want to keep this issue moving forward since there definitely seems to be a legit bug here. I also want to avoid falling into the trap of an [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem), so I'm gonna sum this up again:

**The Problem:**

> If a message is delivered to the client (via WebSocket) and the user then selects that channel, the client sends a POST to indicate the channel has been viewed (https://api.mattermost.com/v4/#tag/channels%2Fpaths%2F~1channels~1members~1%7Buser_id%7D~1view%2Fpost). The POST doesn't provide a timestamp or get a timestamp in response, so the client must associate that POST with a local time. Any subsequent post delivered via Websocket has a timestamp that the client can compare to the POST time to see if it should indicate that there are new messages, but this will fail if there is significant skew between client and server.

In other words: The client sends a POST request upon opening a channel to mark the channel as viewed. The server marks the channel as being viewed at the time that it receives that POST request. If there is significant skew between these two times for any reason, the client and server may disagree on which messages are new.

**Proposal A:**

Have the server send its time in the [client config response](https://api.mattermost.com/v4/#tag/system%2Fpaths%2F%7E1config%7E1client%2Fget).

**Proposal B:**

Have the server respond to the client with the time at which the server considered the channel viewed.

**Proposal C:**

Have the client inform the server of the time at which the server should consider the channel viewed.

**My personal opinion:**

Proposal A wouldn't allow the client to do anything that it can't already do with the `Date` headers on every response. Proposal B is probably easier to implement than proposal C and it fixes the problem of clock skew. But it does leave a race condition: The server will consider posts that were made during transit of the client's POST request to be viewed.

So I agree that B is probably the simplest approach and does mitigate the problem, but I believe C is the most accurate.

Maybe @jwilander has other opinions on this? Or @coreyhulen?

**Comment by jtdaugherty** [comment]
@ccbrown - I have an alternative proposal. My objective with this one is to *get us out of the business of having to deal with server time at all* and the issues that arise from doing so. The proposal is this:

Rather than relying on server time *at the time the POST is received*, which suffers from network transit delays and clock skew and is thus inaccurate, make the API call take *the ID of the most recently-viewed post that the client saw*.

* For channels with no messages at all, the post ID can be omitted, meaning "use the server time." There may still be a possibility of a race here, but it's also an uncommon situation.
* Clients that haven't updated to the new behavior can still omit the post ID this way and get the old behavior, but clients that send the post ID get a better outcome because *if* they need to know the server time that was used for the view update, they can look at the post metadata of that post.
* I haven't thought deeply about how this interacts with deleted posts. Say the most recent post is deleted, and the client issues the API call to update the view time using the post *before* that one. This isn't great because that timestamp will be further back in time.
* Another issue here is the question of how to rectify the existence of up to three timestamps on each post: creation, editing, and deletion. In Matterhorn we have `max(max(create, edit), delete)`, essentially, but that's easy to get wrong.

What do you think?

**Comment by ccbrown** [comment]
@jtdaugherty I would definitely want to send the id if posts had an absolute ordering that clients were guaranteed to receive them in (e.g. via a monotonic sequence number). But we don't have that, so figuring out which posts come after a particular id would come down to looking at timestamps, which aren't actually guaranteed to be monotonic in a multi-node cluster. So I think as a result of those deeply rooted design decisions, sending the id would be behaviorally equivalent to sending the timestamp of the latest viewed post.

**Comment by jtdaugherty** [comment]
@ccbrown - that makes sense, thanks! In that case I favor proposal (B).

**Comment by lindy65** [comment]
Thanks @ccbrown @jtdaugherty @kquick 

I've created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7404) to track the issue so will close it off here.
