### ISSUE TITLE
API Specification

### ISSUE THREAD

**Issue by cathalgarvey** [mattermost/platform#69]
I see that the code appears to be logically organised around a clean-looking API; I can go and read through the Go source and get to understand it, but it'd be better if there were a specification of that API clearly written somewhere for reference. As this is a developing project, it'd especially be useful to know what parts of the API are considered "stable".

Lets-Chat have an API spec which was invaluable to me in writing a [Python API wrapper](https://github.com/cathalgarvey/python-letschat) and I'd love to do the same for MatterMost. :)

**Comment by it33** [comment]
Hi cathalgarvey, thanks for the question--would love to have your help building an Python API wrapper!

It's only been a day since we went public with the project, the current 0.5.0 release is considered a "preview", and we can't really guarantee API stability. http://www.mattermost.org/mattermost-0-5-0-released/

That said, documenting the APIs--perhaps some of the more mature ones that are more likely to be stable--is a good idea, and I've posted it as a community feature request for voting here: https://mattermost.zendesk.com/hc/communities/public/questions/204327305-API-Specification

It's early days, and hope we get more and more discussion about how to best prioritize projects.
