### ISSUE TITLE
Deleting a message does not delete files in storage

### ISSUE THREAD

**Issue by sho-suzuki** [mattermost/platform#6990]
#### Summary
Bug report in one concise sentence

#### Steps to reproduce
we use 4.0.1 enterprise edition (but License file is not applied.)
`config.json` setting is as follows.

```json:config.json
    "FileSettings": {
        "EnableFileAttachments": true,
        "MaxFileSize": 52428800,
        "DriverName": "local",
        "Directory": "/opt/mattermost/data/",
        "EnablePublicLink": true,
        "PublicLinkSalt": "A705AklYF8MFDOfcwh*****",
        "InitialFont": "luximbi.ttf",
    }
```
1. drag and drop the file.
1. write a message to textarea and press the enter button.
1. mouse over the message and click delete.
1. confirm -> yes to succeed to delete message and related file.

#### Expected behavior
When deleting a message with an attached file, the real file is erased as well.

#### Observed behavior (that appears unintentional) 
Real file is still remains in local file directory after the operation.
there is no errors.

**Comment by prixone** [comment]
I don't think that is unintentional because all the said "delete" feature of Mattermost is a soft delete, that means it doesn't completely delete anything it just hides it.

So if you go to your database directly and search for the message you deleted you will find it there along with the DeleteAt which indicates when it was deleted.

So the same goes for the file, access to the file from Mattermost is removed but it does not physically delete the file.

**Comment by sho-suzuki** [comment]
Thank you for your reply.
I have understood the design policy to delete messages and files without permanently deleting them.
