### ISSUE TITLE
Dots after HTTP link are included in the link on Mac client...

### ISSUE THREAD

**Issue by jaapvermeulen** [mattermost/platform#7043]
#### Summary
Dots after an HTTP link are included in the link on Mac client...

#### Steps to reproduce
Type the following message into the Mattermost Mac client and hit enter (or control-enter):

`@all Yay!  Got xxx to run over SSL.  https://xxx-yyy.aaa.bbb...
`
#### Expected behavior

The link that becomes "live" is:

`https://xxx-yyy.aaa.bbb
`
#### Observed behavior (that appears unintentional) 

The link that became "live" included 2 dots at the end of the URL (copied as link from the mattermost Mac client):

`https://xxx-yyy.aaa.bbb../
`
#### Possible fixes

Ignore trailing punctuation?

**Comment by hmhealey** [comment]
Thanks, that's kind of interesting. I guess we only trim off the last period since it's not followed by anything else. I've filed a couple tickets for both our web and mobile apps to fix this. Here's the links if you want to follow them:
https://mattermost.atlassian.net/browse/PLT-7250
https://mattermost.atlassian.net/browse/RN-300

**Comment by hmhealey** [comment]
A fix for this has been merged and will be in the web/desktop apps for Mattermost 4.1 (coming out in a few days) and the mobile app version 1.2 (coming out in a few weeks). Feel free to reopen this ticket if you're seeing this happen again after you've upgraded
