### ISSUE TITLE
Text input box and some messages not visible. Borderline unusable.

### ISSUE THREAD

**Issue by wesviewzr** [mattermost/platform#7056]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Text input and some messages not visible.
#### Steps to reproduce
Version 3.7.0 on macOS Sierra 10.12.5

#### Expected behavior
I would expect to be able to see the text input. Currently I cannot even see the text I'm typing into the box. I would expect that zooming out or resizing the screen would correct the issue, but it makes things worse. Zooming in and making the window smaller seems to help slightly. When I can't see the text I'm typing the app is essentially unusable.

#### Observed behavior (that appears unintentional) 
![screen shot 2017-07-29 at 12 41 05 pm](https://user-images.githubusercontent.com/13283469/28747415-4c7a2f74-745b-11e7-9651-b1ba25005d42.png)
![screen shot 2017-07-29 at 12 40 52 pm](https://user-images.githubusercontent.com/13283469/28747414-4c78cbf2-745b-11e7-81d4-09b671b13fd1.png)
![screen shot 2017-07-29 at 12 40 39 pm](https://user-images.githubusercontent.com/13283469/28747416-4c7a24f2-745b-11e7-9e76-b90d723ce62f.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by jasonblais** [comment]
Yes, there's an upstream issue that's causing this. https://github.com/electron/electron/issues/7375

As a workaround @wesviewzr , can you click somewhere inside the message area, then hit CMD+0?

That should resize the view properly so that the entire UI is visible on the screen. Let me know if not

**Comment by lindy65** [comment]
Hi @wesviewzr 

We haven't received an update so we'll assume that the problem is fixed or is no longer valid.  If you still experience the same problem, try upgrading to the latest version.  If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
