### ISSUE TITLE
Add feature to add badge to the user

### ISSUE THREAD

**Issue by augustnmonteiro** [mattermost/platform#7070]
#### Summary
Our case is a bit different than the most ones, we have an open mattermost and would be good have a badge saying that the user it's a member.
Like github does on the prs or issues.

```
<userphoto> <username> [Member]
<chat>

<userphoto> <username> [Member]
<chat>

<userphoto> <username> [Member]
<chat>
```

**Comment by augustnmonteiro** [comment]
It would be also good in the case of pre-release.mattermost

**Comment by lindy65** [comment]
Hi @augustnmonteiro,

### Please help us share your proposal in the feature proposal forum? 

Thank you for making an effort to contribute to the Mattermost open source project. Your time is valuable, and we highly appreciate your investment. 

Hundreds of engineers from around the world have contributed to this project through [community processes](https://about.mattermost.com/help/) that are openly documented. 

In the context of the [issue template](https://github.com/mattermost/platform/blob/master/ISSUE_TEMPLATE.md) presented when you created this issue, it seems this report is more a **feature proposal** (a change in the software's design) than a **bug report** (obviously unintentional behavior). 

Per the [issue template](https://github.com/mattermost/platform/blob/master/ISSUE_TEMPLATE.md), GitHub issues are used for [filing bug reports](https://www.mattermost.org/filing-issues/). 

We request your help to: 

- Consider closing this issue, because it does not meet the issue template requirements. 

You are welcome to continue discussion on this ticket after it is closed. 

We also welcome you to [open a feature proposal](https://www.mattermost.org/feature-ideas/) in the feature proposal forum where your idea can be discussed and upvoted by the community, 

Alternatively, if a similar proposal already exists, please consider upvoting and commenting?

Over [100 feature proposals](https://mattermost.uservoice.com/forums/306457-general/status/1588363) from the community have been added to the Mattermost open source project.

**Comment by lindy65** [comment]
I'll close this off here for now and @augustnmonteiro can open a feature request for it.
