### ISSUE TITLE
[Help Wanted] [PLT-7256] Turning off email batching results in no email notification selected

### ISSUE THREAD

**Issue by esethna** [mattermost/platform#7081]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7256)

Repro:

1) Enable email batching in server config or System Console > Email Notifications
2) In account settings, change email notifications to "Immediate" and save, then back to "15 minutes" and save.
3) Disable email batching in server config or System Console > Email Notifications
4) In account settings, notice that there is no email rate selected, because "15 minutes" is not a supported option when batching is disabled.

Expected: "Immediately" selected as the email rate.

**Comment by pruthvip** [comment]
Wanted to work on this. Wanted some clarifications.

Hence while digging through , i saw that we take the value `this.state.emailInterval` from PreferenceStore, which keeps a map(preferences) which is synced with the redux store. But why are we calling PreferenceStore.getInt() , with separate flags 

`if (global.mm_config.EnableEmailBatching === 'true') {
            // when email batching is enabled, the default interval is 15 minutes
            this.state = {
                emailInterval: PreferenceStore.getInt(Preferences.CATEGORY_NOTIFICATIONS, Preferences.EMAIL_INTERVAL, Preferences.INTERVAL_FIFTEEN_MINUTES)
            };
        } else {
            // otherwise, the default interval is immediately
            this.state = {
                emailInterval: PreferenceStore.getInt(Preferences.CATEGORY_NOTIFICATIONS, Preferences.EMAIL_INTERVAL, Preferences.INTERVAL_IMMEDIATE)
            };
        }`

When the store doesn't consider the third param

`getInt(category, name, defaultValue = 0) {
        const key = this.getKey(category, name);

        if (!this.preferences.has(key)) {
            return defaultValue;
        }

        return parseInt(this.preferences.get(key), 10);
    }`

since , `this.preferences.has(key)` is present, it always returns 900. Because of which the error comes. 

Hence if any change is required, it should be done in the redux part of the application?

**Comment by MusikPolice** [comment]
Hi @pruthvip, I believe that the API is returning 900 in this case because it returns the selected email interval in seconds, and 900 seconds is 15 minutes, which is what you selected in the Account Settings dialog.

The server stores the selected email interval in a single preference, regardless of whether email batching is active or not. As such, I see a couple of ways of fixing the issue:

1. Change the preference store so that there are two separate settings, one for batched email notification interval, and one for non-batched email notification interval
2. Modify the component to recognize that an email notification interval of 900s is invalid if email batching is disabled, and default it back to 30s (immediate) in this case.
