### ISSUE TITLE
Switching from MySQL to PostgreSQL in default install

### ISSUE THREAD

**Issue by Omeryl** [mattermost/platform#71]
Any particular reason we're using Oracle's MySQL over better/nicer alternatives, like MariaDB?

**Comment by it33** [comment]
hi Omeryl, thanks for the question. We basically chose MySQL because of its popularity. It wasn't a value judgement, just using what people were most likely to find familiar.

**Comment by Omeryl** [comment]
Hey @it33, MariaDB is still MySQL, just completely open unlike Oracle's MySQL (it's actually a fork of MySQL maintained by the original developer of MySQL). It has major advantages over Oracle's MySQL.

https://mariadb.org/

**Comment by hauleth** [comment]
IMHO the nicest solution would be PostgreSQL

**Comment by ShawnMilo** [comment]
In many people's opinion's, PostgreSQL is a very good database, and MySQL [is not](https://groups.google.com/forum/#!msg/django-users/AKpy31__Nec/vW0eLf42COcJ), really. Also, very informative, short [video](https://www.youtube.com/watch?v=emgJtr9tIME) of MySQL behaving unforgivably with its default configuration.

**Comment by it33** [comment]
@Omeryl, @hauleth, @ShawnMilo, I've added feature requests (http://www.mattermost.org/feature-requests/) for MariaDB and Postgres support at https://mattermost.zendesk.com/hc/communities/public/questions/203129919-Support-for-MariaDB- and 
https://mattermost.zendesk.com/hc/communities/public/questions/204331285-Support-for-PostgreSQL and made the first upvote on each. 

Please consider joining the forum (one click with Twitter, Google or Facebook) to continue the discussion? 

This is the third day of the open source project and your input as the earliest members of the community on this topic is highly appreciated. 

Since these topics appear to be more feature requests than issues in the context of the project (http://www.mattermost.org/filing-issues/), I'm closing this thread so discussion can continue in the feature request forum.

**Comment by Omeryl** [comment]
Meh, I don't think a Zendesk sufficiently satisfies things like this. It's an open source project, the first thing people will see is the "Issues" portion of the repo more than likely. Why not properly tag issues? @it33

**Comment by it33** [comment]
@Omeryl It's a good question. 

I think ideally for feature requests we'd want to offer the community a way to vote on, search through and browse trending feature requests similar to http://feedback.gitlab.com/forums/176466-general/filters/hot

GitHub Issues doesn't seem to support what we believe we'll need long term--and I agree Zendesk doesn't either, it's just what we were using for the video game business, and was familiar. 

It's starting to break already and maybe we should go to Uservoice for this. I wasn't sure how high priority that work was. 

You're making us think a lot this week, @Omeryl. Thank you, don't stop :)

**Comment by it33** [comment]
After more community discussion and a feature request filing, the core team will be changing from MySQL in the default install to PostgreSQL for the 0.6.0 release at the end of the month: http://mattermost.uservoice.com/forums/306457-general/suggestions/8589070-support-for-postgresql

MariaDB was also considered, but it didn't end up as the top community choice. 

@Omeryl, we're also switching to using GitHub issues with proper tags. Thanks again for your feedback. It took us a week, but we're finding our way now.

**Comment by kamilion** [comment]
Bleh, postgresql instead of rethinkdb? Seriously, you guys even mention them on your blog!

http://www.mattermost.org/on-premises-open-source-slack-alternative/

That was the whole reason I *CAME*, cause I thought I'd get a nice new rethinkdb project!

Oh well. At least it's postgresql, can't really complain there. Anything but mysql.

Such a shame -- rethinkdb totally fits the mattermost model to a T.

**Comment by alexsun** [comment]
so, I'm can help with switching from MySQL to PostgreSQL.
also at this time can check possibilities about RethinkDB

**Comment by coreyhulen** [comment]
@alexsun thanks.  there is already a pull request submitted for postgresql.

**Comment by coreyhulen** [comment]
postgres if fixed with https://github.com/mattermost/platform/pull/170
