### ISSUE TITLE
Mentions badge missing on Mac

### ISSUE THREAD

**Issue by jaapvermeulen** [mattermost/platform#7126]
#### Summary
Using the Mac native client, it is missing the "mentions" badge and you cannot see how many messages you haven't seen yet.

#### Steps to reproduce
Select a channel that will not receive new messages.
Generate new messages in other channels.
Open the application and observe whether there are badges showing for channels with unread messages.

#### Expected behavior
Expect to see a badge with the number of unread messages when the channel is not selected and has unread messages (also for team)

#### Observed behavior (that appears unintentional) 
Sometimes the badges show, sometimes they do not.  I attached a couple of screenshots where the badges are not showing on the Mac client.  In the first one (ExpectBadgeOnWebAndMobileApp) there are pending messages in the "Web and Mobile App" channel, but  there is no corresponding badge.  You can see a badge for one of the private channels.  In the second one (ExpectBadgeOnTeamIcon) there are pending messages for a different team.  You can see the dot to the left of the team icon, but no badge on the team icon.

![expectbadgeonwebandmobleapp](https://user-images.githubusercontent.com/4005724/28985713-102a781a-7921-11e7-8ce3-427b79da185f.png)
![expectbadgeonteamicon](https://user-images.githubusercontent.com/4005724/28985716-17aeda2c-7921-11e7-9faa-156f9267a221.png)

**Comment by jasonblais** [comment]
Thanks @jaapvermeulen for the report. Does this reproduce on Chrome (or another browser on Mac)?

**Comment by jaapvermeulen** [comment]
Jason, I have been checking it with both chrome and firefox this morning.  Unfortunately, the amount of traffic is not that high right now, but I observed the following:

- This morning the badge *did* show up for the *team* icon in the native client (as I mentioned it sometimes shows up; it almost seems related to whether the screen is locked or not)
- When I generate messages myself in the native clients, both browsers would NOT show a badge for the team icons (but the dot to the left *would* show up), and NEITHER show a badge NOR bolded text for the channel once I switched to the team (the last selected channel was not the channel with the new message).
- When I received a message from someone else, native and browsers showed the same behavior as explained in the original bug description: no badge (but dot) for team, no badge (but bolded text) for channel.

I hope the above all makes sense.  I'm running the Linux server on RHEL7:
Version: 4.0.0  (4.0.1)
Database: postgres (9.2.18)

If anything, it seems to me that should be readily reproducible in a similar environment?
Obviously this is not a serious issue, but more an inconvenience.

**Comment by jaapvermeulen** [comment]
One last tidbit.  The reverse for the 2nd bullet in the previous comment is true as well.  Submitting a message in the browser will produce the same behavior in the native client.  All this seems to be pointing back to the server I assume.

**Comment by jaapvermeulen** [comment]
Sorry for the many comments.  Come to think about it a little more, sending yourself messages is not the best test case anyway.  The message is most likely immediately marked 'read' (because it's showing in the client that you used for sending the message) but for some reason the team is still marked as having new messages (if that 's not the currently selected team).  When you select that team, it doesn't show anything because there ends up being no unread messages.  So that case is explained except maybe for why the team is still tagged for having new messages (and whether that's to be expected).

**Comment by jasonblais** [comment]
@jaapvermeulen Thanks for the additional information here. Very useful.

So I think I understand what's going on,

1) The "badge" that shows a count, actually counts how many mentions you've received.  Mentions trigger when someone sends a message that includes your username or any of the options selected in **Account Settings > Notifications > Words that trigger mentions**.

![image](https://user-images.githubusercontent.com/13119842/29041332-780303c4-7b80-11e7-8bd8-480d4c451648.png)

2) If you receive a message that doesn't contain a mention, then the channel is only bolded. Similarly, the team icon only has a dot (instead of a badge). 

We do have a [feature proposal here](https://mattermost.uservoice.com/forums/306457-general/suggestions/13740840-add-badge-for-all-unread-non-mention-messages) for having the badge count unread messages instead of unread mentions only.

I'd encourage you to upvote it. You get **10** votes in the feature idea forum, and each one influences the future of the project.

3) We also had a bug where unread messages from yourself sometimes were shown as unreads, sometimes not. But in Mattermost v4.1, your own messages won't show up as unreads across tabs, or browsers ([ticket link](https://mattermost.atlassian.net/browse/PLT-6683))

----

Sorry I didn't realize this from your original post, but hopefully that's helpful.

We really appreciate the feedback. Let me know if you have any further questions or thoughts.

**Comment by jaapvermeulen** [comment]
So, that doesn't completely make sense.  I set my 'Desktop Notifications' to 'For all activity'...  Are you saying that I still ONLY get badges for messages that I'm mentioned in and not for all unread messages?  If that's the case, it is *completely* non-intuitive and I strongly suggest to change this behavior...

**Comment by jaapvermeulen** [comment]
Well, the documentation explains it: https://docs.mattermost.com/help/getting-started/configuring-notifications.html, so I guess I'm in the wrong and my expectations are not not in line with what your documentation says.  Still think this is an odd way of showing badges that I haven't really run into before (as you can tell from my confusion, and I've been around 30 years and worked with many UIs).  Another way to solve this whole thing is to add an option to make the badge show unread messages instead of 'mentions'.  But that's a feature... :-)  I'll close it.

**Comment by jasonblais** [comment]
Thanks @jaapvermeulen for the feedback! That's really valuable, I'll share it with our design team as well.

Really appreciate you taking the time here.
