### ISSUE TITLE
URLs in Markdown not parsed correctly for character ' (%27)

### ISSUE THREAD

**Issue by th-joerger** [mattermost/platform#7150]
#### Summary
URLs in Markdown not parsed correctly for character ' (%27)

#### Steps to reproduce
Post e. g.
```
[Poe's law in action](https://en.wikipedia.org/wiki/Poe's_law)
```
to a chat in the Mattermost Windows Desktop Client 3.7.0

#### Expected behavior
It should be become:
[Poe's law in action](https://en.wikipedia.org/wiki/Poe's_law)

#### Observed behavior (that appears unintentional)
It becomes
<div>[Poe's law in action](<a href="https://en.wikipedia.org/wiki/Poe's_law">https://en.wikipedia.org/wiki/Poe's_law</a>)</div>

with the url part auto-linked to a clickable link.

#### Possible fixes / Workaround
Replace the character ' by %27
```
[Poe's law in action](https://en.wikipedia.org/wiki/Poe%27s_law)
```
everything works as expected.

**Comment by hmhealey** [comment]
Hi @th-joerger,

Thanks for the report. Looks like our current markdown library doesn't like single quotes or double quotes in those links because it's confusing them with the syntax for adding a title to links. I've filed [a Jira ticket](https://mattermost.atlassian.net/browse/PLT-7353) for this if you'd like to follow it. However, we're working on overhauling our markdown library right now, so it may not get fixed until that's all done

**Comment by th-joerger** [comment]
@hmhealey Thanks for the fast response and confirming this :)

**Comment by lindy65** [comment]
The PR has been submitted so I'll close the issue off here and we can track via the ticket.
