### ISSUE TITLE
Why no foreign keys?

### ISSUE THREAD

**Issue by ThiefMaster** [mattermost/platform#7193]
I just looked at the database structure of a Mattermost instance and noticed that it does not use any Foreign Keys to enforce consistency in the database. Is there any reason for this?

**Comment by ccbrown** [comment]
Posted in our developer channel about this since I've also been curious: https://pre-release.mattermost.com/core/pl/tneqwhaocbgsppc8uyg4bjzzgw

As it stands, my best guess is "no", there's no particular reason for it.

**Comment by lindy65** [comment]
Hi @ThiefMaster,

Feedback from our devs after discussing this issue is that there is "insufficient motivation". No one seems to have strong enough opinions that we should add foreign keys at this point.

Perhaps you'd like to open a suggestion on our [Feature Ideas Forum](https://mattermost.uservoice.com/forums/306457-general) which you and others can up-vote?  The more votes a suggestion gets, the more chance it has of making it into the product.

I'll close this issue off here for now.
