### ISSUE TITLE
Change emoji's color

### ISSUE THREAD

**Issue by S6066** [mattermost/platform#7262]
With Mattermost 4.1, emojis changed. Some users (like me) don't like that
For example, all "hand" emojis turned yellow, instead of usual white
A way to change the color (in user's settings) of this kind of emojis like Slack does would be cool

**Comment by hmhealey** [comment]
Hi @S6066, 

We changed it to yellow since it's a neutral skin tone. I don't believe we're planning on supporting alternate skin tones yet, but feel free to make a suggestion [on our Feature Ideas forum](https://mattermost.uservoice.com/forums/306457-general) so we can gauge community interest when prioritizing changes

**Comment by h-town** [comment]
> 
> 
> Hi @S6066,
> 
> We changed it to yellow since it's a neutral skin tone. I don't believe we're planning on supporting alternate skin tones yet, but feel free to make a suggestion [on our Feature Ideas forum](https://mattermost.uservoice.com/forums/306457-general) so we can gauge community interest when prioritizing changes

TIL Jaundice is a neutral skin tone

**Comment by p3k** [comment]
maybe it’s the right time **now** to change this behaviour. it is very irritating to see the correct display of the emojis in the editor and then get a uniform look in the actual post. black emojis matter(most)!

![image](https://user-images.githubusercontent.com/16631/85422336-c8082700-b575-11ea-8f7b-63b311dc2529.png)

**Comment by hmhealey** [comment]
Hi @p3k. That actually appears to be a bug. This issue was filed back when we changed our default emoji images to all be yellow since a handful of random emojis had previously had different skin tones.

Nowadays, we're a bit behind on the emojis that we support, but all the ones that we do support should include full skin tone support. I don't know why this one in particular isn't working since the text form of it works (`:fist_raised_dark_skin_tone:`) and other emojis like `👍🏾` render in Mattermost correctly using both the unicode and text forms. We did previously have a similar bug where some gendered emojis were rendering with the incorrect gender, so perhaps this is related.

I've filed [a Jira ticket](https://mattermost.atlassian.net/browse/MM-26573) to look into this more.

**Comment by hmhealey** [comment]
I found out what the issue was. It had to do with an ancient bug in the code that converts unicode into the names that emoji image files are stored under, and it only affected a few older emojis such as this one and the raised hand emoji (✋).

There's a PR to fix it here: https://github.com/mattermost/mattermost-webapp/pull/5818

**Comment by p3k** [comment]
Thanks for the quick action, @hmhealey very much appreciated.
