### ISSUE TITLE
Routing on front-end (single-page app / react-router)

### ISSUE THREAD

**Issue by apaatsio** [mattermost/platform#790]
Have you considered doing routing on the client side? Now the UI logic is split so that the routing is in the backend and rest of the UI is in the frontend.

I think it would be better if it was a true single-page app. This should be pretty straight-forward with react-router. Basically we would have to implement the routes that are now in `web/web.go` with react-router and implement the page templates in `web/templates` as react components. We probably need some new API calls also for logging in and out. 

Why?

- simpler architecture: one complete react app instead of react app + routing and templates in backend
- single-page app is much easier to wrap with PhoneGap/Cordova
- faster; app-like feel

**Comment by it33** [comment]
Hi @apaatsio, 

We've discussed this internally and we agree with your suggestion, it's just a large change, and we're not sure how to fit this in our queue. It's also hard to label this "Accepting Pull Requests", because it would require a lot of work and could be very hard to test and to review, particularly since the project is so fast moving right now. 

We think either we'll need to do some refactoring later and this could be part of the changes made (and testing to be done), or perhaps there is someone in the community who wants a very difficult challenge.

We'll have to come back to this one. We do agree on your thoughts.

**Comment by STRML** [comment]
+1 to this. I am the maintainer of [React-Router-Component](https://github.com/STRML/react-router-component) which is a simple routing library. React-Router is generally better supported and better-known, so I'd recommend it instead, but whichever you choose will have a big impact on the app. 

Once it's properly single-page, it should be easy(ier) to get a basic PhoneGap app going.

**Comment by lfbrock** [comment]
Closing this issue, it will be tracked in a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-1680)
