### ISSUE TITLE
Inviting a member

### ISSUE THREAD

**Issue by sskmani** [mattermost/platform#85]

**Comment by sskmani** [comment]
How should i invite a member to domain without email verification.

**Comment by jwilander** [comment]
Hi sskmani,

You should be able to click on the three vertical dots in the top-left next to your team name and go to "Get Team Invite Link". That should open a dialog on with a link you can copy. Give that link to the user you want to join and they should be able to sign up for your team.

We're planning on making a blog post about how to use the core features of the system, so stay tuned! We're also always looking for feedback on any part of our system, so let us know if you like/don't like something :)

**Comment by it33** [comment]
hi @sskmani, we're started a forum thread about this issue at http://discourse.mattermost.org/t/how-to-invite-a-member-after-setup/18. You can continue the conversation with a 1-click login with your GitHub account. 

Since this topic does not appear to require a code change, we're closing the Issue in GitHub. Please open a new issue if you feel a code change is appropriate.
