### ISSUE TITLE
Hubot integration

### ISSUE THREAD

**Issue by bramvdbogaerde** [mattermost/platform#89]
How could this be integrated with Hubot?

**Comment by it33** [comment]
Hi @bramvdbogaerde, we're working support for creating applications that integrate with services like Hubot. Hope to share some early designs soon. Right now (less than a week after going open source), there's not a straight forward way to accomplish this.

In the meantime, the best way to influence product direction is by creating Feature Requests and creating agreement in the community around the new feature: http://www.mattermost.org/feature-requests/

**Comment by kenden** [comment]
As you suggested, here is a feature request for a Hipchat integration:
http://mattermost.uservoice.com/forums/306457-general/suggestions/8867041-add-a-way-to-integrate-with-hubot
:+1: for it!

**Comment by bramvdbogaerde** [comment]
:+1:

**Comment by kenden** [comment]
Should be solved with:
https://github.com/mattermost/platform/pull/715

**Comment by bramvdbogaerde** [comment]
Does this also include outgoing webhooks so something like Hubot also can receive messages?

**Comment by mindlapse** [comment]
The hubot-mattermost adapter is now available - I'm using it and it works well.

https://github.com/renanvicente/hubot-mattermost

Note: If you're running mattermost as a docker container on linux then you may need to update your iptables with incoming & outgoing rules for the docker0 interface.

**Comment by loafoe** [comment]
Another adapter is available which uses the Mattermost API directly. It also sets up a websocket connection for real-time events triggers (join/leave channel):

https://github.com/loafoe/hubot-matteruser

Amongst other things it also allows your Hubot to join private channels and you can send it DMs. 
Setting it up is IMHO also simpler since it does not use webhooks.

(author here, so apology for the shameless plug)
