### ISSUE TITLE
Accepting Pull Requests: Vagrant based developer setup 

### ISSUE THREAD

**Issue by CHIEFnChowCombo** [mattermost/platform#940]
I'd like to submit a PR with a Vagrant based setup for easy localized development. The install/setup guides are great already, but I think it'd be great to offer the option for those who like the vagrant workflow.

It could significantly simplify the [developer-setup](http://docs.mattermost.org/developer/Setup/index.html) for those who wish to use vagrant.

**Comment by stephenfin** [comment]
I'm consigned to using Windows for the majority of my work so I'd also like to make use this. Ideally (for me) this would deploy three different boxes for the DB, reverse proxy server and application server (the latter two could be combined). This would allow for [fast upgrades without losing data](https://github.com/mattermost/platform/issues/919).

I'd personally take whatever I could get though heh.

**Comment by it33** [comment]
Thanks @H3Chief, would love a PR here! 

Here's [a guide we've prepared for helping improve Mattermost documentation](https://forum.mattermost.org/t/help-improve-mattermost-documentation/194), and some [general guidelines](http://www.mattermost.org/documentation-guidelines/). 

Hugely appreciated!

**Comment by H3Chief** [comment]
@stephenfin I've been using Vagrant's [multi-machine](https://docs.vagrantup.com/v2/multi-machine/) capability lately to run this type of setup. usually, i'll have one VM as a local puppet/ansible agent, and the other machines to represent the responsibilities of machines in my deployment infrastructure.

I can create a base multi-vm vagrant file in addition to a simple all-in-one vagrant vm.

**Comment by stephenfin** [comment]
Yay :smile:

I'd vote Ansible for a new development like this (I'm a big fan and that's where [the market seems to be moving](http://thenewstack.io/are-docker-users-migrating-to-ansible-and-away-from-puppet-and-chef/)) but hey: I'm not the guy implementing this.

**Comment by H3Chief** [comment]
yes, that was actually my plan.  When I get beyond the basic config of docker provider, I'll ping you for some feedback on the multiple nodes.

**Comment by stephenfin** [comment]
Looking forward to it

**Comment by tomitm** [comment]
I was playing around with this today. As a Windows dev, there's a couple of hurdles, like the `Makefile` and also globbing (`**/*.jsx`) in the npm inline scripts.

Unfortunately, npm [doesn't get along well](https://twitter.com/othiym23/status/661622178484322304) with Vagrant/VirtualBox's shared folders. From what I can gather, it sounds like there's issues with long paths (which I don't think I ran into today) and symlinks.

Lastly, I don't think Ansible runs natively on Windows yet, without having to workaround with cygwin. It's possible there might have been improvements since I last checked though.

Feel free to ping me if you want someone to test on Windows!

**Comment by H3Chief** [comment]
@tomitm i think you have the wrong idea about how this all works. Everything is installed and run on the VM, not on your host machine, including Ansible and node/npm. Synced folder would be limited to source code and data containers, not development tools.

**Comment by tomitm** [comment]
@H3Chief Yep, I realise that.

I had docker/go/node/npm/ruby/compass setup in the vagrant VM, and the synced folder (default `/vagrant`) so I could make changes on the host IDE. The hurdles I mentioned were my motivation for playing around with this, as they wouldn't be an issue with a Vagrant setup.

The problems I was having lie with `npm install` which uses of symlinks. Under Windows, npm uses a cmd workaround instead, but since it's not executing in Windows (*that's the point*), it's using symlinks. However...

At this point, everything sounds like it *should* work fine, but from reading through issues earlier in the npm and vagrant repos, it sounds like VirtualBox's shared filesystem that operates the syncing is causing errors. There's even a note about this in [Vagrant's documentation](https://docs.vagrantup.com/v2/synced-folders/basic_usage.html) (see *Symbolic Links*), which implies the npm issue.

To be more specific, I was getting an `ETXTBSY` error from `npm install`, which lead me to npm issues about vagrant and symlinks. If you do a search for that you'll find some issues referring to what I'm talking about.

I did get to a point where eventually I managed to get npm install to complete miraculously, but then the npm scripts couldn't find `watchify` and `browserify` at which point I called it a day.

I'll try to find the key issues for you tomorrow, if you're interested.

**Comment by H3Chief** [comment]
Yeah. This could be big. I'll get into it this afternoon also.

**Comment by tomitm** [comment]
Quick update for Windows - latest VirtualBox fixes the issue with long paths and Vagrant re-enabled UNC path support on Windows, so next Vagrant release should work great. As long as you run `vagrant up` as administrator, that'll allow symlinks to be created as well, so that it seems that npm should work now. :tada:

If you're still working on this @H3Chief, I'd be excited to see this as it makes the barrier to contributing much lower.

**Comment by esethna** [comment]
[Ticket]https://mattermost.atlassian.net/browse/PLT-1860) created, closing as it will be tracked in JIRA.

**Comment by CHIEFnChowCombo** [comment]
Actually, I finished this already. I use it for testing the development of
Matterfront. Check it out here:
https://github.com/HackerHappyHour/matterfront
