### ISSUE TITLE
Special characters are dropped for channel hyperlinks

### ISSUE THREAD

**Issue by stephenfin** [mattermost/platform#965]
This may be a non-issue but I'm reporting it just in case.

If I try to create a channel with a special character, like so:

    Articles & Blogs

Then the URL that Mattermost presents drops those special characters, like so:

    articles--blogs

This isn't a **huge** deal - just slightly annoying. The use of special characters is a selling point of Mattermost so it's probably not practical to disallow them. If this is the case, I'd either strip the extra spaces (after stripping the special characters) or encode the special characters.

However, it also highlights another "bug". Should I try to create another channel with a similar name but different special characters then the handles clashe:

![image](https://cloud.githubusercontent.com/assets/1690835/10344758/b5e47700-6cea-11e5-92b1-7a7629b64749.png)

There should probably be (a) some autoresolution of handles (adding a number at the end) or (b) a better error message.

**Comment by it33** [comment]
Thanks @stephenfin!

I think stripping out the extra spaces would work. Happy to take a pull request on that. Encoding characters seems tricky, because generally we'd want Channel URLs that are easy to type, e.g. `/join articles-blogs` rather than `/join articles-[encoded characters]-blogs` 

Regarding the error message on colliding URL names, I believe this was updated in v1.0: 
![image](https://cloud.githubusercontent.com/assets/177788/10359524/57cb3654-6d4e-11e5-84c0-dcbff845c63d.png)

We have a public [test instance](https://gitlab.mattermost.com/signup_user_complete/?id=fqbr3mubzjg9ty7cks5xkxr3hh) with v1.0 up and running if you want to try it out?

The test instance will get updated to v1.1 RC1 shortly, and would love to have your feedback on that as well,

**Comment by it33** [comment]
Thanks @girishso for fixing!
